# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui\dialogSliceConverter.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_dialogSliceConverter(object):
    def setupUi(self, dialogSliceConverter):
        dialogSliceConverter.setObjectName("dialogSliceConverter")
        dialogSliceConverter.resize(763, 482)
        self.gridLayout = QtWidgets.QGridLayout(dialogSliceConverter)
        self.gridLayout.setObjectName("gridLayout")
        self.buttonBrowseSF = QtWidgets.QPushButton(dialogSliceConverter)
        self.buttonBrowseSF.setObjectName("buttonBrowseSF")
        self.gridLayout.addWidget(self.buttonBrowseSF, 2, 0, 1, 2)
        self.label_2 = QtWidgets.QLabel(dialogSliceConverter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 2)
        self.graphicsLayerPreview = ImageViewer(dialogSliceConverter)
        self.graphicsLayerPreview.setObjectName("graphicsLayerPreview")
        self.gridLayout.addWidget(self.graphicsLayerPreview, 1, 2, 5, 4)
        self.pushButton_3 = QtWidgets.QPushButton(dialogSliceConverter)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 5, 0, 2, 2)
        self.pushButton = QtWidgets.QPushButton(dialogSliceConverter)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 3, 0, 1, 2)
        self.pushButton_2 = QtWidgets.QPushButton(dialogSliceConverter)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 4, 0, 1, 2)
        self.progressBar = QtWidgets.QProgressBar(dialogSliceConverter)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setTextVisible(True)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 15, 0, 1, 2)
        self.lineFolder = QtWidgets.QLineEdit(dialogSliceConverter)
        self.lineFolder.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineFolder.setReadOnly(True)
        self.lineFolder.setObjectName("lineFolder")
        self.gridLayout.addWidget(self.lineFolder, 8, 0, 1, 2)
        self.labelStatus = QtWidgets.QLabel(dialogSliceConverter)
        self.labelStatus.setAlignment(QtCore.Qt.AlignCenter)
        self.labelStatus.setObjectName("labelStatus")
        self.gridLayout.addWidget(self.labelStatus, 14, 0, 1, 2)
        self.labelLayerNumber = QtWidgets.QLabel(dialogSliceConverter)
        self.labelLayerNumber.setObjectName("labelLayerNumber")
        self.gridLayout.addWidget(self.labelLayerNumber, 6, 5, 2, 1)
        self.buttonDone = QtWidgets.QPushButton(dialogSliceConverter)
        self.buttonDone.setMinimumSize(QtCore.QSize(95, 0))
        self.buttonDone.setObjectName("buttonDone")
        self.gridLayout.addWidget(self.buttonDone, 12, 4, 2, 2)
        self.labelStatusSlice = QtWidgets.QLabel(dialogSliceConverter)
        self.labelStatusSlice.setAlignment(QtCore.Qt.AlignCenter)
        self.labelStatusSlice.setObjectName("labelStatusSlice")
        self.gridLayout.addWidget(self.labelStatusSlice, 13, 0, 1, 2)
        self.label = QtWidgets.QLabel(dialogSliceConverter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 7, 0, 1, 2)
        self.pushBrowseOF = QtWidgets.QPushButton(dialogSliceConverter)
        self.pushBrowseOF.setObjectName("pushBrowseOF")
        self.gridLayout.addWidget(self.pushBrowseOF, 9, 0, 1, 1)
        self.checkRange = QtWidgets.QCheckBox(dialogSliceConverter)
        self.checkRange.setEnabled(False)
        self.checkRange.setObjectName("checkRange")
        self.gridLayout.addWidget(self.checkRange, 10, 0, 1, 2)
        self.spinRangeLow = QtWidgets.QSpinBox(dialogSliceConverter)
        self.spinRangeLow.setEnabled(False)
        self.spinRangeLow.setMinimum(1)
        self.spinRangeLow.setMaximum(99999)
        self.spinRangeLow.setObjectName("spinRangeLow")
        self.gridLayout.addWidget(self.spinRangeLow, 11, 0, 1, 2)
        self.spinRangeHigh = QtWidgets.QSpinBox(dialogSliceConverter)
        self.spinRangeHigh.setEnabled(False)
        self.spinRangeHigh.setMinimum(1)
        self.spinRangeHigh.setMaximum(99999)
        self.spinRangeHigh.setObjectName("spinRangeHigh")
        self.gridLayout.addWidget(self.spinRangeHigh, 12, 0, 1, 2)
        self.labelLayerPreview = QtWidgets.QLabel(dialogSliceConverter)
        self.labelLayerPreview.setObjectName("labelLayerPreview")
        self.gridLayout.addWidget(self.labelLayerPreview, 0, 2, 1, 4)
        self.labelLayerNumberTitle = QtWidgets.QLabel(dialogSliceConverter)
        self.labelLayerNumberTitle.setObjectName("labelLayerNumberTitle")
        self.gridLayout.addWidget(self.labelLayerNumberTitle, 6, 4, 2, 1)
        self.listSliceFiles = QtWidgets.QListWidget(dialogSliceConverter)
        self.listSliceFiles.setObjectName("listSliceFiles")
        self.gridLayout.addWidget(self.listSliceFiles, 1, 0, 1, 2)
        self.pushPreviewLayer = QtWidgets.QPushButton(dialogSliceConverter)
        self.pushPreviewLayer.setObjectName("pushPreviewLayer")
        self.gridLayout.addWidget(self.pushPreviewLayer, 8, 2, 1, 1)
        self.spinPreviewLayer = QtWidgets.QSpinBox(dialogSliceConverter)
        self.spinPreviewLayer.setMinimum(1)
        self.spinPreviewLayer.setObjectName("spinPreviewLayer")
        self.gridLayout.addWidget(self.spinPreviewLayer, 8, 3, 1, 1)

        self.retranslateUi(dialogSliceConverter)
        self.buttonDone.clicked.connect(dialogSliceConverter.close)
        self.checkRange.toggled['bool'].connect(self.spinRangeLow.setEnabled)
        self.checkRange.toggled['bool'].connect(self.spinRangeHigh.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(dialogSliceConverter)
        dialogSliceConverter.setTabOrder(self.listSliceFiles, self.buttonDone)

    def retranslateUi(self, dialogSliceConverter):
        _translate = QtCore.QCoreApplication.translate
        dialogSliceConverter.setWindowTitle(_translate("dialogSliceConverter", "Slice Converter"))
        self.buttonBrowseSF.setText(_translate("dialogSliceConverter", "Add Slice Files"))
        self.label_2.setText(_translate("dialogSliceConverter", "Slice Files"))
        self.pushButton_3.setText(_translate("dialogSliceConverter", "Draw Contours"))
        self.pushButton.setText(_translate("dialogSliceConverter", "Remove Selected Files"))
        self.pushButton_2.setText(_translate("dialogSliceConverter", "Convert to Contours"))
        self.labelStatus.setText(_translate("dialogSliceConverter", "Please select a .cli file(s) to convert."))
        self.labelLayerNumber.setText(_translate("dialogSliceConverter", "0000 / 0000"))
        self.buttonDone.setText(_translate("dialogSliceConverter", "Done"))
        self.labelStatusSlice.setText(_translate("dialogSliceConverter", "Current Part: None"))
        self.label.setText(_translate("dialogSliceConverter", "Output Folder"))
        self.pushBrowseOF.setText(_translate("dialogSliceConverter", "Browse..."))
        self.checkRange.setText(_translate("dialogSliceConverter", "Draw Range"))
        self.labelLayerPreview.setText(_translate("dialogSliceConverter", "Layer Preview"))
        self.labelLayerNumberTitle.setText(_translate("dialogSliceConverter", "Layer Number"))
        self.pushPreviewLayer.setText(_translate("dialogSliceConverter", "Preview Layer"))

from ui_elements import ImageViewer
