# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui\dialogOverlayAdjustment.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_dialogOverlayAdjustment(object):
    def setupUi(self, dialogOverlayAdjustment):
        dialogOverlayAdjustment.setObjectName("dialogOverlayAdjustment")
        dialogOverlayAdjustment.resize(361, 361)
        dialogOverlayAdjustment.setMinimumSize(QtCore.QSize(361, 361))
        dialogOverlayAdjustment.setMaximumSize(QtCore.QSize(361, 361))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("logo.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        dialogOverlayAdjustment.setWindowIcon(icon)
        self.labelInformation = QtWidgets.QLabel(dialogOverlayAdjustment)
        self.labelInformation.setGeometry(QtCore.QRect(10, 5, 351, 41))
        self.labelInformation.setWordWrap(True)
        self.labelInformation.setObjectName("labelInformation")
        self.buttonDone = QtWidgets.QPushButton(dialogOverlayAdjustment)
        self.buttonDone.setGeometry(QtCore.QRect(200, 323, 151, 28))
        self.buttonDone.setObjectName("buttonDone")
        self.groupValues = QtWidgets.QGroupBox(dialogOverlayAdjustment)
        self.groupValues.setEnabled(True)
        self.groupValues.setGeometry(QtCore.QRect(10, 50, 139, 91))
        self.groupValues.setObjectName("groupValues")
        self.gridLayout = QtWidgets.QGridLayout(self.groupValues)
        self.gridLayout.setObjectName("gridLayout")
        self.labelPixels = QtWidgets.QLabel(self.groupValues)
        self.labelPixels.setObjectName("labelPixels")
        self.gridLayout.addWidget(self.labelPixels, 0, 0, 1, 1)
        self.spinPixels = QtWidgets.QSpinBox(self.groupValues)
        self.spinPixels.setMinimum(1)
        self.spinPixels.setMaximum(5000)
        self.spinPixels.setObjectName("spinPixels")
        self.gridLayout.addWidget(self.spinPixels, 0, 1, 1, 1)
        self.labelDegrees = QtWidgets.QLabel(self.groupValues)
        self.labelDegrees.setObjectName("labelDegrees")
        self.gridLayout.addWidget(self.labelDegrees, 1, 0, 1, 1)
        self.spinDegrees = QtWidgets.QDoubleSpinBox(self.groupValues)
        self.spinDegrees.setMinimum(0.0)
        self.spinDegrees.setMaximum(360.0)
        self.spinDegrees.setProperty("value", 1.0)
        self.spinDegrees.setObjectName("spinDegrees")
        self.gridLayout.addWidget(self.spinDegrees, 1, 1, 1, 1)
        self.groupTranslation = QtWidgets.QGroupBox(dialogOverlayAdjustment)
        self.groupTranslation.setGeometry(QtCore.QRect(270, 50, 81, 191))
        self.groupTranslation.setObjectName("groupTranslation")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupTranslation)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.buttonTranslateUp = QtWidgets.QPushButton(self.groupTranslation)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.buttonTranslateUp.setFont(font)
        self.buttonTranslateUp.setObjectName("buttonTranslateUp")
        self.gridLayout_2.addWidget(self.buttonTranslateUp, 0, 0, 1, 1)
        self.buttonTranslateDown = QtWidgets.QPushButton(self.groupTranslation)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.buttonTranslateDown.setFont(font)
        self.buttonTranslateDown.setObjectName("buttonTranslateDown")
        self.gridLayout_2.addWidget(self.buttonTranslateDown, 1, 0, 1, 1)
        self.buttonTranslateLeft = QtWidgets.QPushButton(self.groupTranslation)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.buttonTranslateLeft.setFont(font)
        self.buttonTranslateLeft.setObjectName("buttonTranslateLeft")
        self.gridLayout_2.addWidget(self.buttonTranslateLeft, 2, 0, 1, 1)
        self.buttonTranslateRight = QtWidgets.QPushButton(self.groupTranslation)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.buttonTranslateRight.setFont(font)
        self.buttonTranslateRight.setObjectName("buttonTranslateRight")
        self.gridLayout_2.addWidget(self.buttonTranslateRight, 3, 0, 1, 1)
        self.groupRotationFlip = QtWidgets.QGroupBox(dialogOverlayAdjustment)
        self.groupRotationFlip.setGeometry(QtCore.QRect(200, 250, 151, 71))
        self.groupRotationFlip.setObjectName("groupRotationFlip")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupRotationFlip)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.buttonRotateACW = QtWidgets.QPushButton(self.groupRotationFlip)
        self.buttonRotateACW.setMinimumSize(QtCore.QSize(31, 31))
        self.buttonRotateACW.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.buttonRotateACW.setFont(font)
        self.buttonRotateACW.setObjectName("buttonRotateACW")
        self.horizontalLayout.addWidget(self.buttonRotateACW)
        self.buttonRotateCW = QtWidgets.QPushButton(self.groupRotationFlip)
        self.buttonRotateCW.setMinimumSize(QtCore.QSize(31, 31))
        self.buttonRotateCW.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.buttonRotateCW.setFont(font)
        self.buttonRotateCW.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.buttonRotateCW.setObjectName("buttonRotateCW")
        self.horizontalLayout.addWidget(self.buttonRotateCW)
        self.buttonFlipHorizontal = QtWidgets.QPushButton(self.groupRotationFlip)
        self.buttonFlipHorizontal.setMinimumSize(QtCore.QSize(31, 31))
        self.buttonFlipHorizontal.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.buttonFlipHorizontal.setFont(font)
        self.buttonFlipHorizontal.setObjectName("buttonFlipHorizontal")
        self.horizontalLayout.addWidget(self.buttonFlipHorizontal)
        self.buttonFlipVertical = QtWidgets.QPushButton(self.groupRotationFlip)
        self.buttonFlipVertical.setMinimumSize(QtCore.QSize(31, 31))
        self.buttonFlipVertical.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.buttonFlipVertical.setFont(font)
        self.buttonFlipVertical.setObjectName("buttonFlipVertical")
        self.horizontalLayout.addWidget(self.buttonFlipVertical)
        self.groupStretchPull = QtWidgets.QGroupBox(dialogOverlayAdjustment)
        self.groupStretchPull.setGeometry(QtCore.QRect(10, 150, 181, 201))
        self.groupStretchPull.setObjectName("groupStretchPull")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupStretchPull)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.buttonStretchLeftUp = QtWidgets.QPushButton(self.groupStretchPull)
        self.buttonStretchLeftUp.setMinimumSize(QtCore.QSize(31, 31))
        self.buttonStretchLeftUp.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.buttonStretchLeftUp.setFont(font)
        self.buttonStretchLeftUp.setCheckable(True)
        self.buttonStretchLeftUp.setObjectName("buttonStretchLeftUp")
        self.gridLayout_4.addWidget(self.buttonStretchLeftUp, 0, 1, 1, 1)
        self.buttonStretchRightUp = QtWidgets.QPushButton(self.groupStretchPull)
        self.buttonStretchRightUp.setMinimumSize(QtCore.QSize(31, 31))
        self.buttonStretchRightUp.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.buttonStretchRightUp.setFont(font)
        self.buttonStretchRightUp.setCheckable(True)
        self.buttonStretchRightUp.setObjectName("buttonStretchRightUp")
        self.gridLayout_4.addWidget(self.buttonStretchRightUp, 0, 3, 1, 1)
        self.buttonStretchUpLeft = QtWidgets.QPushButton(self.groupStretchPull)
        self.buttonStretchUpLeft.setMinimumSize(QtCore.QSize(31, 31))
        self.buttonStretchUpLeft.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.buttonStretchUpLeft.setFont(font)
        self.buttonStretchUpLeft.setCheckable(True)
        self.buttonStretchUpLeft.setObjectName("buttonStretchUpLeft")
        self.gridLayout_4.addWidget(self.buttonStretchUpLeft, 1, 0, 1, 1)
        self.buttonStretchNW = QtWidgets.QPushButton(self.groupStretchPull)
        self.buttonStretchNW.setMinimumSize(QtCore.QSize(31, 31))
        self.buttonStretchNW.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.buttonStretchNW.setFont(font)
        self.buttonStretchNW.setCheckable(True)
        self.buttonStretchNW.setObjectName("buttonStretchNW")
        self.gridLayout_4.addWidget(self.buttonStretchNW, 1, 1, 1, 1)
        self.buttonStretchN = QtWidgets.QPushButton(self.groupStretchPull)
        self.buttonStretchN.setMinimumSize(QtCore.QSize(31, 31))
        self.buttonStretchN.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.buttonStretchN.setFont(font)
        self.buttonStretchN.setCheckable(True)
        self.buttonStretchN.setObjectName("buttonStretchN")
        self.gridLayout_4.addWidget(self.buttonStretchN, 1, 2, 1, 1)
        self.buttonStretchNE = QtWidgets.QPushButton(self.groupStretchPull)
        self.buttonStretchNE.setMinimumSize(QtCore.QSize(31, 31))
        self.buttonStretchNE.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.buttonStretchNE.setFont(font)
        self.buttonStretchNE.setCheckable(True)
        self.buttonStretchNE.setObjectName("buttonStretchNE")
        self.gridLayout_4.addWidget(self.buttonStretchNE, 1, 3, 1, 1)
        self.buttonStretchUpRight = QtWidgets.QPushButton(self.groupStretchPull)
        self.buttonStretchUpRight.setMinimumSize(QtCore.QSize(31, 31))
        self.buttonStretchUpRight.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.buttonStretchUpRight.setFont(font)
        self.buttonStretchUpRight.setCheckable(True)
        self.buttonStretchUpRight.setObjectName("buttonStretchUpRight")
        self.gridLayout_4.addWidget(self.buttonStretchUpRight, 1, 4, 1, 1)
        self.buttonStretchW = QtWidgets.QPushButton(self.groupStretchPull)
        self.buttonStretchW.setMinimumSize(QtCore.QSize(31, 31))
        self.buttonStretchW.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.buttonStretchW.setFont(font)
        self.buttonStretchW.setCheckable(True)
        self.buttonStretchW.setObjectName("buttonStretchW")
        self.gridLayout_4.addWidget(self.buttonStretchW, 2, 1, 1, 1)
        self.buttonResetStretch = QtWidgets.QPushButton(self.groupStretchPull)
        self.buttonResetStretch.setMinimumSize(QtCore.QSize(31, 31))
        self.buttonResetStretch.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.buttonResetStretch.setFont(font)
        self.buttonResetStretch.setCheckable(True)
        self.buttonResetStretch.setObjectName("buttonResetStretch")
        self.gridLayout_4.addWidget(self.buttonResetStretch, 2, 2, 1, 1)
        self.buttonStretchE = QtWidgets.QPushButton(self.groupStretchPull)
        self.buttonStretchE.setMinimumSize(QtCore.QSize(31, 31))
        self.buttonStretchE.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.buttonStretchE.setFont(font)
        self.buttonStretchE.setCheckable(True)
        self.buttonStretchE.setObjectName("buttonStretchE")
        self.gridLayout_4.addWidget(self.buttonStretchE, 2, 3, 1, 1)
        self.buttonStretchDownLeft = QtWidgets.QPushButton(self.groupStretchPull)
        self.buttonStretchDownLeft.setMinimumSize(QtCore.QSize(31, 31))
        self.buttonStretchDownLeft.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.buttonStretchDownLeft.setFont(font)
        self.buttonStretchDownLeft.setCheckable(True)
        self.buttonStretchDownLeft.setObjectName("buttonStretchDownLeft")
        self.gridLayout_4.addWidget(self.buttonStretchDownLeft, 3, 0, 1, 1)
        self.buttonStretchSW = QtWidgets.QPushButton(self.groupStretchPull)
        self.buttonStretchSW.setMinimumSize(QtCore.QSize(31, 31))
        self.buttonStretchSW.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.buttonStretchSW.setFont(font)
        self.buttonStretchSW.setCheckable(True)
        self.buttonStretchSW.setObjectName("buttonStretchSW")
        self.gridLayout_4.addWidget(self.buttonStretchSW, 3, 1, 1, 1)
        self.buttonStretchS = QtWidgets.QPushButton(self.groupStretchPull)
        self.buttonStretchS.setMinimumSize(QtCore.QSize(31, 31))
        self.buttonStretchS.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.buttonStretchS.setFont(font)
        self.buttonStretchS.setCheckable(True)
        self.buttonStretchS.setObjectName("buttonStretchS")
        self.gridLayout_4.addWidget(self.buttonStretchS, 3, 2, 1, 1)
        self.buttonStretchSE = QtWidgets.QPushButton(self.groupStretchPull)
        self.buttonStretchSE.setMinimumSize(QtCore.QSize(31, 31))
        self.buttonStretchSE.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.buttonStretchSE.setFont(font)
        self.buttonStretchSE.setCheckable(True)
        self.buttonStretchSE.setObjectName("buttonStretchSE")
        self.gridLayout_4.addWidget(self.buttonStretchSE, 3, 3, 1, 1)
        self.buttonStretchDownRight = QtWidgets.QPushButton(self.groupStretchPull)
        self.buttonStretchDownRight.setMinimumSize(QtCore.QSize(31, 31))
        self.buttonStretchDownRight.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.buttonStretchDownRight.setFont(font)
        self.buttonStretchDownRight.setCheckable(True)
        self.buttonStretchDownRight.setObjectName("buttonStretchDownRight")
        self.gridLayout_4.addWidget(self.buttonStretchDownRight, 3, 4, 1, 1)
        self.buttonStretchLeftDown = QtWidgets.QPushButton(self.groupStretchPull)
        self.buttonStretchLeftDown.setMinimumSize(QtCore.QSize(31, 31))
        self.buttonStretchLeftDown.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.buttonStretchLeftDown.setFont(font)
        self.buttonStretchLeftDown.setCheckable(True)
        self.buttonStretchLeftDown.setObjectName("buttonStretchLeftDown")
        self.gridLayout_4.addWidget(self.buttonStretchLeftDown, 4, 1, 1, 1)
        self.buttonStretchRightDown = QtWidgets.QPushButton(self.groupStretchPull)
        self.buttonStretchRightDown.setMinimumSize(QtCore.QSize(31, 31))
        self.buttonStretchRightDown.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.buttonStretchRightDown.setFont(font)
        self.buttonStretchRightDown.setCheckable(True)
        self.buttonStretchRightDown.setObjectName("buttonStretchRightDown")
        self.gridLayout_4.addWidget(self.buttonStretchRightDown, 4, 3, 1, 1)
        self.groupGeneral = QtWidgets.QGroupBox(dialogOverlayAdjustment)
        self.groupGeneral.setGeometry(QtCore.QRect(160, 50, 101, 91))
        self.groupGeneral.setObjectName("groupGeneral")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupGeneral)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.buttonReset = QtWidgets.QPushButton(self.groupGeneral)
        self.buttonReset.setEnabled(True)
        self.buttonReset.setMinimumSize(QtCore.QSize(35, 35))
        self.buttonReset.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.buttonReset.setFont(font)
        self.buttonReset.setObjectName("buttonReset")
        self.gridLayout_5.addWidget(self.buttonReset, 0, 0, 1, 1)
        self.buttonUndo = QtWidgets.QPushButton(self.groupGeneral)
        self.buttonUndo.setMinimumSize(QtCore.QSize(35, 35))
        self.buttonUndo.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.buttonUndo.setFont(font)
        self.buttonUndo.setCheckable(True)
        self.buttonUndo.setObjectName("buttonUndo")
        self.gridLayout_5.addWidget(self.buttonUndo, 0, 1, 1, 1)

        self.retranslateUi(dialogOverlayAdjustment)
        self.buttonDone.clicked.connect(dialogOverlayAdjustment.close)
        QtCore.QMetaObject.connectSlotsByName(dialogOverlayAdjustment)
        dialogOverlayAdjustment.setTabOrder(self.buttonDone, self.spinPixels)
        dialogOverlayAdjustment.setTabOrder(self.spinPixels, self.spinDegrees)
        dialogOverlayAdjustment.setTabOrder(self.spinDegrees, self.buttonReset)
        dialogOverlayAdjustment.setTabOrder(self.buttonReset, self.buttonUndo)
        dialogOverlayAdjustment.setTabOrder(self.buttonUndo, self.buttonTranslateUp)
        dialogOverlayAdjustment.setTabOrder(self.buttonTranslateUp, self.buttonTranslateDown)
        dialogOverlayAdjustment.setTabOrder(self.buttonTranslateDown, self.buttonTranslateLeft)
        dialogOverlayAdjustment.setTabOrder(self.buttonTranslateLeft, self.buttonTranslateRight)
        dialogOverlayAdjustment.setTabOrder(self.buttonTranslateRight, self.buttonStretchLeftUp)
        dialogOverlayAdjustment.setTabOrder(self.buttonStretchLeftUp, self.buttonStretchRightUp)
        dialogOverlayAdjustment.setTabOrder(self.buttonStretchRightUp, self.buttonStretchUpLeft)
        dialogOverlayAdjustment.setTabOrder(self.buttonStretchUpLeft, self.buttonStretchNW)
        dialogOverlayAdjustment.setTabOrder(self.buttonStretchNW, self.buttonStretchN)
        dialogOverlayAdjustment.setTabOrder(self.buttonStretchN, self.buttonStretchNE)
        dialogOverlayAdjustment.setTabOrder(self.buttonStretchNE, self.buttonStretchUpRight)
        dialogOverlayAdjustment.setTabOrder(self.buttonStretchUpRight, self.buttonStretchW)
        dialogOverlayAdjustment.setTabOrder(self.buttonStretchW, self.buttonResetStretch)
        dialogOverlayAdjustment.setTabOrder(self.buttonResetStretch, self.buttonStretchE)
        dialogOverlayAdjustment.setTabOrder(self.buttonStretchE, self.buttonStretchDownLeft)
        dialogOverlayAdjustment.setTabOrder(self.buttonStretchDownLeft, self.buttonStretchSW)
        dialogOverlayAdjustment.setTabOrder(self.buttonStretchSW, self.buttonStretchSE)
        dialogOverlayAdjustment.setTabOrder(self.buttonStretchSE, self.buttonStretchS)
        dialogOverlayAdjustment.setTabOrder(self.buttonStretchS, self.buttonStretchDownRight)
        dialogOverlayAdjustment.setTabOrder(self.buttonStretchDownRight, self.buttonStretchLeftDown)
        dialogOverlayAdjustment.setTabOrder(self.buttonStretchLeftDown, self.buttonStretchRightDown)
        dialogOverlayAdjustment.setTabOrder(self.buttonStretchRightDown, self.buttonRotateACW)
        dialogOverlayAdjustment.setTabOrder(self.buttonRotateACW, self.buttonRotateCW)
        dialogOverlayAdjustment.setTabOrder(self.buttonRotateCW, self.buttonFlipHorizontal)
        dialogOverlayAdjustment.setTabOrder(self.buttonFlipHorizontal, self.buttonFlipVertical)

    def retranslateUi(self, dialogOverlayAdjustment):
        _translate = QtCore.QCoreApplication.translate
        dialogOverlayAdjustment.setWindowTitle(_translate("dialogOverlayAdjustment", "Overlay Adjustment"))
        self.labelInformation.setText(_translate("dialogOverlayAdjustment", "This tool allows the user to manipulate the overlay image using a variety of geometric transformation OpenCV tools."))
        self.buttonDone.setText(_translate("dialogOverlayAdjustment", "Done"))
        self.groupValues.setTitle(_translate("dialogOverlayAdjustment", "Values"))
        self.labelPixels.setText(_translate("dialogOverlayAdjustment", "Pixels"))
        self.labelDegrees.setText(_translate("dialogOverlayAdjustment", "Degrees"))
        self.groupTranslation.setTitle(_translate("dialogOverlayAdjustment", "Translation"))
        self.buttonTranslateUp.setToolTip(_translate("dialogOverlayAdjustment", "Shifts the display image up by the given pixels."))
        self.buttonTranslateUp.setText(_translate("dialogOverlayAdjustment", "U"))
        self.buttonTranslateDown.setToolTip(_translate("dialogOverlayAdjustment", "Shifts the display image down by the given pixels."))
        self.buttonTranslateDown.setText(_translate("dialogOverlayAdjustment", "D"))
        self.buttonTranslateLeft.setToolTip(_translate("dialogOverlayAdjustment", "Shifts the display image left by the given pixels."))
        self.buttonTranslateLeft.setText(_translate("dialogOverlayAdjustment", "L"))
        self.buttonTranslateRight.setToolTip(_translate("dialogOverlayAdjustment", "Shifts the display image right by the given pixels."))
        self.buttonTranslateRight.setText(_translate("dialogOverlayAdjustment", "R"))
        self.groupRotationFlip.setTitle(_translate("dialogOverlayAdjustment", "Rotation / Flip"))
        self.buttonRotateACW.setToolTip(_translate("dialogOverlayAdjustment", "Clocwise rotates the display image by the given degrees."))
        self.buttonRotateACW.setText(_translate("dialogOverlayAdjustment", "ACW"))
        self.buttonRotateCW.setToolTip(_translate("dialogOverlayAdjustment", "Anti-Clocwise rotates the display image by the given degrees."))
        self.buttonRotateCW.setText(_translate("dialogOverlayAdjustment", "CW"))
        self.buttonFlipHorizontal.setToolTip(_translate("dialogOverlayAdjustment", "Clocwise rotates the display image by the given degrees."))
        self.buttonFlipHorizontal.setText(_translate("dialogOverlayAdjustment", "H"))
        self.buttonFlipVertical.setToolTip(_translate("dialogOverlayAdjustment", "Clocwise rotates the display image by the given degrees."))
        self.buttonFlipVertical.setText(_translate("dialogOverlayAdjustment", "V"))
        self.groupStretchPull.setTitle(_translate("dialogOverlayAdjustment", "Stretch / Pull"))
        self.buttonStretchLeftUp.setToolTip(_translate("dialogOverlayAdjustment", "Click to move the crop boundary."))
        self.buttonStretchLeftUp.setText(_translate("dialogOverlayAdjustment", "LU"))
        self.buttonStretchRightUp.setToolTip(_translate("dialogOverlayAdjustment", "Click to move the crop boundary."))
        self.buttonStretchRightUp.setText(_translate("dialogOverlayAdjustment", "RU"))
        self.buttonStretchUpLeft.setToolTip(_translate("dialogOverlayAdjustment", "Click to move the crop boundary."))
        self.buttonStretchUpLeft.setText(_translate("dialogOverlayAdjustment", "UL"))
        self.buttonStretchNW.setToolTip(_translate("dialogOverlayAdjustment", "Click to move the crop boundary."))
        self.buttonStretchNW.setText(_translate("dialogOverlayAdjustment", "NW"))
        self.buttonStretchN.setToolTip(_translate("dialogOverlayAdjustment", "Click to move the overlay boundary."))
        self.buttonStretchN.setText(_translate("dialogOverlayAdjustment", "N"))
        self.buttonStretchNE.setToolTip(_translate("dialogOverlayAdjustment", "Click to move the crop boundary."))
        self.buttonStretchNE.setText(_translate("dialogOverlayAdjustment", "NE"))
        self.buttonStretchUpRight.setToolTip(_translate("dialogOverlayAdjustment", "Click to move the crop boundary."))
        self.buttonStretchUpRight.setText(_translate("dialogOverlayAdjustment", "UR"))
        self.buttonStretchW.setToolTip(_translate("dialogOverlayAdjustment", "Click to move the crop boundary."))
        self.buttonStretchW.setText(_translate("dialogOverlayAdjustment", "W"))
        self.buttonResetStretch.setToolTip(_translate("dialogOverlayAdjustment", "Click to move the crop boundary."))
        self.buttonResetStretch.setText(_translate("dialogOverlayAdjustment", "R"))
        self.buttonStretchE.setToolTip(_translate("dialogOverlayAdjustment", "Click to move the crop boundary."))
        self.buttonStretchE.setText(_translate("dialogOverlayAdjustment", "E"))
        self.buttonStretchDownLeft.setToolTip(_translate("dialogOverlayAdjustment", "Click to move the crop boundary."))
        self.buttonStretchDownLeft.setText(_translate("dialogOverlayAdjustment", "DL"))
        self.buttonStretchSW.setToolTip(_translate("dialogOverlayAdjustment", "Click to move the crop boundary."))
        self.buttonStretchSW.setText(_translate("dialogOverlayAdjustment", "SW"))
        self.buttonStretchS.setToolTip(_translate("dialogOverlayAdjustment", "Click to move the crop boundary."))
        self.buttonStretchS.setText(_translate("dialogOverlayAdjustment", "S"))
        self.buttonStretchSE.setToolTip(_translate("dialogOverlayAdjustment", "Click to move the crop boundary."))
        self.buttonStretchSE.setText(_translate("dialogOverlayAdjustment", "SE"))
        self.buttonStretchDownRight.setToolTip(_translate("dialogOverlayAdjustment", "Click to move the crop boundary."))
        self.buttonStretchDownRight.setText(_translate("dialogOverlayAdjustment", "DR"))
        self.buttonStretchLeftDown.setToolTip(_translate("dialogOverlayAdjustment", "Click to move the crop boundary."))
        self.buttonStretchLeftDown.setText(_translate("dialogOverlayAdjustment", "LD"))
        self.buttonStretchRightDown.setToolTip(_translate("dialogOverlayAdjustment", "Click to move the crop boundary."))
        self.buttonStretchRightDown.setText(_translate("dialogOverlayAdjustment", "RD"))
        self.groupGeneral.setTitle(_translate("dialogOverlayAdjustment", "General"))
        self.buttonReset.setToolTip(_translate("dialogOverlayAdjustment", "Resets the overlay image."))
        self.buttonReset.setText(_translate("dialogOverlayAdjustment", "R"))
        self.buttonUndo.setToolTip(_translate("dialogOverlayAdjustment", "Click to move the crop boundary."))
        self.buttonUndo.setText(_translate("dialogOverlayAdjustment", "U"))

