# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialogImageCapture.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_dialogImageCapture(object):
    def setupUi(self, dialogImageCapture):
        dialogImageCapture.setObjectName(_fromUtf8("dialogImageCapture"))
        dialogImageCapture.resize(491, 308)
        dialogImageCapture.setMinimumSize(QtCore.QSize(491, 308))
        dialogImageCapture.setMaximumSize(QtCore.QSize(491, 308))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/resources/logo.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        dialogImageCapture.setWindowIcon(icon)
        self.labelCameraStatus = QtGui.QLabel(dialogImageCapture)
        self.labelCameraStatus.setGeometry(QtCore.QRect(330, 134, 151, 28))
        self.labelCameraStatus.setFrameShape(QtGui.QFrame.Panel)
        self.labelCameraStatus.setFrameShadow(QtGui.QFrame.Sunken)
        self.labelCameraStatus.setLineWidth(2)
        self.labelCameraStatus.setMidLineWidth(0)
        self.labelCameraStatus.setText(_fromUtf8(""))
        self.labelCameraStatus.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCameraStatus.setObjectName(_fromUtf8("labelCameraStatus"))
        self.buttonCheckCamera = QtGui.QPushButton(dialogImageCapture)
        self.buttonCheckCamera.setGeometry(QtCore.QRect(170, 134, 151, 28))
        self.buttonCheckCamera.setObjectName(_fromUtf8("buttonCheckCamera"))
        self.buttonCameraSettings = QtGui.QPushButton(dialogImageCapture)
        self.buttonCameraSettings.setGeometry(QtCore.QRect(10, 134, 151, 28))
        self.buttonCameraSettings.setObjectName(_fromUtf8("buttonCameraSettings"))
        self.buttonBrowse = QtGui.QPushButton(dialogImageCapture)
        self.buttonBrowse.setGeometry(QtCore.QRect(330, 99, 151, 28))
        self.buttonBrowse.setObjectName(_fromUtf8("buttonBrowse"))
        self.labelSaveLocation = QtGui.QLabel(dialogImageCapture)
        self.labelSaveLocation.setGeometry(QtCore.QRect(10, 76, 141, 21))
        self.labelSaveLocation.setObjectName(_fromUtf8("labelSaveLocation"))
        self.labelInformation = QtGui.QLabel(dialogImageCapture)
        self.labelInformation.setGeometry(QtCore.QRect(10, 5, 471, 71))
        self.labelInformation.setWordWrap(True)
        self.labelInformation.setObjectName(_fromUtf8("labelInformation"))
        self.buttonDone = QtGui.QPushButton(dialogImageCapture)
        self.buttonDone.setGeometry(QtCore.QRect(330, 270, 151, 28))
        self.buttonDone.setObjectName(_fromUtf8("buttonDone"))
        self.buttonCapture = QtGui.QPushButton(dialogImageCapture)
        self.buttonCapture.setEnabled(False)
        self.buttonCapture.setGeometry(QtCore.QRect(10, 168, 151, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.buttonCapture.setFont(font)
        self.buttonCapture.setObjectName(_fromUtf8("buttonCapture"))
        self.buttonRun = QtGui.QPushButton(dialogImageCapture)
        self.buttonRun.setEnabled(False)
        self.buttonRun.setGeometry(QtCore.QRect(170, 202, 151, 28))
        self.buttonRun.setObjectName(_fromUtf8("buttonRun"))
        self.buttonStop = QtGui.QPushButton(dialogImageCapture)
        self.buttonStop.setEnabled(False)
        self.buttonStop.setGeometry(QtCore.QRect(330, 202, 151, 28))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.buttonStop.setPalette(palette)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.buttonStop.setFont(font)
        self.buttonStop.setObjectName(_fromUtf8("buttonStop"))
        self.labelTimeElapsed = QtGui.QLabel(dialogImageCapture)
        self.labelTimeElapsed.setGeometry(QtCore.QRect(330, 236, 151, 28))
        self.labelTimeElapsed.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTimeElapsed.setObjectName(_fromUtf8("labelTimeElapsed"))
        self.labelStatusBar = QtGui.QLabel(dialogImageCapture)
        self.labelStatusBar.setGeometry(QtCore.QRect(10, 270, 321, 28))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.labelStatusBar.setFont(font)
        self.labelStatusBar.setObjectName(_fromUtf8("labelStatusBar"))
        self.labelTriggerStatus = QtGui.QLabel(dialogImageCapture)
        self.labelTriggerStatus.setGeometry(QtCore.QRect(330, 168, 151, 28))
        self.labelTriggerStatus.setFrameShape(QtGui.QFrame.Panel)
        self.labelTriggerStatus.setFrameShadow(QtGui.QFrame.Sunken)
        self.labelTriggerStatus.setLineWidth(2)
        self.labelTriggerStatus.setMidLineWidth(0)
        self.labelTriggerStatus.setText(_fromUtf8(""))
        self.labelTriggerStatus.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTriggerStatus.setObjectName(_fromUtf8("labelTriggerStatus"))
        self.buttonCheckTrigger = QtGui.QPushButton(dialogImageCapture)
        self.buttonCheckTrigger.setGeometry(QtCore.QRect(170, 168, 151, 28))
        self.buttonCheckTrigger.setObjectName(_fromUtf8("buttonCheckTrigger"))
        self.lineImageFolder = QtGui.QLineEdit(dialogImageCapture)
        self.lineImageFolder.setGeometry(QtCore.QRect(10, 100, 311, 26))
        self.lineImageFolder.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineImageFolder.setReadOnly(True)
        self.lineImageFolder.setObjectName(_fromUtf8("lineImageFolder"))
        self.labelTimeIdle = QtGui.QLabel(dialogImageCapture)
        self.labelTimeIdle.setGeometry(QtCore.QRect(170, 236, 151, 28))
        self.labelTimeIdle.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTimeIdle.setObjectName(_fromUtf8("labelTimeIdle"))
        self.spinStartingLayer = QtGui.QSpinBox(dialogImageCapture)
        self.spinStartingLayer.setEnabled(False)
        self.spinStartingLayer.setGeometry(QtCore.QRect(123, 239, 38, 22))
        self.spinStartingLayer.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.spinStartingLayer.setMinimum(1)
        self.spinStartingLayer.setMaximum(9999)
        self.spinStartingLayer.setObjectName(_fromUtf8("spinStartingLayer"))
        self.checkContinue = QtGui.QCheckBox(dialogImageCapture)
        self.checkContinue.setGeometry(QtCore.QRect(10, 236, 111, 28))
        self.checkContinue.setObjectName(_fromUtf8("checkContinue"))

        self.retranslateUi(dialogImageCapture)
        QtCore.QObject.connect(self.buttonDone, QtCore.SIGNAL(_fromUtf8("clicked()")), dialogImageCapture.close)
        QtCore.QObject.connect(self.checkContinue, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.spinStartingLayer.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(dialogImageCapture)
        dialogImageCapture.setTabOrder(self.buttonCheckCamera, self.buttonCheckTrigger)
        dialogImageCapture.setTabOrder(self.buttonCheckTrigger, self.buttonCapture)
        dialogImageCapture.setTabOrder(self.buttonCapture, self.buttonRun)
        dialogImageCapture.setTabOrder(self.buttonRun, self.buttonStop)
        dialogImageCapture.setTabOrder(self.buttonStop, self.checkContinue)
        dialogImageCapture.setTabOrder(self.checkContinue, self.spinStartingLayer)
        dialogImageCapture.setTabOrder(self.spinStartingLayer, self.buttonDone)
        dialogImageCapture.setTabOrder(self.buttonDone, self.buttonBrowse)
        dialogImageCapture.setTabOrder(self.buttonBrowse, self.buttonCameraSettings)

    def retranslateUi(self, dialogImageCapture):
        dialogImageCapture.setWindowTitle(_translate("dialogImageCapture", "Image Capture", None))
        self.buttonCheckCamera.setText(_translate("dialogImageCapture", "Check Camera", None))
        self.buttonCameraSettings.setText(_translate("dialogImageCapture", "Camera Settings", None))
        self.buttonBrowse.setText(_translate("dialogImageCapture", "Browse", None))
        self.labelSaveLocation.setText(_translate("dialogImageCapture", "Image Save Location", None))
        self.labelInformation.setText(_translate("dialogImageCapture", "This tool allows the user to change camera settings and take images from the camera which are saved to the given location. To Capture individual images, please select a save location and check for an available camera. To Run using the hardware trigger, please also check for an available triggering device.", None))
        self.buttonDone.setText(_translate("dialogImageCapture", "Done", None))
        self.buttonCapture.setText(_translate("dialogImageCapture", "Capture", None))
        self.buttonRun.setText(_translate("dialogImageCapture", "Run", None))
        self.buttonStop.setText(_translate("dialogImageCapture", "Stop", None))
        self.labelTimeElapsed.setText(_translate("dialogImageCapture", "Time Elapsed: 00:00:00", None))
        self.labelStatusBar.setText(_translate("dialogImageCapture", "Status:", None))
        self.buttonCheckTrigger.setText(_translate("dialogImageCapture", "Check Trigger", None))
        self.labelTimeIdle.setText(_translate("dialogImageCapture", "Time Idle: 00:00:00", None))
        self.checkContinue.setToolTip(_translate("dialogImageCapture", "Check this box to continue layer number labelling from the entered number.", None))
        self.checkContinue.setText(_translate("dialogImageCapture", "Continue From", None))

import icons_rc
