# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui\dialogSliceConverter.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_dialogSliceConverter(object):
    def setupUi(self, dialogSliceConverter):
        dialogSliceConverter.setObjectName("dialogSliceConverter")
        dialogSliceConverter.resize(925, 789)
        self.gridLayout = QtWidgets.QGridLayout(dialogSliceConverter)
        self.gridLayout.setObjectName("gridLayout")
        self.groupTranslation = QtWidgets.QGroupBox(dialogSliceConverter)
        self.groupTranslation.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupTranslation.sizePolicy().hasHeightForWidth())
        self.groupTranslation.setSizePolicy(sizePolicy)
        self.groupTranslation.setObjectName("groupTranslation")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupTranslation)
        self.gridLayout_3.setContentsMargins(-1, 0, -1, 6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.labelY = QtWidgets.QLabel(self.groupTranslation)
        self.labelY.setAlignment(QtCore.Qt.AlignCenter)
        self.labelY.setObjectName("labelY")
        self.gridLayout_3.addWidget(self.labelY, 0, 2, 1, 1)
        self.labelUnits = QtWidgets.QLabel(self.groupTranslation)
        self.labelUnits.setObjectName("labelUnits")
        self.gridLayout_3.addWidget(self.labelUnits, 1, 3, 1, 1)
        self.pushResetT = QtWidgets.QPushButton(self.groupTranslation)
        self.pushResetT.setObjectName("pushResetT")
        self.gridLayout_3.addWidget(self.pushResetT, 3, 0, 1, 4)
        self.pushTranslate = QtWidgets.QPushButton(self.groupTranslation)
        self.pushTranslate.setObjectName("pushTranslate")
        self.gridLayout_3.addWidget(self.pushTranslate, 2, 0, 1, 4)
        self.spinY = QtWidgets.QSpinBox(self.groupTranslation)
        self.spinY.setMinimum(-2410)
        self.spinY.setMaximum(2410)
        self.spinY.setObjectName("spinY")
        self.gridLayout_3.addWidget(self.spinY, 1, 2, 1, 1)
        self.labelX = QtWidgets.QLabel(self.groupTranslation)
        self.labelX.setAlignment(QtCore.Qt.AlignCenter)
        self.labelX.setObjectName("labelX")
        self.gridLayout_3.addWidget(self.labelX, 0, 1, 1, 1)
        self.spinX = QtWidgets.QSpinBox(self.groupTranslation)
        self.spinX.setMinimum(-3470)
        self.spinX.setMaximum(3470)
        self.spinX.setObjectName("spinX")
        self.gridLayout_3.addWidget(self.spinX, 1, 1, 1, 1)
        self.gridLayout.addWidget(self.groupTranslation, 8, 7, 2, 1)
        self.groupStatus = QtWidgets.QGroupBox(dialogSliceConverter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupStatus.sizePolicy().hasHeightForWidth())
        self.groupStatus.setSizePolicy(sizePolicy)
        self.groupStatus.setObjectName("groupStatus")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupStatus)
        self.verticalLayout_4.setContentsMargins(-1, 6, -1, 6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.labelCurrentPart = QtWidgets.QLabel(self.groupStatus)
        self.labelCurrentPart.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCurrentPart.setObjectName("labelCurrentPart")
        self.verticalLayout_4.addWidget(self.labelCurrentPart)
        self.labelStatusPart = QtWidgets.QLabel(self.groupStatus)
        self.labelStatusPart.setAlignment(QtCore.Qt.AlignCenter)
        self.labelStatusPart.setObjectName("labelStatusPart")
        self.verticalLayout_4.addWidget(self.labelStatusPart)
        self.labelStatus = QtWidgets.QLabel(self.groupStatus)
        self.labelStatus.setAlignment(QtCore.Qt.AlignCenter)
        self.labelStatus.setObjectName("labelStatus")
        self.verticalLayout_4.addWidget(self.labelStatus)
        self.progressBar = QtWidgets.QProgressBar(self.groupStatus)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setTextVisible(True)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_4.addWidget(self.progressBar)
        self.pushPause = QtWidgets.QPushButton(self.groupStatus)
        self.pushPause.setEnabled(False)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushPause.setFont(font)
        self.pushPause.setObjectName("pushPause")
        self.verticalLayout_4.addWidget(self.pushPause)
        self.gridLayout.addWidget(self.groupStatus, 8, 9, 2, 4)
        self.frameOutputFolder = QtWidgets.QFrame(dialogSliceConverter)
        self.frameOutputFolder.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameOutputFolder.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameOutputFolder.setObjectName("frameOutputFolder")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frameOutputFolder)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labelOutputFolder = QtWidgets.QLabel(self.frameOutputFolder)
        self.labelOutputFolder.setObjectName("labelOutputFolder")
        self.horizontalLayout_2.addWidget(self.labelOutputFolder)
        self.lineOutputFolder = QtWidgets.QLineEdit(self.frameOutputFolder)
        self.lineOutputFolder.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineOutputFolder.setReadOnly(True)
        self.lineOutputFolder.setObjectName("lineOutputFolder")
        self.horizontalLayout_2.addWidget(self.lineOutputFolder)
        self.pushBrowseOF = QtWidgets.QPushButton(self.frameOutputFolder)
        self.pushBrowseOF.setObjectName("pushBrowseOF")
        self.horizontalLayout_2.addWidget(self.pushBrowseOF)
        self.gridLayout.addWidget(self.frameOutputFolder, 13, 0, 1, 10)
        self.frameSliceFiles = QtWidgets.QFrame(dialogSliceConverter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameSliceFiles.sizePolicy().hasHeightForWidth())
        self.frameSliceFiles.setSizePolicy(sizePolicy)
        self.frameSliceFiles.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameSliceFiles.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameSliceFiles.setObjectName("frameSliceFiles")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frameSliceFiles)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.listSliceFiles = QtWidgets.QListWidget(self.frameSliceFiles)
        self.listSliceFiles.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.listSliceFiles.setObjectName("listSliceFiles")
        self.verticalLayout_3.addWidget(self.listSliceFiles)
        self.pushAddSF = QtWidgets.QPushButton(self.frameSliceFiles)
        self.pushAddSF.setObjectName("pushAddSF")
        self.verticalLayout_3.addWidget(self.pushAddSF)
        self.pushRemoveSF = QtWidgets.QPushButton(self.frameSliceFiles)
        self.pushRemoveSF.setObjectName("pushRemoveSF")
        self.verticalLayout_3.addWidget(self.pushRemoveSF)
        self.pushDrawContours = QtWidgets.QPushButton(self.frameSliceFiles)
        self.pushDrawContours.setEnabled(False)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushDrawContours.setFont(font)
        self.pushDrawContours.setObjectName("pushDrawContours")
        self.verticalLayout_3.addWidget(self.pushDrawContours)
        self.gridLayout.addWidget(self.frameSliceFiles, 1, 0, 6, 3)
        self.groupRotation = QtWidgets.QGroupBox(dialogSliceConverter)
        self.groupRotation.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupRotation.sizePolicy().hasHeightForWidth())
        self.groupRotation.setSizePolicy(sizePolicy)
        self.groupRotation.setObjectName("groupRotation")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupRotation)
        self.gridLayout_4.setContentsMargins(-1, 0, -1, 6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.pushRotate = QtWidgets.QPushButton(self.groupRotation)
        self.pushRotate.setObjectName("pushRotate")
        self.gridLayout_4.addWidget(self.pushRotate, 2, 0, 1, 3)
        self.pushResetR = QtWidgets.QPushButton(self.groupRotation)
        self.pushResetR.setObjectName("pushResetR")
        self.gridLayout_4.addWidget(self.pushResetR, 3, 0, 1, 3)
        self.spinAngle = QtWidgets.QSpinBox(self.groupRotation)
        self.spinAngle.setMinimum(-360)
        self.spinAngle.setMaximum(360)
        self.spinAngle.setObjectName("spinAngle")
        self.gridLayout_4.addWidget(self.spinAngle, 1, 1, 1, 1)
        self.labelDegree = QtWidgets.QLabel(self.groupRotation)
        self.labelDegree.setAlignment(QtCore.Qt.AlignCenter)
        self.labelDegree.setObjectName("labelDegree")
        self.gridLayout_4.addWidget(self.labelDegree, 1, 2, 1, 1)
        self.labelAngle = QtWidgets.QLabel(self.groupRotation)
        self.labelAngle.setAlignment(QtCore.Qt.AlignCenter)
        self.labelAngle.setObjectName("labelAngle")
        self.gridLayout_4.addWidget(self.labelAngle, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.groupRotation, 8, 6, 2, 1)
        self.groupDisplayOptions = QtWidgets.QGroupBox(dialogSliceConverter)
        self.groupDisplayOptions.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupDisplayOptions.sizePolicy().hasHeightForWidth())
        self.groupDisplayOptions.setSizePolicy(sizePolicy)
        self.groupDisplayOptions.setObjectName("groupDisplayOptions")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupDisplayOptions)
        self.verticalLayout_2.setContentsMargins(-1, 6, -1, 6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.checkCentrelines = QtWidgets.QCheckBox(self.groupDisplayOptions)
        self.checkCentrelines.setObjectName("checkCentrelines")
        self.verticalLayout_2.addWidget(self.checkCentrelines)
        self.checkFillContours = QtWidgets.QCheckBox(self.groupDisplayOptions)
        self.checkFillContours.setObjectName("checkFillContours")
        self.verticalLayout_2.addWidget(self.checkFillContours)
        self.checkBackground = QtWidgets.QCheckBox(self.groupDisplayOptions)
        self.checkBackground.setObjectName("checkBackground")
        self.verticalLayout_2.addWidget(self.checkBackground)
        self.lineBackground = QtWidgets.QLineEdit(self.groupDisplayOptions)
        self.lineBackground.setEnabled(False)
        self.lineBackground.setReadOnly(True)
        self.lineBackground.setObjectName("lineBackground")
        self.verticalLayout_2.addWidget(self.lineBackground)
        self.pushBrowseCB = QtWidgets.QPushButton(self.groupDisplayOptions)
        self.pushBrowseCB.setEnabled(False)
        self.pushBrowseCB.setObjectName("pushBrowseCB")
        self.verticalLayout_2.addWidget(self.pushBrowseCB)
        self.gridLayout.addWidget(self.groupDisplayOptions, 8, 0, 2, 3)
        self.label = QtWidgets.QLabel(dialogSliceConverter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 10, 0, 1, 13)
        self.buttonDone = QtWidgets.QPushButton(dialogSliceConverter)
        self.buttonDone.setObjectName("buttonDone")
        self.gridLayout.addWidget(self.buttonDone, 13, 10, 1, 3)
        self.groupMousePosition = QtWidgets.QGroupBox(dialogSliceConverter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupMousePosition.sizePolicy().hasHeightForWidth())
        self.groupMousePosition.setSizePolicy(sizePolicy)
        self.groupMousePosition.setObjectName("groupMousePosition")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupMousePosition)
        self.verticalLayout.setContentsMargins(-1, 6, -1, 6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelXPosition = QtWidgets.QLabel(self.groupMousePosition)
        self.labelXPosition.setAlignment(QtCore.Qt.AlignCenter)
        self.labelXPosition.setObjectName("labelXPosition")
        self.verticalLayout.addWidget(self.labelXPosition)
        self.labelYPosition = QtWidgets.QLabel(self.groupMousePosition)
        self.labelYPosition.setAlignment(QtCore.Qt.AlignCenter)
        self.labelYPosition.setObjectName("labelYPosition")
        self.verticalLayout.addWidget(self.labelYPosition)
        self.gridLayout.addWidget(self.groupMousePosition, 8, 3, 1, 1)
        self.groupDrawRange = QtWidgets.QGroupBox(dialogSliceConverter)
        self.groupDrawRange.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupDrawRange.sizePolicy().hasHeightForWidth())
        self.groupDrawRange.setSizePolicy(sizePolicy)
        self.groupDrawRange.setObjectName("groupDrawRange")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupDrawRange)
        self.verticalLayout_5.setContentsMargins(-1, 6, -1, 6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.spinRangeLow = QtWidgets.QSpinBox(self.groupDrawRange)
        self.spinRangeLow.setMinimum(1)
        self.spinRangeLow.setMaximum(9999)
        self.spinRangeLow.setObjectName("spinRangeLow")
        self.verticalLayout_5.addWidget(self.spinRangeLow)
        self.spinRangeHigh = QtWidgets.QSpinBox(self.groupDrawRange)
        self.spinRangeHigh.setMinimum(1)
        self.spinRangeHigh.setMaximum(9999)
        self.spinRangeHigh.setObjectName("spinRangeHigh")
        self.verticalLayout_5.addWidget(self.spinRangeHigh)
        self.gridLayout.addWidget(self.groupDrawRange, 9, 3, 1, 1)
        self.tableTransform = QtWidgets.QTableWidget(dialogSliceConverter)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tableTransform.setFont(font)
        self.tableTransform.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tableTransform.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableTransform.setObjectName("tableTransform")
        self.tableTransform.setColumnCount(4)
        self.tableTransform.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableTransform.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableTransform.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableTransform.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableTransform.setHorizontalHeaderItem(3, item)
        self.gridLayout.addWidget(self.tableTransform, 8, 8, 2, 1)
        self.frameDisplay = QtWidgets.QFrame(dialogSliceConverter)
        self.frameDisplay.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameDisplay.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameDisplay.setObjectName("frameDisplay")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frameDisplay)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.graphicsDisplay = ImageViewer(self.frameDisplay)
        self.graphicsDisplay.setMinimumSize(QtCore.QSize(746, 518))
        self.graphicsDisplay.setMouseTracking(True)
        self.graphicsDisplay.setObjectName("graphicsDisplay")
        self.gridLayout_2.addWidget(self.graphicsDisplay, 0, 0, 1, 1)
        self.frameDisplayControl = QtWidgets.QFrame(self.frameDisplay)
        self.frameDisplayControl.setEnabled(False)
        self.frameDisplayControl.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameDisplayControl.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameDisplayControl.setObjectName("frameDisplayControl")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frameDisplayControl)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushZoomIn = QtWidgets.QPushButton(self.frameDisplayControl)
        self.pushZoomIn.setCheckable(True)
        self.pushZoomIn.setObjectName("pushZoomIn")
        self.horizontalLayout.addWidget(self.pushZoomIn)
        self.pushZoomOut = QtWidgets.QPushButton(self.frameDisplayControl)
        self.pushZoomOut.setObjectName("pushZoomOut")
        self.horizontalLayout.addWidget(self.pushZoomOut)
        self.labelSliceHeightTitle = QtWidgets.QLabel(self.frameDisplayControl)
        self.labelSliceHeightTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.labelSliceHeightTitle.setObjectName("labelSliceHeightTitle")
        self.horizontalLayout.addWidget(self.labelSliceHeightTitle)
        self.labelSliceHeight = QtWidgets.QLabel(self.frameDisplayControl)
        self.labelSliceHeight.setObjectName("labelSliceHeight")
        self.horizontalLayout.addWidget(self.labelSliceHeight)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.labelSliceNumberTitle = QtWidgets.QLabel(self.frameDisplayControl)
        self.labelSliceNumberTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.labelSliceNumberTitle.setObjectName("labelSliceNumberTitle")
        self.horizontalLayout.addWidget(self.labelSliceNumberTitle)
        self.labelSliceNumber = QtWidgets.QLabel(self.frameDisplayControl)
        self.labelSliceNumber.setAlignment(QtCore.Qt.AlignCenter)
        self.labelSliceNumber.setObjectName("labelSliceNumber")
        self.horizontalLayout.addWidget(self.labelSliceNumber)
        self.spinSliceNumber = QtWidgets.QSpinBox(self.frameDisplayControl)
        self.spinSliceNumber.setMinimum(1)
        self.spinSliceNumber.setMaximum(9999)
        self.spinSliceNumber.setObjectName("spinSliceNumber")
        self.horizontalLayout.addWidget(self.spinSliceNumber)
        self.pushGo = QtWidgets.QPushButton(self.frameDisplayControl)
        self.pushGo.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushGo.setObjectName("pushGo")
        self.horizontalLayout.addWidget(self.pushGo)
        self.gridLayout_2.addWidget(self.frameDisplayControl, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.frameDisplay, 1, 3, 6, 10)
        self.label_2 = QtWidgets.QLabel(dialogSliceConverter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 11, 0, 1, 13)

        self.retranslateUi(dialogSliceConverter)
        self.buttonDone.clicked.connect(dialogSliceConverter.close)
        self.checkBackground.toggled['bool'].connect(self.lineBackground.setEnabled)
        self.checkBackground.toggled['bool'].connect(self.pushBrowseCB.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(dialogSliceConverter)
        dialogSliceConverter.setTabOrder(self.listSliceFiles, self.graphicsDisplay)
        dialogSliceConverter.setTabOrder(self.graphicsDisplay, self.pushAddSF)
        dialogSliceConverter.setTabOrder(self.pushAddSF, self.pushRemoveSF)
        dialogSliceConverter.setTabOrder(self.pushRemoveSF, self.pushDrawContours)
        dialogSliceConverter.setTabOrder(self.pushDrawContours, self.checkCentrelines)
        dialogSliceConverter.setTabOrder(self.checkCentrelines, self.checkFillContours)
        dialogSliceConverter.setTabOrder(self.checkFillContours, self.checkBackground)
        dialogSliceConverter.setTabOrder(self.checkBackground, self.lineBackground)
        dialogSliceConverter.setTabOrder(self.lineBackground, self.pushBrowseCB)
        dialogSliceConverter.setTabOrder(self.pushBrowseCB, self.pushZoomIn)
        dialogSliceConverter.setTabOrder(self.pushZoomIn, self.pushZoomOut)
        dialogSliceConverter.setTabOrder(self.pushZoomOut, self.spinSliceNumber)
        dialogSliceConverter.setTabOrder(self.spinSliceNumber, self.pushGo)
        dialogSliceConverter.setTabOrder(self.pushGo, self.spinRangeLow)
        dialogSliceConverter.setTabOrder(self.spinRangeLow, self.spinRangeHigh)
        dialogSliceConverter.setTabOrder(self.spinRangeHigh, self.spinAngle)
        dialogSliceConverter.setTabOrder(self.spinAngle, self.pushRotate)
        dialogSliceConverter.setTabOrder(self.pushRotate, self.pushResetR)
        dialogSliceConverter.setTabOrder(self.pushResetR, self.spinX)
        dialogSliceConverter.setTabOrder(self.spinX, self.spinY)
        dialogSliceConverter.setTabOrder(self.spinY, self.pushTranslate)
        dialogSliceConverter.setTabOrder(self.pushTranslate, self.pushResetT)
        dialogSliceConverter.setTabOrder(self.pushResetT, self.pushPause)
        dialogSliceConverter.setTabOrder(self.pushPause, self.pushBrowseOF)
        dialogSliceConverter.setTabOrder(self.pushBrowseOF, self.buttonDone)

    def retranslateUi(self, dialogSliceConverter):
        _translate = QtCore.QCoreApplication.translate
        dialogSliceConverter.setWindowTitle(_translate("dialogSliceConverter", "Slice Converter"))
        self.groupTranslation.setTitle(_translate("dialogSliceConverter", "Translation"))
        self.labelY.setText(_translate("dialogSliceConverter", "Y"))
        self.labelUnits.setText(_translate("dialogSliceConverter", "px"))
        self.pushResetT.setText(_translate("dialogSliceConverter", "Reset"))
        self.pushTranslate.setText(_translate("dialogSliceConverter", "Translate"))
        self.spinY.setToolTip(_translate("dialogSliceConverter", "-2410 - 2410"))
        self.labelX.setText(_translate("dialogSliceConverter", "X"))
        self.spinX.setToolTip(_translate("dialogSliceConverter", "-3470 - 3470"))
        self.groupStatus.setTitle(_translate("dialogSliceConverter", "Status"))
        self.labelCurrentPart.setText(_translate("dialogSliceConverter", "Current Part"))
        self.labelStatusPart.setText(_translate("dialogSliceConverter", "None"))
        self.labelStatus.setText(_translate("dialogSliceConverter", "Add slice files."))
        self.pushPause.setText(_translate("dialogSliceConverter", "Pause"))
        self.labelOutputFolder.setText(_translate("dialogSliceConverter", "Output Folder"))
        self.pushBrowseOF.setText(_translate("dialogSliceConverter", "Browse..."))
        self.pushAddSF.setText(_translate("dialogSliceConverter", "Add Slice Files..."))
        self.pushRemoveSF.setText(_translate("dialogSliceConverter", "Remove Selected Files"))
        self.pushDrawContours.setText(_translate("dialogSliceConverter", "Draw Contours"))
        self.groupRotation.setTitle(_translate("dialogSliceConverter", "Rotation"))
        self.pushRotate.setText(_translate("dialogSliceConverter", "Rotate"))
        self.pushResetR.setText(_translate("dialogSliceConverter", "Reset"))
        self.spinAngle.setToolTip(_translate("dialogSliceConverter", "-360 - 360"))
        self.labelDegree.setText(_translate("dialogSliceConverter", "°"))
        self.labelAngle.setText(_translate("dialogSliceConverter", "Angle"))
        self.groupDisplayOptions.setTitle(_translate("dialogSliceConverter", "Display Options"))
        self.checkCentrelines.setText(_translate("dialogSliceConverter", "Centrelines"))
        self.checkFillContours.setText(_translate("dialogSliceConverter", "Fill Contours"))
        self.checkBackground.setText(_translate("dialogSliceConverter", "Custom Background"))
        self.pushBrowseCB.setText(_translate("dialogSliceConverter", "Browse..."))
        self.label.setText(_translate("dialogSliceConverter", "Adding or removing slice files and clicking Draw Contours with the Output Folder set to the active build\'s folder will add or remove their respective reports."))
        self.buttonDone.setText(_translate("dialogSliceConverter", "Done"))
        self.groupMousePosition.setTitle(_translate("dialogSliceConverter", "Mouse Position"))
        self.labelXPosition.setText(_translate("dialogSliceConverter", "X     0000 px"))
        self.labelYPosition.setText(_translate("dialogSliceConverter", "Y     0000 px"))
        self.groupDrawRange.setTitle(_translate("dialogSliceConverter", "Draw Range"))
        item = self.tableTransform.horizontalHeaderItem(0)
        item.setText(_translate("dialogSliceConverter", "Part"))
        item = self.tableTransform.horizontalHeaderItem(1)
        item.setText(_translate("dialogSliceConverter", "X"))
        item = self.tableTransform.horizontalHeaderItem(2)
        item.setText(_translate("dialogSliceConverter", "Y"))
        item = self.tableTransform.horizontalHeaderItem(3)
        item.setText(_translate("dialogSliceConverter", "Angle"))
        self.pushZoomIn.setText(_translate("dialogSliceConverter", "Zoom In"))
        self.pushZoomOut.setText(_translate("dialogSliceConverter", "Zoom Out"))
        self.labelSliceHeightTitle.setText(_translate("dialogSliceConverter", "Height (mm)"))
        self.labelSliceHeight.setText(_translate("dialogSliceConverter", "00.000"))
        self.labelSliceNumberTitle.setText(_translate("dialogSliceConverter", "Slice Number"))
        self.labelSliceNumber.setText(_translate("dialogSliceConverter", "0001 / 0001"))
        self.pushGo.setText(_translate("dialogSliceConverter", "Go"))
        self.label_2.setText(_translate("dialogSliceConverter", "The Defect Detector will need to be rerun for any new slices."))

from ui_elements import ImageViewer
