# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui\dialogSliceConverter.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_dialogSliceConverter(object):
    def setupUi(self, dialogSliceConverter):
        dialogSliceConverter.setObjectName("dialogSliceConverter")
        dialogSliceConverter.resize(1102, 574)
        self.gridLayout = QtWidgets.QGridLayout(dialogSliceConverter)
        self.gridLayout.setObjectName("gridLayout")
        self.groupStatus = QtWidgets.QGroupBox(dialogSliceConverter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupStatus.sizePolicy().hasHeightForWidth())
        self.groupStatus.setSizePolicy(sizePolicy)
        self.groupStatus.setObjectName("groupStatus")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupStatus)
        self.verticalLayout_4.setContentsMargins(-1, 6, -1, 6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.labelCurrentPart = QtWidgets.QLabel(self.groupStatus)
        self.labelCurrentPart.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCurrentPart.setObjectName("labelCurrentPart")
        self.verticalLayout_4.addWidget(self.labelCurrentPart)
        self.labelStatusPart = QtWidgets.QLabel(self.groupStatus)
        self.labelStatusPart.setAlignment(QtCore.Qt.AlignCenter)
        self.labelStatusPart.setObjectName("labelStatusPart")
        self.verticalLayout_4.addWidget(self.labelStatusPart)
        self.labelStatus = QtWidgets.QLabel(self.groupStatus)
        self.labelStatus.setAlignment(QtCore.Qt.AlignCenter)
        self.labelStatus.setObjectName("labelStatus")
        self.verticalLayout_4.addWidget(self.labelStatus)
        self.progressBar = QtWidgets.QProgressBar(self.groupStatus)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setTextVisible(True)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_4.addWidget(self.progressBar)
        self.pushPause = QtWidgets.QPushButton(self.groupStatus)
        self.pushPause.setEnabled(False)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushPause.setFont(font)
        self.pushPause.setObjectName("pushPause")
        self.verticalLayout_4.addWidget(self.pushPause)
        self.gridLayout.addWidget(self.groupStatus, 7, 7, 2, 1)
        self.frameSidebar = QtWidgets.QFrame(dialogSliceConverter)
        self.frameSidebar.setMaximumSize(QtCore.QSize(140, 16777215))
        self.frameSidebar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameSidebar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameSidebar.setObjectName("frameSidebar")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frameSidebar)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.listSliceFiles = QtWidgets.QListWidget(self.frameSidebar)
        self.listSliceFiles.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.listSliceFiles.setObjectName("listSliceFiles")
        self.verticalLayout_3.addWidget(self.listSliceFiles)
        self.pushAddSF = QtWidgets.QPushButton(self.frameSidebar)
        self.pushAddSF.setObjectName("pushAddSF")
        self.verticalLayout_3.addWidget(self.pushAddSF)
        self.pushRemoveSF = QtWidgets.QPushButton(self.frameSidebar)
        self.pushRemoveSF.setObjectName("pushRemoveSF")
        self.verticalLayout_3.addWidget(self.pushRemoveSF)
        self.pushDrawContours = QtWidgets.QPushButton(self.frameSidebar)
        self.pushDrawContours.setEnabled(False)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushDrawContours.setFont(font)
        self.pushDrawContours.setObjectName("pushDrawContours")
        self.verticalLayout_3.addWidget(self.pushDrawContours)
        self.groupDisplayOptions = QtWidgets.QGroupBox(self.frameSidebar)
        self.groupDisplayOptions.setEnabled(False)
        self.groupDisplayOptions.setObjectName("groupDisplayOptions")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupDisplayOptions)
        self.verticalLayout_2.setContentsMargins(-1, 6, -1, 6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.checkCentrelines = QtWidgets.QCheckBox(self.groupDisplayOptions)
        self.checkCentrelines.setObjectName("checkCentrelines")
        self.verticalLayout_2.addWidget(self.checkCentrelines)
        self.checkFillContours = QtWidgets.QCheckBox(self.groupDisplayOptions)
        self.checkFillContours.setObjectName("checkFillContours")
        self.verticalLayout_2.addWidget(self.checkFillContours)
        self.checkBackground = QtWidgets.QCheckBox(self.groupDisplayOptions)
        self.checkBackground.setObjectName("checkBackground")
        self.verticalLayout_2.addWidget(self.checkBackground)
        self.lineBackground = QtWidgets.QLineEdit(self.groupDisplayOptions)
        self.lineBackground.setEnabled(False)
        self.lineBackground.setReadOnly(True)
        self.lineBackground.setObjectName("lineBackground")
        self.verticalLayout_2.addWidget(self.lineBackground)
        self.pushBrowseCB = QtWidgets.QPushButton(self.groupDisplayOptions)
        self.pushBrowseCB.setEnabled(False)
        self.pushBrowseCB.setObjectName("pushBrowseCB")
        self.verticalLayout_2.addWidget(self.pushBrowseCB)
        self.verticalLayout_3.addWidget(self.groupDisplayOptions)
        self.gridLayout.addWidget(self.frameSidebar, 1, 0, 8, 1)
        self.groupDrawRange = QtWidgets.QGroupBox(dialogSliceConverter)
        self.groupDrawRange.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupDrawRange.sizePolicy().hasHeightForWidth())
        self.groupDrawRange.setSizePolicy(sizePolicy)
        self.groupDrawRange.setObjectName("groupDrawRange")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupDrawRange)
        self.verticalLayout_5.setContentsMargins(-1, 6, -1, 6)
        self.verticalLayout_5.setSpacing(3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.spinRangeLow = QtWidgets.QSpinBox(self.groupDrawRange)
        self.spinRangeLow.setMinimum(1)
        self.spinRangeLow.setMaximum(9999)
        self.spinRangeLow.setObjectName("spinRangeLow")
        self.verticalLayout_5.addWidget(self.spinRangeLow)
        self.spinRangeHigh = QtWidgets.QSpinBox(self.groupDrawRange)
        self.spinRangeHigh.setMinimum(1)
        self.spinRangeHigh.setMaximum(9999)
        self.spinRangeHigh.setObjectName("spinRangeHigh")
        self.verticalLayout_5.addWidget(self.spinRangeHigh)
        self.gridLayout.addWidget(self.groupDrawRange, 8, 2, 1, 1)
        self.frameOutputFolder = QtWidgets.QFrame(dialogSliceConverter)
        self.frameOutputFolder.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameOutputFolder.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameOutputFolder.setObjectName("frameOutputFolder")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frameOutputFolder)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labelOutputFolder = QtWidgets.QLabel(self.frameOutputFolder)
        self.labelOutputFolder.setObjectName("labelOutputFolder")
        self.horizontalLayout_2.addWidget(self.labelOutputFolder)
        self.lineOutputFolder = QtWidgets.QLineEdit(self.frameOutputFolder)
        self.lineOutputFolder.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineOutputFolder.setReadOnly(True)
        self.lineOutputFolder.setObjectName("lineOutputFolder")
        self.horizontalLayout_2.addWidget(self.lineOutputFolder)
        self.pushBrowseOF = QtWidgets.QPushButton(self.frameOutputFolder)
        self.pushBrowseOF.setObjectName("pushBrowseOF")
        self.horizontalLayout_2.addWidget(self.pushBrowseOF)
        self.gridLayout.addWidget(self.frameOutputFolder, 12, 0, 1, 7)
        self.groupDisplayControl = QtWidgets.QGroupBox(dialogSliceConverter)
        self.groupDisplayControl.setEnabled(False)
        self.groupDisplayControl.setObjectName("groupDisplayControl")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupDisplayControl)
        self.gridLayout_5.setContentsMargins(-1, 6, -1, 6)
        self.gridLayout_5.setVerticalSpacing(3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.pushZoomIn = QtWidgets.QPushButton(self.groupDisplayControl)
        self.pushZoomIn.setCheckable(True)
        self.pushZoomIn.setObjectName("pushZoomIn")
        self.gridLayout_5.addWidget(self.pushZoomIn, 0, 0, 1, 3)
        self.pushZoomOut = QtWidgets.QPushButton(self.groupDisplayControl)
        self.pushZoomOut.setObjectName("pushZoomOut")
        self.gridLayout_5.addWidget(self.pushZoomOut, 1, 0, 1, 3)
        self.spinSliceNumber = QtWidgets.QSpinBox(self.groupDisplayControl)
        self.spinSliceNumber.setMinimum(1)
        self.spinSliceNumber.setMaximum(9999)
        self.spinSliceNumber.setObjectName("spinSliceNumber")
        self.gridLayout_5.addWidget(self.spinSliceNumber, 4, 0, 1, 2)
        self.pushGo = QtWidgets.QPushButton(self.groupDisplayControl)
        self.pushGo.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushGo.setObjectName("pushGo")
        self.gridLayout_5.addWidget(self.pushGo, 4, 2, 1, 1)
        self.labelSliceNumberTitle = QtWidgets.QLabel(self.groupDisplayControl)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.labelSliceNumberTitle.setFont(font)
        self.labelSliceNumberTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.labelSliceNumberTitle.setObjectName("labelSliceNumberTitle")
        self.gridLayout_5.addWidget(self.labelSliceNumberTitle, 2, 0, 1, 3)
        self.labelSliceNumber = QtWidgets.QLabel(self.groupDisplayControl)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelSliceNumber.setFont(font)
        self.labelSliceNumber.setAlignment(QtCore.Qt.AlignCenter)
        self.labelSliceNumber.setObjectName("labelSliceNumber")
        self.gridLayout_5.addWidget(self.labelSliceNumber, 3, 0, 1, 3)
        self.gridLayout.addWidget(self.groupDisplayControl, 7, 1, 2, 1)
        self.groupTranslation = QtWidgets.QGroupBox(dialogSliceConverter)
        self.groupTranslation.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupTranslation.sizePolicy().hasHeightForWidth())
        self.groupTranslation.setSizePolicy(sizePolicy)
        self.groupTranslation.setObjectName("groupTranslation")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupTranslation)
        self.gridLayout_3.setContentsMargins(-1, 6, -1, 6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.labelUnits = QtWidgets.QLabel(self.groupTranslation)
        self.labelUnits.setObjectName("labelUnits")
        self.gridLayout_3.addWidget(self.labelUnits, 1, 3, 1, 1)
        self.pushTranslate = QtWidgets.QPushButton(self.groupTranslation)
        self.pushTranslate.setObjectName("pushTranslate")
        self.gridLayout_3.addWidget(self.pushTranslate, 2, 0, 1, 4)
        self.labelY = QtWidgets.QLabel(self.groupTranslation)
        self.labelY.setAlignment(QtCore.Qt.AlignCenter)
        self.labelY.setObjectName("labelY")
        self.gridLayout_3.addWidget(self.labelY, 0, 2, 1, 1)
        self.labelX = QtWidgets.QLabel(self.groupTranslation)
        self.labelX.setAlignment(QtCore.Qt.AlignCenter)
        self.labelX.setObjectName("labelX")
        self.gridLayout_3.addWidget(self.labelX, 0, 1, 1, 1)
        self.spinY = QtWidgets.QSpinBox(self.groupTranslation)
        self.spinY.setMinimum(-2410)
        self.spinY.setMaximum(2410)
        self.spinY.setObjectName("spinY")
        self.gridLayout_3.addWidget(self.spinY, 1, 2, 1, 1)
        self.spinX = QtWidgets.QSpinBox(self.groupTranslation)
        self.spinX.setMinimum(-3470)
        self.spinX.setMaximum(3470)
        self.spinX.setObjectName("spinX")
        self.gridLayout_3.addWidget(self.spinX, 1, 1, 1, 1)
        self.pushResetT = QtWidgets.QPushButton(self.groupTranslation)
        self.pushResetT.setObjectName("pushResetT")
        self.gridLayout_3.addWidget(self.pushResetT, 3, 0, 1, 4)
        self.gridLayout.addWidget(self.groupTranslation, 7, 5, 2, 1)
        self.groupRotation = QtWidgets.QGroupBox(dialogSliceConverter)
        self.groupRotation.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupRotation.sizePolicy().hasHeightForWidth())
        self.groupRotation.setSizePolicy(sizePolicy)
        self.groupRotation.setObjectName("groupRotation")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupRotation)
        self.gridLayout_4.setContentsMargins(-1, 6, -1, 6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.labelDegree = QtWidgets.QLabel(self.groupRotation)
        self.labelDegree.setAlignment(QtCore.Qt.AlignCenter)
        self.labelDegree.setObjectName("labelDegree")
        self.gridLayout_4.addWidget(self.labelDegree, 1, 2, 1, 1)
        self.labelAngle = QtWidgets.QLabel(self.groupRotation)
        self.labelAngle.setAlignment(QtCore.Qt.AlignCenter)
        self.labelAngle.setObjectName("labelAngle")
        self.gridLayout_4.addWidget(self.labelAngle, 0, 1, 1, 1)
        self.pushResetR = QtWidgets.QPushButton(self.groupRotation)
        self.pushResetR.setObjectName("pushResetR")
        self.gridLayout_4.addWidget(self.pushResetR, 3, 0, 1, 3)
        self.spinAngle = QtWidgets.QSpinBox(self.groupRotation)
        self.spinAngle.setMinimum(-360)
        self.spinAngle.setMaximum(360)
        self.spinAngle.setObjectName("spinAngle")
        self.gridLayout_4.addWidget(self.spinAngle, 1, 1, 1, 1)
        self.pushRotate = QtWidgets.QPushButton(self.groupRotation)
        self.pushRotate.setObjectName("pushRotate")
        self.gridLayout_4.addWidget(self.pushRotate, 2, 0, 1, 3)
        self.gridLayout.addWidget(self.groupRotation, 7, 4, 2, 1)
        self.tableTransform = QtWidgets.QTableWidget(dialogSliceConverter)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tableTransform.setFont(font)
        self.tableTransform.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableTransform.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tableTransform.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableTransform.setObjectName("tableTransform")
        self.tableTransform.setColumnCount(0)
        self.tableTransform.setRowCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.tableTransform.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableTransform.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableTransform.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableTransform.setVerticalHeaderItem(3, item)
        self.tableTransform.horizontalHeader().setVisible(False)
        self.gridLayout.addWidget(self.tableTransform, 7, 6, 2, 1)
        self.pushDone = QtWidgets.QPushButton(dialogSliceConverter)
        self.pushDone.setObjectName("pushDone")
        self.gridLayout.addWidget(self.pushDone, 12, 7, 1, 1)
        self.graphicsDisplay = ImageViewer(dialogSliceConverter)
        self.graphicsDisplay.setMouseTracking(True)
        self.graphicsDisplay.setObjectName("graphicsDisplay")
        self.gridLayout.addWidget(self.graphicsDisplay, 1, 1, 6, 7)
        self.groupMousePosition = QtWidgets.QGroupBox(dialogSliceConverter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupMousePosition.sizePolicy().hasHeightForWidth())
        self.groupMousePosition.setSizePolicy(sizePolicy)
        self.groupMousePosition.setObjectName("groupMousePosition")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupMousePosition)
        self.gridLayout_7.setContentsMargins(-1, 6, -1, 6)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.labelYPosition = QtWidgets.QLabel(self.groupMousePosition)
        self.labelYPosition.setAlignment(QtCore.Qt.AlignCenter)
        self.labelYPosition.setObjectName("labelYPosition")
        self.gridLayout_7.addWidget(self.labelYPosition, 1, 0, 1, 1)
        self.labelXPosition = QtWidgets.QLabel(self.groupMousePosition)
        self.labelXPosition.setAlignment(QtCore.Qt.AlignCenter)
        self.labelXPosition.setObjectName("labelXPosition")
        self.gridLayout_7.addWidget(self.labelXPosition, 0, 0, 1, 1)
        self.labelXUnits = QtWidgets.QLabel(self.groupMousePosition)
        self.labelXUnits.setObjectName("labelXUnits")
        self.gridLayout_7.addWidget(self.labelXUnits, 0, 1, 1, 1)
        self.labelYUnits = QtWidgets.QLabel(self.groupMousePosition)
        self.labelYUnits.setObjectName("labelYUnits")
        self.gridLayout_7.addWidget(self.labelYUnits, 1, 1, 1, 1)
        self.gridLayout.addWidget(self.groupMousePosition, 7, 2, 1, 1)
        self.groupROI = QtWidgets.QGroupBox(dialogSliceConverter)
        self.groupROI.setEnabled(False)
        self.groupROI.setObjectName("groupROI")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupROI)
        self.gridLayout_2.setContentsMargins(-1, 6, -1, 6)
        self.gridLayout_2.setVerticalSpacing(3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushSelect = QtWidgets.QPushButton(self.groupROI)
        self.pushSelect.setCheckable(True)
        self.pushSelect.setObjectName("pushSelect")
        self.gridLayout_2.addWidget(self.pushSelect, 0, 0, 1, 2)
        self.labelTopLeft = QtWidgets.QLabel(self.groupROI)
        self.labelTopLeft.setObjectName("labelTopLeft")
        self.gridLayout_2.addWidget(self.labelTopLeft, 3, 0, 1, 1)
        self.labelResolution = QtWidgets.QLabel(self.groupROI)
        self.labelResolution.setObjectName("labelResolution")
        self.gridLayout_2.addWidget(self.labelResolution, 4, 0, 1, 1)
        self.pushSet = QtWidgets.QPushButton(self.groupROI)
        self.pushSet.setObjectName("pushSet")
        self.gridLayout_2.addWidget(self.pushSet, 5, 0, 1, 3)
        self.pushRemove = QtWidgets.QPushButton(self.groupROI)
        self.pushRemove.setObjectName("pushRemove")
        self.gridLayout_2.addWidget(self.pushRemove, 0, 2, 1, 1)
        self.labelSpacer = QtWidgets.QLabel(self.groupROI)
        self.labelSpacer.setText("")
        self.labelSpacer.setObjectName("labelSpacer")
        self.gridLayout_2.addWidget(self.labelSpacer, 2, 0, 1, 1)
        self.frame = QtWidgets.QFrame(self.groupROI)
        self.frame.setMinimumSize(QtCore.QSize(100, 0))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setVerticalSpacing(3)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.labelYROI = QtWidgets.QLabel(self.frame)
        self.labelYROI.setAlignment(QtCore.Qt.AlignCenter)
        self.labelYROI.setObjectName("labelYROI")
        self.gridLayout_6.addWidget(self.labelYROI, 0, 1, 1, 1)
        self.labelXROI = QtWidgets.QLabel(self.frame)
        self.labelXROI.setAlignment(QtCore.Qt.AlignCenter)
        self.labelXROI.setObjectName("labelXROI")
        self.gridLayout_6.addWidget(self.labelXROI, 0, 0, 1, 1)
        self.spinResolutionX = QtWidgets.QSpinBox(self.frame)
        self.spinResolutionX.setMaximum(9999)
        self.spinResolutionX.setObjectName("spinResolutionX")
        self.gridLayout_6.addWidget(self.spinResolutionX, 2, 0, 1, 1)
        self.spinTLX = QtWidgets.QSpinBox(self.frame)
        self.spinTLX.setMaximum(9999)
        self.spinTLX.setObjectName("spinTLX")
        self.gridLayout_6.addWidget(self.spinTLX, 1, 0, 1, 1)
        self.spinResolutionY = QtWidgets.QSpinBox(self.frame)
        self.spinResolutionY.setMaximum(9999)
        self.spinResolutionY.setObjectName("spinResolutionY")
        self.gridLayout_6.addWidget(self.spinResolutionY, 2, 1, 1, 1)
        self.spinTLY = QtWidgets.QSpinBox(self.frame)
        self.spinTLY.setMaximum(9999)
        self.spinTLY.setObjectName("spinTLY")
        self.gridLayout_6.addWidget(self.spinTLY, 1, 1, 1, 1)
        self.labelTLUnits = QtWidgets.QLabel(self.frame)
        self.labelTLUnits.setObjectName("labelTLUnits")
        self.gridLayout_6.addWidget(self.labelTLUnits, 1, 2, 1, 1)
        self.labelResUnits = QtWidgets.QLabel(self.frame)
        self.labelResUnits.setObjectName("labelResUnits")
        self.gridLayout_6.addWidget(self.labelResUnits, 2, 2, 1, 1)
        self.gridLayout_2.addWidget(self.frame, 2, 1, 3, 2)
        self.gridLayout.addWidget(self.groupROI, 7, 3, 2, 1)

        self.retranslateUi(dialogSliceConverter)
        self.pushDone.clicked.connect(dialogSliceConverter.close)
        self.checkBackground.toggled['bool'].connect(self.lineBackground.setEnabled)
        self.checkBackground.toggled['bool'].connect(self.pushBrowseCB.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(dialogSliceConverter)
        dialogSliceConverter.setTabOrder(self.listSliceFiles, self.graphicsDisplay)
        dialogSliceConverter.setTabOrder(self.graphicsDisplay, self.pushAddSF)
        dialogSliceConverter.setTabOrder(self.pushAddSF, self.pushRemoveSF)
        dialogSliceConverter.setTabOrder(self.pushRemoveSF, self.pushDrawContours)
        dialogSliceConverter.setTabOrder(self.pushDrawContours, self.checkCentrelines)
        dialogSliceConverter.setTabOrder(self.checkCentrelines, self.checkFillContours)
        dialogSliceConverter.setTabOrder(self.checkFillContours, self.checkBackground)
        dialogSliceConverter.setTabOrder(self.checkBackground, self.lineBackground)
        dialogSliceConverter.setTabOrder(self.lineBackground, self.pushBrowseCB)
        dialogSliceConverter.setTabOrder(self.pushBrowseCB, self.pushZoomIn)
        dialogSliceConverter.setTabOrder(self.pushZoomIn, self.pushZoomOut)
        dialogSliceConverter.setTabOrder(self.pushZoomOut, self.spinSliceNumber)
        dialogSliceConverter.setTabOrder(self.spinSliceNumber, self.pushGo)
        dialogSliceConverter.setTabOrder(self.pushGo, self.spinRangeLow)
        dialogSliceConverter.setTabOrder(self.spinRangeLow, self.spinRangeHigh)
        dialogSliceConverter.setTabOrder(self.spinRangeHigh, self.pushSelect)
        dialogSliceConverter.setTabOrder(self.pushSelect, self.pushRemove)
        dialogSliceConverter.setTabOrder(self.pushRemove, self.spinTLX)
        dialogSliceConverter.setTabOrder(self.spinTLX, self.spinTLY)
        dialogSliceConverter.setTabOrder(self.spinTLY, self.spinResolutionX)
        dialogSliceConverter.setTabOrder(self.spinResolutionX, self.spinResolutionY)
        dialogSliceConverter.setTabOrder(self.spinResolutionY, self.pushSet)
        dialogSliceConverter.setTabOrder(self.pushSet, self.spinAngle)
        dialogSliceConverter.setTabOrder(self.spinAngle, self.pushRotate)
        dialogSliceConverter.setTabOrder(self.pushRotate, self.pushResetR)
        dialogSliceConverter.setTabOrder(self.pushResetR, self.spinX)
        dialogSliceConverter.setTabOrder(self.spinX, self.spinY)
        dialogSliceConverter.setTabOrder(self.spinY, self.pushTranslate)
        dialogSliceConverter.setTabOrder(self.pushTranslate, self.pushResetT)
        dialogSliceConverter.setTabOrder(self.pushResetT, self.tableTransform)
        dialogSliceConverter.setTabOrder(self.tableTransform, self.pushPause)
        dialogSliceConverter.setTabOrder(self.pushPause, self.pushBrowseOF)
        dialogSliceConverter.setTabOrder(self.pushBrowseOF, self.pushDone)

    def retranslateUi(self, dialogSliceConverter):
        _translate = QtCore.QCoreApplication.translate
        dialogSliceConverter.setWindowTitle(_translate("dialogSliceConverter", "Slice Converter"))
        self.groupStatus.setTitle(_translate("dialogSliceConverter", "Status"))
        self.labelCurrentPart.setText(_translate("dialogSliceConverter", "Current Part"))
        self.labelStatusPart.setText(_translate("dialogSliceConverter", "None"))
        self.labelStatus.setText(_translate("dialogSliceConverter", "Add slice files."))
        self.pushPause.setText(_translate("dialogSliceConverter", "Pause"))
        self.pushAddSF.setText(_translate("dialogSliceConverter", "Add Slice Files..."))
        self.pushRemoveSF.setText(_translate("dialogSliceConverter", "Remove Slice Files"))
        self.pushDrawContours.setText(_translate("dialogSliceConverter", "Draw Contours"))
        self.groupDisplayOptions.setTitle(_translate("dialogSliceConverter", "Display Options"))
        self.checkCentrelines.setText(_translate("dialogSliceConverter", "Centrelines"))
        self.checkFillContours.setText(_translate("dialogSliceConverter", "Fill Contours"))
        self.checkBackground.setText(_translate("dialogSliceConverter", "Custom Background"))
        self.pushBrowseCB.setText(_translate("dialogSliceConverter", "Browse..."))
        self.groupDrawRange.setTitle(_translate("dialogSliceConverter", "Draw Range"))
        self.labelOutputFolder.setText(_translate("dialogSliceConverter", "Output Folder"))
        self.pushBrowseOF.setText(_translate("dialogSliceConverter", "Browse..."))
        self.groupDisplayControl.setTitle(_translate("dialogSliceConverter", "Display Control"))
        self.pushZoomIn.setText(_translate("dialogSliceConverter", "Zoom In"))
        self.pushZoomOut.setText(_translate("dialogSliceConverter", "Zoom Out"))
        self.pushGo.setText(_translate("dialogSliceConverter", "Go"))
        self.labelSliceNumberTitle.setText(_translate("dialogSliceConverter", "Slice Number"))
        self.labelSliceNumber.setText(_translate("dialogSliceConverter", "0001 / 0001"))
        self.groupTranslation.setTitle(_translate("dialogSliceConverter", "Translation"))
        self.labelUnits.setText(_translate("dialogSliceConverter", "px"))
        self.pushTranslate.setText(_translate("dialogSliceConverter", "Translate"))
        self.labelY.setText(_translate("dialogSliceConverter", "Y"))
        self.labelX.setText(_translate("dialogSliceConverter", "X"))
        self.spinY.setToolTip(_translate("dialogSliceConverter", "-2410 - 2410"))
        self.spinX.setToolTip(_translate("dialogSliceConverter", "-3470 - 3470"))
        self.pushResetT.setText(_translate("dialogSliceConverter", "Reset"))
        self.groupRotation.setTitle(_translate("dialogSliceConverter", "Rotation"))
        self.labelDegree.setText(_translate("dialogSliceConverter", "°"))
        self.labelAngle.setText(_translate("dialogSliceConverter", "Angle"))
        self.pushResetR.setText(_translate("dialogSliceConverter", "Reset"))
        self.spinAngle.setToolTip(_translate("dialogSliceConverter", "-360 - 360"))
        self.pushRotate.setText(_translate("dialogSliceConverter", "Rotate"))
        item = self.tableTransform.verticalHeaderItem(0)
        item.setText(_translate("dialogSliceConverter", "Part"))
        item = self.tableTransform.verticalHeaderItem(1)
        item.setText(_translate("dialogSliceConverter", "X"))
        item = self.tableTransform.verticalHeaderItem(2)
        item.setText(_translate("dialogSliceConverter", "Y"))
        item = self.tableTransform.verticalHeaderItem(3)
        item.setText(_translate("dialogSliceConverter", "Angle"))
        self.pushDone.setText(_translate("dialogSliceConverter", "Done"))
        self.groupMousePosition.setTitle(_translate("dialogSliceConverter", "Mouse Position"))
        self.labelYPosition.setText(_translate("dialogSliceConverter", "Y     0000"))
        self.labelXPosition.setText(_translate("dialogSliceConverter", "X     0000"))
        self.labelXUnits.setText(_translate("dialogSliceConverter", "px"))
        self.labelYUnits.setText(_translate("dialogSliceConverter", "px"))
        self.groupROI.setTitle(_translate("dialogSliceConverter", "Region of Interest"))
        self.pushSelect.setText(_translate("dialogSliceConverter", "Select"))
        self.labelTopLeft.setText(_translate("dialogSliceConverter", "Top Left"))
        self.labelResolution.setText(_translate("dialogSliceConverter", "Resolution"))
        self.pushSet.setText(_translate("dialogSliceConverter", "Set"))
        self.pushRemove.setText(_translate("dialogSliceConverter", "Remove"))
        self.labelYROI.setText(_translate("dialogSliceConverter", "Y"))
        self.labelXROI.setText(_translate("dialogSliceConverter", "X"))
        self.labelTLUnits.setText(_translate("dialogSliceConverter", "px"))
        self.labelResUnits.setText(_translate("dialogSliceConverter", "px"))

from ui_elements import ImageViewer
