# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui\dialogCameraSettings.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_dialogCameraSettings(object):
    def setupUi(self, dialogCameraSettings):
        dialogCameraSettings.setObjectName("dialogCameraSettings")
        dialogCameraSettings.resize(270, 251)
        self.gridLayout = QtWidgets.QGridLayout(dialogCameraSettings)
        self.gridLayout.setObjectName("gridLayout")
        self.frameButtons = QtWidgets.QFrame(dialogCameraSettings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameButtons.sizePolicy().hasHeightForWidth())
        self.frameButtons.setSizePolicy(sizePolicy)
        self.frameButtons.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameButtons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameButtons.setObjectName("frameButtons")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frameButtons)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushApply = QtWidgets.QPushButton(self.frameButtons)
        self.pushApply.setEnabled(False)
        self.pushApply.setObjectName("pushApply")
        self.horizontalLayout.addWidget(self.pushApply)
        self.pushOK = QtWidgets.QPushButton(self.frameButtons)
        self.pushOK.setObjectName("pushOK")
        self.horizontalLayout.addWidget(self.pushOK)
        self.pushCancel = QtWidgets.QPushButton(self.frameButtons)
        self.pushCancel.setEnabled(True)
        self.pushCancel.setObjectName("pushCancel")
        self.horizontalLayout.addWidget(self.pushCancel)
        self.gridLayout.addWidget(self.frameButtons, 8, 0, 1, 4)
        self.spinInterPacketDelay = QtWidgets.QSpinBox(dialogCameraSettings)
        self.spinInterPacketDelay.setSuffix("")
        self.spinInterPacketDelay.setMaximum(10000)
        self.spinInterPacketDelay.setProperty("value", 0)
        self.spinInterPacketDelay.setObjectName("spinInterPacketDelay")
        self.gridLayout.addWidget(self.spinInterPacketDelay, 5, 2, 1, 2)
        self.labelGain = QtWidgets.QLabel(dialogCameraSettings)
        self.labelGain.setObjectName("labelGain")
        self.gridLayout.addWidget(self.labelGain, 1, 0, 1, 1)
        self.labelFrameDelay = QtWidgets.QLabel(dialogCameraSettings)
        self.labelFrameDelay.setScaledContents(False)
        self.labelFrameDelay.setObjectName("labelFrameDelay")
        self.gridLayout.addWidget(self.labelFrameDelay, 6, 0, 1, 2)
        self.spinPacketSize = QtWidgets.QSpinBox(dialogCameraSettings)
        self.spinPacketSize.setMinimum(0)
        self.spinPacketSize.setMaximum(1500)
        self.spinPacketSize.setSingleStep(4)
        self.spinPacketSize.setProperty("value", 1500)
        self.spinPacketSize.setObjectName("spinPacketSize")
        self.gridLayout.addWidget(self.spinPacketSize, 4, 2, 1, 2)
        self.labelPixelFormat = QtWidgets.QLabel(dialogCameraSettings)
        self.labelPixelFormat.setObjectName("labelPixelFormat")
        self.gridLayout.addWidget(self.labelPixelFormat, 0, 0, 1, 1)
        self.labelTriggerTimeout = QtWidgets.QLabel(dialogCameraSettings)
        self.labelTriggerTimeout.setObjectName("labelTriggerTimeout")
        self.gridLayout.addWidget(self.labelTriggerTimeout, 7, 0, 1, 1)
        self.labelPacketSize = QtWidgets.QLabel(dialogCameraSettings)
        self.labelPacketSize.setObjectName("labelPacketSize")
        self.gridLayout.addWidget(self.labelPacketSize, 4, 0, 1, 1)
        self.labelInterPacketDelay = QtWidgets.QLabel(dialogCameraSettings)
        self.labelInterPacketDelay.setObjectName("labelInterPacketDelay")
        self.gridLayout.addWidget(self.labelInterPacketDelay, 5, 0, 1, 1)
        self.spinTriggerTimeout = QtWidgets.QSpinBox(dialogCameraSettings)
        self.spinTriggerTimeout.setMaximum(60)
        self.spinTriggerTimeout.setProperty("value", 3)
        self.spinTriggerTimeout.setObjectName("spinTriggerTimeout")
        self.gridLayout.addWidget(self.spinTriggerTimeout, 7, 2, 1, 2)
        self.spinFrameDelay = QtWidgets.QSpinBox(dialogCameraSettings)
        self.spinFrameDelay.setMaximum(10000)
        self.spinFrameDelay.setProperty("value", 0)
        self.spinFrameDelay.setObjectName("spinFrameDelay")
        self.gridLayout.addWidget(self.spinFrameDelay, 6, 2, 1, 2)
        self.labelExposureTime = QtWidgets.QLabel(dialogCameraSettings)
        self.labelExposureTime.setObjectName("labelExposureTime")
        self.gridLayout.addWidget(self.labelExposureTime, 3, 0, 1, 1)
        self.comboPixelFormat = QtWidgets.QComboBox(dialogCameraSettings)
        self.comboPixelFormat.setObjectName("comboPixelFormat")
        self.comboPixelFormat.addItem("")
        self.comboPixelFormat.addItem("")
        self.comboPixelFormat.addItem("")
        self.gridLayout.addWidget(self.comboPixelFormat, 0, 2, 1, 2)
        self.spinExposureTime = QtWidgets.QSpinBox(dialogCameraSettings)
        self.spinExposureTime.setMinimum(35)
        self.spinExposureTime.setMaximum(100000)
        self.spinExposureTime.setProperty("value", 23000)
        self.spinExposureTime.setObjectName("spinExposureTime")
        self.gridLayout.addWidget(self.spinExposureTime, 3, 2, 1, 2)
        self.labelBlackLevel = QtWidgets.QLabel(dialogCameraSettings)
        self.labelBlackLevel.setObjectName("labelBlackLevel")
        self.gridLayout.addWidget(self.labelBlackLevel, 2, 0, 1, 1)
        self.spinBlackLevel = QtWidgets.QSpinBox(dialogCameraSettings)
        self.spinBlackLevel.setMaximum(1023)
        self.spinBlackLevel.setProperty("value", 21)
        self.spinBlackLevel.setObjectName("spinBlackLevel")
        self.gridLayout.addWidget(self.spinBlackLevel, 2, 2, 1, 2)
        self.spinGain = QtWidgets.QSpinBox(dialogCameraSettings)
        self.spinGain.setMinimum(51)
        self.spinGain.setMaximum(255)
        self.spinGain.setProperty("value", 51)
        self.spinGain.setObjectName("spinGain")
        self.gridLayout.addWidget(self.spinGain, 1, 2, 1, 2)

        self.retranslateUi(dialogCameraSettings)
        self.pushOK.clicked.connect(dialogCameraSettings.accept)
        self.pushCancel.clicked.connect(dialogCameraSettings.close)
        QtCore.QMetaObject.connectSlotsByName(dialogCameraSettings)
        dialogCameraSettings.setTabOrder(self.comboPixelFormat, self.spinExposureTime)
        dialogCameraSettings.setTabOrder(self.spinExposureTime, self.spinPacketSize)
        dialogCameraSettings.setTabOrder(self.spinPacketSize, self.spinInterPacketDelay)
        dialogCameraSettings.setTabOrder(self.spinInterPacketDelay, self.spinFrameDelay)
        dialogCameraSettings.setTabOrder(self.spinFrameDelay, self.spinTriggerTimeout)
        dialogCameraSettings.setTabOrder(self.spinTriggerTimeout, self.pushApply)
        dialogCameraSettings.setTabOrder(self.pushApply, self.pushOK)
        dialogCameraSettings.setTabOrder(self.pushOK, self.pushCancel)

    def retranslateUi(self, dialogCameraSettings):
        _translate = QtCore.QCoreApplication.translate
        dialogCameraSettings.setWindowTitle(_translate("dialogCameraSettings", "Camera Settings"))
        self.pushApply.setText(_translate("dialogCameraSettings", "Apply"))
        self.pushOK.setText(_translate("dialogCameraSettings", "OK"))
        self.pushCancel.setText(_translate("dialogCameraSettings", "Cancel"))
        self.spinInterPacketDelay.setToolTip(_translate("dialogCameraSettings", "0 - 10,000"))
        self.labelGain.setToolTip(_translate("dialogCameraSettings", "Sets the selected gain control in device specific units."))
        self.labelGain.setText(_translate("dialogCameraSettings", "Gain"))
        self.labelFrameDelay.setToolTip(_translate("dialogCameraSettings", "Sets the frame transfer start delay (in ticks) for the selected stream channel."))
        self.labelFrameDelay.setText(_translate("dialogCameraSettings", "Frame Transmission Delay"))
        self.spinPacketSize.setToolTip(_translate("dialogCameraSettings", "0 - 1,500"))
        self.labelPixelFormat.setToolTip(_translate("dialogCameraSettings", "Sets the format of the pixel data transmitted for acquired images."))
        self.labelPixelFormat.setText(_translate("dialogCameraSettings", "Pixel Format"))
        self.labelTriggerTimeout.setToolTip(_translate("dialogCameraSettings", "Sets how long (in seconds) until the trigger can be triggered again. Timeout starts upon saving the image."))
        self.labelTriggerTimeout.setText(_translate("dialogCameraSettings", "Trigger Timeout"))
        self.labelPacketSize.setToolTip(_translate("dialogCameraSettings", "Sets the packet size in bytes for the selected stream channel."))
        self.labelPacketSize.setText(_translate("dialogCameraSettings", "Packet Size"))
        self.labelInterPacketDelay.setToolTip(_translate("dialogCameraSettings", "Sets the inter-packet delay (in ticks) for the selected stream channel."))
        self.labelInterPacketDelay.setText(_translate("dialogCameraSettings", "Inter-Packet Delay"))
        self.spinTriggerTimeout.setToolTip(_translate("dialogCameraSettings", "0 - 60"))
        self.spinFrameDelay.setToolTip(_translate("dialogCameraSettings", "0 - 10,000"))
        self.labelExposureTime.setToolTip(_translate("dialogCameraSettings", "Directly sets the camera\'s exposure time in microseconds."))
        self.labelExposureTime.setText(_translate("dialogCameraSettings", "Exposure Time"))
        self.comboPixelFormat.setItemText(0, _translate("dialogCameraSettings", "Mono 8"))
        self.comboPixelFormat.setItemText(1, _translate("dialogCameraSettings", "Mono 12"))
        self.comboPixelFormat.setItemText(2, _translate("dialogCameraSettings", "Mono 12 Packed"))
        self.spinExposureTime.setToolTip(_translate("dialogCameraSettings", "0 - 100,000"))
        self.labelBlackLevel.setToolTip(_translate("dialogCameraSettings", "Sets the value of the selected black level control."))
        self.labelBlackLevel.setText(_translate("dialogCameraSettings", "Black Level"))
        self.spinBlackLevel.setToolTip(_translate("dialogCameraSettings", "0 - 1,023"))
        self.spinGain.setToolTip(_translate("dialogCameraSettings", "51 - 255"))

