# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialogOverlayAdjustment.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_dialogOverlayAdjustment(object):
    def setupUi(self, dialogOverlayAdjustment):
        dialogOverlayAdjustment.setObjectName(_fromUtf8("dialogOverlayAdjustment"))
        dialogOverlayAdjustment.resize(361, 361)
        dialogOverlayAdjustment.setMinimumSize(QtCore.QSize(361, 361))
        dialogOverlayAdjustment.setMaximumSize(QtCore.QSize(361, 361))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/resources/logo.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        dialogOverlayAdjustment.setWindowIcon(icon)
        self.labelInformation = QtGui.QLabel(dialogOverlayAdjustment)
        self.labelInformation.setGeometry(QtCore.QRect(10, 5, 351, 41))
        self.labelInformation.setWordWrap(True)
        self.labelInformation.setObjectName(_fromUtf8("labelInformation"))
        self.buttonDone = QtGui.QPushButton(dialogOverlayAdjustment)
        self.buttonDone.setGeometry(QtCore.QRect(200, 323, 151, 28))
        self.buttonDone.setObjectName(_fromUtf8("buttonDone"))
        self.groupValues = QtGui.QGroupBox(dialogOverlayAdjustment)
        self.groupValues.setEnabled(True)
        self.groupValues.setGeometry(QtCore.QRect(10, 50, 139, 91))
        self.groupValues.setObjectName(_fromUtf8("groupValues"))
        self.gridLayout = QtGui.QGridLayout(self.groupValues)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.labelPixels = QtGui.QLabel(self.groupValues)
        self.labelPixels.setObjectName(_fromUtf8("labelPixels"))
        self.gridLayout.addWidget(self.labelPixels, 0, 0, 1, 1)
        self.spinPixels = QtGui.QSpinBox(self.groupValues)
        self.spinPixels.setMinimum(1)
        self.spinPixels.setMaximum(5000)
        self.spinPixels.setObjectName(_fromUtf8("spinPixels"))
        self.gridLayout.addWidget(self.spinPixels, 0, 1, 1, 1)
        self.labelDegrees = QtGui.QLabel(self.groupValues)
        self.labelDegrees.setObjectName(_fromUtf8("labelDegrees"))
        self.gridLayout.addWidget(self.labelDegrees, 1, 0, 1, 1)
        self.spinDegrees = QtGui.QDoubleSpinBox(self.groupValues)
        self.spinDegrees.setMinimum(0.0)
        self.spinDegrees.setMaximum(360.0)
        self.spinDegrees.setProperty("value", 1.0)
        self.spinDegrees.setObjectName(_fromUtf8("spinDegrees"))
        self.gridLayout.addWidget(self.spinDegrees, 1, 1, 1, 1)
        self.groupTranslation = QtGui.QGroupBox(dialogOverlayAdjustment)
        self.groupTranslation.setGeometry(QtCore.QRect(270, 50, 81, 191))
        self.groupTranslation.setObjectName(_fromUtf8("groupTranslation"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupTranslation)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.buttonTranslateUp = QtGui.QPushButton(self.groupTranslation)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.buttonTranslateUp.setFont(font)
        self.buttonTranslateUp.setObjectName(_fromUtf8("buttonTranslateUp"))
        self.gridLayout_2.addWidget(self.buttonTranslateUp, 0, 0, 1, 1)
        self.buttonTranslateDown = QtGui.QPushButton(self.groupTranslation)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.buttonTranslateDown.setFont(font)
        self.buttonTranslateDown.setObjectName(_fromUtf8("buttonTranslateDown"))
        self.gridLayout_2.addWidget(self.buttonTranslateDown, 1, 0, 1, 1)
        self.buttonTranslateLeft = QtGui.QPushButton(self.groupTranslation)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.buttonTranslateLeft.setFont(font)
        self.buttonTranslateLeft.setObjectName(_fromUtf8("buttonTranslateLeft"))
        self.gridLayout_2.addWidget(self.buttonTranslateLeft, 2, 0, 1, 1)
        self.buttonTranslateRight = QtGui.QPushButton(self.groupTranslation)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.buttonTranslateRight.setFont(font)
        self.buttonTranslateRight.setObjectName(_fromUtf8("buttonTranslateRight"))
        self.gridLayout_2.addWidget(self.buttonTranslateRight, 3, 0, 1, 1)
        self.groupRotationFlip = QtGui.QGroupBox(dialogOverlayAdjustment)
        self.groupRotationFlip.setGeometry(QtCore.QRect(200, 250, 151, 71))
        self.groupRotationFlip.setObjectName(_fromUtf8("groupRotationFlip"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupRotationFlip)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.buttonRotateACW = QtGui.QPushButton(self.groupRotationFlip)
        self.buttonRotateACW.setMinimumSize(QtCore.QSize(31, 31))
        self.buttonRotateACW.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.buttonRotateACW.setFont(font)
        self.buttonRotateACW.setObjectName(_fromUtf8("buttonRotateACW"))
        self.horizontalLayout.addWidget(self.buttonRotateACW)
        self.buttonRotateCW = QtGui.QPushButton(self.groupRotationFlip)
        self.buttonRotateCW.setMinimumSize(QtCore.QSize(31, 31))
        self.buttonRotateCW.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.buttonRotateCW.setFont(font)
        self.buttonRotateCW.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.buttonRotateCW.setObjectName(_fromUtf8("buttonRotateCW"))
        self.horizontalLayout.addWidget(self.buttonRotateCW)
        self.buttonFlipHorizontal = QtGui.QPushButton(self.groupRotationFlip)
        self.buttonFlipHorizontal.setMinimumSize(QtCore.QSize(31, 31))
        self.buttonFlipHorizontal.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.buttonFlipHorizontal.setFont(font)
        self.buttonFlipHorizontal.setObjectName(_fromUtf8("buttonFlipHorizontal"))
        self.horizontalLayout.addWidget(self.buttonFlipHorizontal)
        self.buttonFlipVertical = QtGui.QPushButton(self.groupRotationFlip)
        self.buttonFlipVertical.setMinimumSize(QtCore.QSize(31, 31))
        self.buttonFlipVertical.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.buttonFlipVertical.setFont(font)
        self.buttonFlipVertical.setObjectName(_fromUtf8("buttonFlipVertical"))
        self.horizontalLayout.addWidget(self.buttonFlipVertical)
        self.groupStretchPull = QtGui.QGroupBox(dialogOverlayAdjustment)
        self.groupStretchPull.setGeometry(QtCore.QRect(10, 150, 181, 201))
        self.groupStretchPull.setObjectName(_fromUtf8("groupStretchPull"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupStretchPull)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.buttonStretchLeftUp = QtGui.QPushButton(self.groupStretchPull)
        self.buttonStretchLeftUp.setMinimumSize(QtCore.QSize(31, 31))
        self.buttonStretchLeftUp.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.buttonStretchLeftUp.setFont(font)
        self.buttonStretchLeftUp.setCheckable(True)
        self.buttonStretchLeftUp.setObjectName(_fromUtf8("buttonStretchLeftUp"))
        self.gridLayout_4.addWidget(self.buttonStretchLeftUp, 0, 1, 1, 1)
        self.buttonStretchRightUp = QtGui.QPushButton(self.groupStretchPull)
        self.buttonStretchRightUp.setMinimumSize(QtCore.QSize(31, 31))
        self.buttonStretchRightUp.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.buttonStretchRightUp.setFont(font)
        self.buttonStretchRightUp.setCheckable(True)
        self.buttonStretchRightUp.setObjectName(_fromUtf8("buttonStretchRightUp"))
        self.gridLayout_4.addWidget(self.buttonStretchRightUp, 0, 3, 1, 1)
        self.buttonStretchUpLeft = QtGui.QPushButton(self.groupStretchPull)
        self.buttonStretchUpLeft.setMinimumSize(QtCore.QSize(31, 31))
        self.buttonStretchUpLeft.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.buttonStretchUpLeft.setFont(font)
        self.buttonStretchUpLeft.setCheckable(True)
        self.buttonStretchUpLeft.setObjectName(_fromUtf8("buttonStretchUpLeft"))
        self.gridLayout_4.addWidget(self.buttonStretchUpLeft, 1, 0, 1, 1)
        self.buttonStretchNW = QtGui.QPushButton(self.groupStretchPull)
        self.buttonStretchNW.setMinimumSize(QtCore.QSize(31, 31))
        self.buttonStretchNW.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.buttonStretchNW.setFont(font)
        self.buttonStretchNW.setCheckable(True)
        self.buttonStretchNW.setObjectName(_fromUtf8("buttonStretchNW"))
        self.gridLayout_4.addWidget(self.buttonStretchNW, 1, 1, 1, 1)
        self.buttonStretchN = QtGui.QPushButton(self.groupStretchPull)
        self.buttonStretchN.setMinimumSize(QtCore.QSize(31, 31))
        self.buttonStretchN.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.buttonStretchN.setFont(font)
        self.buttonStretchN.setCheckable(True)
        self.buttonStretchN.setObjectName(_fromUtf8("buttonStretchN"))
        self.gridLayout_4.addWidget(self.buttonStretchN, 1, 2, 1, 1)
        self.buttonStretchNE = QtGui.QPushButton(self.groupStretchPull)
        self.buttonStretchNE.setMinimumSize(QtCore.QSize(31, 31))
        self.buttonStretchNE.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.buttonStretchNE.setFont(font)
        self.buttonStretchNE.setCheckable(True)
        self.buttonStretchNE.setObjectName(_fromUtf8("buttonStretchNE"))
        self.gridLayout_4.addWidget(self.buttonStretchNE, 1, 3, 1, 1)
        self.buttonStretchUpRight = QtGui.QPushButton(self.groupStretchPull)
        self.buttonStretchUpRight.setMinimumSize(QtCore.QSize(31, 31))
        self.buttonStretchUpRight.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.buttonStretchUpRight.setFont(font)
        self.buttonStretchUpRight.setCheckable(True)
        self.buttonStretchUpRight.setObjectName(_fromUtf8("buttonStretchUpRight"))
        self.gridLayout_4.addWidget(self.buttonStretchUpRight, 1, 4, 1, 1)
        self.buttonStretchW = QtGui.QPushButton(self.groupStretchPull)
        self.buttonStretchW.setMinimumSize(QtCore.QSize(31, 31))
        self.buttonStretchW.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.buttonStretchW.setFont(font)
        self.buttonStretchW.setCheckable(True)
        self.buttonStretchW.setObjectName(_fromUtf8("buttonStretchW"))
        self.gridLayout_4.addWidget(self.buttonStretchW, 2, 1, 1, 1)
        self.buttonResetStretch = QtGui.QPushButton(self.groupStretchPull)
        self.buttonResetStretch.setMinimumSize(QtCore.QSize(31, 31))
        self.buttonResetStretch.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.buttonResetStretch.setFont(font)
        self.buttonResetStretch.setCheckable(True)
        self.buttonResetStretch.setObjectName(_fromUtf8("buttonResetStretch"))
        self.gridLayout_4.addWidget(self.buttonResetStretch, 2, 2, 1, 1)
        self.buttonStretchE = QtGui.QPushButton(self.groupStretchPull)
        self.buttonStretchE.setMinimumSize(QtCore.QSize(31, 31))
        self.buttonStretchE.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.buttonStretchE.setFont(font)
        self.buttonStretchE.setCheckable(True)
        self.buttonStretchE.setObjectName(_fromUtf8("buttonStretchE"))
        self.gridLayout_4.addWidget(self.buttonStretchE, 2, 3, 1, 1)
        self.buttonStretchDownLeft = QtGui.QPushButton(self.groupStretchPull)
        self.buttonStretchDownLeft.setMinimumSize(QtCore.QSize(31, 31))
        self.buttonStretchDownLeft.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.buttonStretchDownLeft.setFont(font)
        self.buttonStretchDownLeft.setCheckable(True)
        self.buttonStretchDownLeft.setObjectName(_fromUtf8("buttonStretchDownLeft"))
        self.gridLayout_4.addWidget(self.buttonStretchDownLeft, 3, 0, 1, 1)
        self.buttonStretchSW = QtGui.QPushButton(self.groupStretchPull)
        self.buttonStretchSW.setMinimumSize(QtCore.QSize(31, 31))
        self.buttonStretchSW.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.buttonStretchSW.setFont(font)
        self.buttonStretchSW.setCheckable(True)
        self.buttonStretchSW.setObjectName(_fromUtf8("buttonStretchSW"))
        self.gridLayout_4.addWidget(self.buttonStretchSW, 3, 1, 1, 1)
        self.buttonStretchS = QtGui.QPushButton(self.groupStretchPull)
        self.buttonStretchS.setMinimumSize(QtCore.QSize(31, 31))
        self.buttonStretchS.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.buttonStretchS.setFont(font)
        self.buttonStretchS.setCheckable(True)
        self.buttonStretchS.setObjectName(_fromUtf8("buttonStretchS"))
        self.gridLayout_4.addWidget(self.buttonStretchS, 3, 2, 1, 1)
        self.buttonStretchSE = QtGui.QPushButton(self.groupStretchPull)
        self.buttonStretchSE.setMinimumSize(QtCore.QSize(31, 31))
        self.buttonStretchSE.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.buttonStretchSE.setFont(font)
        self.buttonStretchSE.setCheckable(True)
        self.buttonStretchSE.setObjectName(_fromUtf8("buttonStretchSE"))
        self.gridLayout_4.addWidget(self.buttonStretchSE, 3, 3, 1, 1)
        self.buttonStretchDownRight = QtGui.QPushButton(self.groupStretchPull)
        self.buttonStretchDownRight.setMinimumSize(QtCore.QSize(31, 31))
        self.buttonStretchDownRight.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.buttonStretchDownRight.setFont(font)
        self.buttonStretchDownRight.setCheckable(True)
        self.buttonStretchDownRight.setObjectName(_fromUtf8("buttonStretchDownRight"))
        self.gridLayout_4.addWidget(self.buttonStretchDownRight, 3, 4, 1, 1)
        self.buttonStretchLeftDown = QtGui.QPushButton(self.groupStretchPull)
        self.buttonStretchLeftDown.setMinimumSize(QtCore.QSize(31, 31))
        self.buttonStretchLeftDown.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.buttonStretchLeftDown.setFont(font)
        self.buttonStretchLeftDown.setCheckable(True)
        self.buttonStretchLeftDown.setObjectName(_fromUtf8("buttonStretchLeftDown"))
        self.gridLayout_4.addWidget(self.buttonStretchLeftDown, 4, 1, 1, 1)
        self.buttonStretchRightDown = QtGui.QPushButton(self.groupStretchPull)
        self.buttonStretchRightDown.setMinimumSize(QtCore.QSize(31, 31))
        self.buttonStretchRightDown.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.buttonStretchRightDown.setFont(font)
        self.buttonStretchRightDown.setCheckable(True)
        self.buttonStretchRightDown.setObjectName(_fromUtf8("buttonStretchRightDown"))
        self.gridLayout_4.addWidget(self.buttonStretchRightDown, 4, 3, 1, 1)
        self.groupGeneral = QtGui.QGroupBox(dialogOverlayAdjustment)
        self.groupGeneral.setGeometry(QtCore.QRect(160, 50, 101, 91))
        self.groupGeneral.setObjectName(_fromUtf8("groupGeneral"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupGeneral)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.buttonReset = QtGui.QPushButton(self.groupGeneral)
        self.buttonReset.setEnabled(True)
        self.buttonReset.setMinimumSize(QtCore.QSize(35, 35))
        self.buttonReset.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.buttonReset.setFont(font)
        self.buttonReset.setObjectName(_fromUtf8("buttonReset"))
        self.gridLayout_5.addWidget(self.buttonReset, 0, 0, 1, 1)
        self.buttonUndo = QtGui.QPushButton(self.groupGeneral)
        self.buttonUndo.setMinimumSize(QtCore.QSize(35, 35))
        self.buttonUndo.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.buttonUndo.setFont(font)
        self.buttonUndo.setCheckable(True)
        self.buttonUndo.setObjectName(_fromUtf8("buttonUndo"))
        self.gridLayout_5.addWidget(self.buttonUndo, 0, 1, 1, 1)

        self.retranslateUi(dialogOverlayAdjustment)
        QtCore.QObject.connect(self.buttonDone, QtCore.SIGNAL(_fromUtf8("clicked()")), dialogOverlayAdjustment.close)
        QtCore.QMetaObject.connectSlotsByName(dialogOverlayAdjustment)
        dialogOverlayAdjustment.setTabOrder(self.buttonDone, self.spinPixels)
        dialogOverlayAdjustment.setTabOrder(self.spinPixels, self.spinDegrees)
        dialogOverlayAdjustment.setTabOrder(self.spinDegrees, self.buttonReset)
        dialogOverlayAdjustment.setTabOrder(self.buttonReset, self.buttonUndo)
        dialogOverlayAdjustment.setTabOrder(self.buttonUndo, self.buttonTranslateUp)
        dialogOverlayAdjustment.setTabOrder(self.buttonTranslateUp, self.buttonTranslateDown)
        dialogOverlayAdjustment.setTabOrder(self.buttonTranslateDown, self.buttonTranslateLeft)
        dialogOverlayAdjustment.setTabOrder(self.buttonTranslateLeft, self.buttonTranslateRight)
        dialogOverlayAdjustment.setTabOrder(self.buttonTranslateRight, self.buttonStretchLeftUp)
        dialogOverlayAdjustment.setTabOrder(self.buttonStretchLeftUp, self.buttonStretchRightUp)
        dialogOverlayAdjustment.setTabOrder(self.buttonStretchRightUp, self.buttonStretchUpLeft)
        dialogOverlayAdjustment.setTabOrder(self.buttonStretchUpLeft, self.buttonStretchNW)
        dialogOverlayAdjustment.setTabOrder(self.buttonStretchNW, self.buttonStretchN)
        dialogOverlayAdjustment.setTabOrder(self.buttonStretchN, self.buttonStretchNE)
        dialogOverlayAdjustment.setTabOrder(self.buttonStretchNE, self.buttonStretchUpRight)
        dialogOverlayAdjustment.setTabOrder(self.buttonStretchUpRight, self.buttonStretchW)
        dialogOverlayAdjustment.setTabOrder(self.buttonStretchW, self.buttonResetStretch)
        dialogOverlayAdjustment.setTabOrder(self.buttonResetStretch, self.buttonStretchE)
        dialogOverlayAdjustment.setTabOrder(self.buttonStretchE, self.buttonStretchDownLeft)
        dialogOverlayAdjustment.setTabOrder(self.buttonStretchDownLeft, self.buttonStretchSW)
        dialogOverlayAdjustment.setTabOrder(self.buttonStretchSW, self.buttonStretchSE)
        dialogOverlayAdjustment.setTabOrder(self.buttonStretchSE, self.buttonStretchS)
        dialogOverlayAdjustment.setTabOrder(self.buttonStretchS, self.buttonStretchDownRight)
        dialogOverlayAdjustment.setTabOrder(self.buttonStretchDownRight, self.buttonStretchLeftDown)
        dialogOverlayAdjustment.setTabOrder(self.buttonStretchLeftDown, self.buttonStretchRightDown)
        dialogOverlayAdjustment.setTabOrder(self.buttonStretchRightDown, self.buttonRotateACW)
        dialogOverlayAdjustment.setTabOrder(self.buttonRotateACW, self.buttonRotateCW)
        dialogOverlayAdjustment.setTabOrder(self.buttonRotateCW, self.buttonFlipHorizontal)
        dialogOverlayAdjustment.setTabOrder(self.buttonFlipHorizontal, self.buttonFlipVertical)

    def retranslateUi(self, dialogOverlayAdjustment):
        dialogOverlayAdjustment.setWindowTitle(_translate("dialogOverlayAdjustment", "Overlay Adjustment", None))
        self.labelInformation.setText(_translate("dialogOverlayAdjustment", "This tool allows the user to manipulate the overlay image using a variety of geometric transformation OpenCV tools.", None))
        self.buttonDone.setText(_translate("dialogOverlayAdjustment", "Done", None))
        self.groupValues.setTitle(_translate("dialogOverlayAdjustment", "Values", None))
        self.labelPixels.setText(_translate("dialogOverlayAdjustment", "Pixels", None))
        self.labelDegrees.setText(_translate("dialogOverlayAdjustment", "Degrees", None))
        self.groupTranslation.setTitle(_translate("dialogOverlayAdjustment", "Translation", None))
        self.buttonTranslateUp.setToolTip(_translate("dialogOverlayAdjustment", "Shifts the display image up by the given pixels.", None))
        self.buttonTranslateUp.setText(_translate("dialogOverlayAdjustment", "▲", None))
        self.buttonTranslateDown.setToolTip(_translate("dialogOverlayAdjustment", "Shifts the display image down by the given pixels.", None))
        self.buttonTranslateDown.setText(_translate("dialogOverlayAdjustment", "▼", None))
        self.buttonTranslateLeft.setToolTip(_translate("dialogOverlayAdjustment", "Shifts the display image left by the given pixels.", None))
        self.buttonTranslateLeft.setText(_translate("dialogOverlayAdjustment", "◄", None))
        self.buttonTranslateRight.setToolTip(_translate("dialogOverlayAdjustment", "Shifts the display image right by the given pixels.", None))
        self.buttonTranslateRight.setText(_translate("dialogOverlayAdjustment", "►", None))
        self.groupRotationFlip.setTitle(_translate("dialogOverlayAdjustment", "Rotation / Flip", None))
        self.buttonRotateACW.setToolTip(_translate("dialogOverlayAdjustment", "Clocwise rotates the display image by the given degrees.", None))
        self.buttonRotateACW.setText(_translate("dialogOverlayAdjustment", "↶", None))
        self.buttonRotateCW.setToolTip(_translate("dialogOverlayAdjustment", "Anti-Clocwise rotates the display image by the given degrees.", None))
        self.buttonRotateCW.setText(_translate("dialogOverlayAdjustment", "↷", None))
        self.buttonFlipHorizontal.setToolTip(_translate("dialogOverlayAdjustment", "Clocwise rotates the display image by the given degrees.", None))
        self.buttonFlipHorizontal.setText(_translate("dialogOverlayAdjustment", "↔", None))
        self.buttonFlipVertical.setToolTip(_translate("dialogOverlayAdjustment", "Clocwise rotates the display image by the given degrees.", None))
        self.buttonFlipVertical.setText(_translate("dialogOverlayAdjustment", "↕", None))
        self.groupStretchPull.setTitle(_translate("dialogOverlayAdjustment", "Stretch / Pull", None))
        self.buttonStretchLeftUp.setToolTip(_translate("dialogOverlayAdjustment", "Click to move the crop boundary.", None))
        self.buttonStretchLeftUp.setText(_translate("dialogOverlayAdjustment", "↿", None))
        self.buttonStretchRightUp.setToolTip(_translate("dialogOverlayAdjustment", "Click to move the crop boundary.", None))
        self.buttonStretchRightUp.setText(_translate("dialogOverlayAdjustment", "↾", None))
        self.buttonStretchUpLeft.setToolTip(_translate("dialogOverlayAdjustment", "Click to move the crop boundary.", None))
        self.buttonStretchUpLeft.setText(_translate("dialogOverlayAdjustment", "↼", None))
        self.buttonStretchNW.setToolTip(_translate("dialogOverlayAdjustment", "Click to move the crop boundary.", None))
        self.buttonStretchNW.setText(_translate("dialogOverlayAdjustment", "↖", None))
        self.buttonStretchN.setToolTip(_translate("dialogOverlayAdjustment", "Click to move the overlay boundary.", None))
        self.buttonStretchN.setText(_translate("dialogOverlayAdjustment", "↑", None))
        self.buttonStretchNE.setToolTip(_translate("dialogOverlayAdjustment", "Click to move the crop boundary.", None))
        self.buttonStretchNE.setText(_translate("dialogOverlayAdjustment", "↗ ", None))
        self.buttonStretchUpRight.setToolTip(_translate("dialogOverlayAdjustment", "Click to move the crop boundary.", None))
        self.buttonStretchUpRight.setText(_translate("dialogOverlayAdjustment", "⇀", None))
        self.buttonStretchW.setToolTip(_translate("dialogOverlayAdjustment", "Click to move the crop boundary.", None))
        self.buttonStretchW.setText(_translate("dialogOverlayAdjustment", "←", None))
        self.buttonResetStretch.setToolTip(_translate("dialogOverlayAdjustment", "Click to move the crop boundary.", None))
        self.buttonResetStretch.setText(_translate("dialogOverlayAdjustment", "R", None))
        self.buttonStretchE.setToolTip(_translate("dialogOverlayAdjustment", "Click to move the crop boundary.", None))
        self.buttonStretchE.setText(_translate("dialogOverlayAdjustment", "→", None))
        self.buttonStretchDownLeft.setToolTip(_translate("dialogOverlayAdjustment", "Click to move the crop boundary.", None))
        self.buttonStretchDownLeft.setText(_translate("dialogOverlayAdjustment", "↽", None))
        self.buttonStretchSW.setToolTip(_translate("dialogOverlayAdjustment", "Click to move the crop boundary.", None))
        self.buttonStretchSW.setText(_translate("dialogOverlayAdjustment", "↙", None))
        self.buttonStretchS.setToolTip(_translate("dialogOverlayAdjustment", "Click to move the crop boundary.", None))
        self.buttonStretchS.setText(_translate("dialogOverlayAdjustment", "↓", None))
        self.buttonStretchSE.setToolTip(_translate("dialogOverlayAdjustment", "Click to move the crop boundary.", None))
        self.buttonStretchSE.setText(_translate("dialogOverlayAdjustment", "↘", None))
        self.buttonStretchDownRight.setToolTip(_translate("dialogOverlayAdjustment", "Click to move the crop boundary.", None))
        self.buttonStretchDownRight.setText(_translate("dialogOverlayAdjustment", "⇁", None))
        self.buttonStretchLeftDown.setToolTip(_translate("dialogOverlayAdjustment", "Click to move the crop boundary.", None))
        self.buttonStretchLeftDown.setText(_translate("dialogOverlayAdjustment", "⇃", None))
        self.buttonStretchRightDown.setToolTip(_translate("dialogOverlayAdjustment", "Click to move the crop boundary.", None))
        self.buttonStretchRightDown.setText(_translate("dialogOverlayAdjustment", "⇂", None))
        self.groupGeneral.setTitle(_translate("dialogOverlayAdjustment", "General", None))
        self.buttonReset.setToolTip(_translate("dialogOverlayAdjustment", "Resets the overlay image.", None))
        self.buttonReset.setText(_translate("dialogOverlayAdjustment", "®", None))
        self.buttonUndo.setToolTip(_translate("dialogOverlayAdjustment", "Click to move the crop boundary.", None))
        self.buttonUndo.setText(_translate("dialogOverlayAdjustment", "U", None))

import icons_rc
