# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialogNewBuild.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_dialogNewBuild(object):
    def setupUi(self, dialogNewBuild):
        dialogNewBuild.setObjectName(_fromUtf8("dialogNewBuild"))
        dialogNewBuild.setWindowModality(QtCore.Qt.NonModal)
        dialogNewBuild.resize(411, 469)
        dialogNewBuild.setMinimumSize(QtCore.QSize(411, 469))
        dialogNewBuild.setMaximumSize(QtCore.QSize(411, 469))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/resources/logo.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        dialogNewBuild.setWindowIcon(icon)
        dialogNewBuild.setModal(True)
        self.lineBuildName = QtGui.QLineEdit(dialogNewBuild)
        self.lineBuildName.setGeometry(QtCore.QRect(140, 10, 261, 26))
        self.lineBuildName.setMaxLength(30)
        self.lineBuildName.setObjectName(_fromUtf8("lineBuildName"))
        self.comboPlatform = QtGui.QComboBox(dialogNewBuild)
        self.comboPlatform.setGeometry(QtCore.QRect(140, 44, 261, 26))
        self.comboPlatform.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.comboPlatform.setObjectName(_fromUtf8("comboPlatform"))
        self.comboPlatform.addItem(_fromUtf8(""))
        self.comboPlatform.addItem(_fromUtf8(""))
        self.comboPlatform.addItem(_fromUtf8(""))
        self.labelBuildPlatform = QtGui.QLabel(dialogNewBuild)
        self.labelBuildPlatform.setGeometry(QtCore.QRect(10, 44, 121, 28))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.labelBuildPlatform.setFont(font)
        self.labelBuildPlatform.setObjectName(_fromUtf8("labelBuildPlatform"))
        self.buttonBrowseBF = QtGui.QPushButton(dialogNewBuild)
        self.buttonBrowseBF.setGeometry(QtCore.QRect(310, 214, 91, 28))
        self.buttonBrowseBF.setObjectName(_fromUtf8("buttonBrowseBF"))
        self.labelBuildName = QtGui.QLabel(dialogNewBuild)
        self.labelBuildName.setGeometry(QtCore.QRect(10, 10, 101, 28))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.labelBuildName.setFont(font)
        self.labelBuildName.setObjectName(_fromUtf8("labelBuildName"))
        self.buttonBox = QtGui.QDialogButtonBox(dialogNewBuild)
        self.buttonBox.setEnabled(True)
        self.buttonBox.setGeometry(QtCore.QRect(210, 428, 191, 31))
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.labelCalibrationFile = QtGui.QLabel(dialogNewBuild)
        self.labelCalibrationFile.setGeometry(QtCore.QRect(10, 78, 121, 28))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.labelCalibrationFile.setFont(font)
        self.labelCalibrationFile.setObjectName(_fromUtf8("labelCalibrationFile"))
        self.labelSliceFile = QtGui.QLabel(dialogNewBuild)
        self.labelSliceFile.setGeometry(QtCore.QRect(10, 112, 121, 28))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.labelSliceFile.setFont(font)
        self.labelSliceFile.setObjectName(_fromUtf8("labelSliceFile"))
        self.lineCalibrationFile = QtGui.QLineEdit(dialogNewBuild)
        self.lineCalibrationFile.setGeometry(QtCore.QRect(140, 78, 161, 26))
        self.lineCalibrationFile.setReadOnly(True)
        self.lineCalibrationFile.setObjectName(_fromUtf8("lineCalibrationFile"))
        self.buttonBrowseCF = QtGui.QPushButton(dialogNewBuild)
        self.buttonBrowseCF.setGeometry(QtCore.QRect(310, 77, 91, 28))
        self.buttonBrowseCF.setObjectName(_fromUtf8("buttonBrowseCF"))
        self.buttonBrowseSF = QtGui.QPushButton(dialogNewBuild)
        self.buttonBrowseSF.setGeometry(QtCore.QRect(310, 111, 91, 28))
        self.buttonBrowseSF.setObjectName(_fromUtf8("buttonBrowseSF"))
        self.lineBuildFolder = QtGui.QLineEdit(dialogNewBuild)
        self.lineBuildFolder.setGeometry(QtCore.QRect(10, 214, 291, 26))
        self.lineBuildFolder.setReadOnly(True)
        self.lineBuildFolder.setObjectName(_fromUtf8("lineBuildFolder"))
        self.listSliceFiles = QtGui.QListWidget(dialogNewBuild)
        self.listSliceFiles.setGeometry(QtCore.QRect(140, 110, 161, 96))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.listSliceFiles.setFont(font)
        self.listSliceFiles.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.listSliceFiles.setObjectName(_fromUtf8("listSliceFiles"))
        self.labelBuildFolder = QtGui.QLabel(dialogNewBuild)
        self.labelBuildFolder.setGeometry(QtCore.QRect(10, 180, 121, 28))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.labelBuildFolder.setFont(font)
        self.labelBuildFolder.setObjectName(_fromUtf8("labelBuildFolder"))
        self.labelUsername = QtGui.QLabel(dialogNewBuild)
        self.labelUsername.setGeometry(QtCore.QRect(10, 248, 121, 28))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.labelUsername.setFont(font)
        self.labelUsername.setObjectName(_fromUtf8("labelUsername"))
        self.lineUsername = QtGui.QLineEdit(dialogNewBuild)
        self.lineUsername.setGeometry(QtCore.QRect(140, 248, 261, 26))
        self.lineUsername.setText(_fromUtf8(""))
        self.lineUsername.setMaxLength(52)
        self.lineUsername.setObjectName(_fromUtf8("lineUsername"))
        self.groupNotifications = QtGui.QGroupBox(dialogNewBuild)
        self.groupNotifications.setGeometry(QtCore.QRect(10, 316, 181, 141))
        self.groupNotifications.setObjectName(_fromUtf8("groupNotifications"))
        self.layoutWidget = QtGui.QWidget(self.groupNotifications)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 8, 151, 130))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.checkAll = QtGui.QCheckBox(self.layoutWidget)
        self.checkAll.setObjectName(_fromUtf8("checkAll"))
        self.verticalLayout.addWidget(self.checkAll)
        self.checkMinor = QtGui.QCheckBox(self.layoutWidget)
        self.checkMinor.setObjectName(_fromUtf8("checkMinor"))
        self.verticalLayout.addWidget(self.checkMinor)
        self.checkMajor = QtGui.QCheckBox(self.layoutWidget)
        self.checkMajor.setObjectName(_fromUtf8("checkMajor"))
        self.verticalLayout.addWidget(self.checkMajor)
        self.checkFailure = QtGui.QCheckBox(self.layoutWidget)
        self.checkFailure.setObjectName(_fromUtf8("checkFailure"))
        self.verticalLayout.addWidget(self.checkFailure)
        self.checkError = QtGui.QCheckBox(self.layoutWidget)
        self.checkError.setObjectName(_fromUtf8("checkError"))
        self.verticalLayout.addWidget(self.checkError)
        self.labelEmailAddress = QtGui.QLabel(dialogNewBuild)
        self.labelEmailAddress.setGeometry(QtCore.QRect(10, 282, 121, 28))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.labelEmailAddress.setFont(font)
        self.labelEmailAddress.setObjectName(_fromUtf8("labelEmailAddress"))
        self.lineEmailAddress = QtGui.QLineEdit(dialogNewBuild)
        self.lineEmailAddress.setGeometry(QtCore.QRect(140, 282, 261, 26))
        self.lineEmailAddress.setText(_fromUtf8(""))
        self.lineEmailAddress.setMaxLength(52)
        self.lineEmailAddress.setObjectName(_fromUtf8("lineEmailAddress"))
        self.buttonSendTestEmail = QtGui.QPushButton(dialogNewBuild)
        self.buttonSendTestEmail.setGeometry(QtCore.QRect(210, 316, 191, 27))
        self.buttonSendTestEmail.setObjectName(_fromUtf8("buttonSendTestEmail"))
        self.checkConvert = QtGui.QCheckBox(dialogNewBuild)
        self.checkConvert.setGeometry(QtCore.QRect(320, 146, 81, 28))
        self.checkConvert.setObjectName(_fromUtf8("checkConvert"))

        self.retranslateUi(dialogNewBuild)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), dialogNewBuild.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), dialogNewBuild.reject)
        QtCore.QMetaObject.connectSlotsByName(dialogNewBuild)

    def retranslateUi(self, dialogNewBuild):
        dialogNewBuild.setWindowTitle(_translate("dialogNewBuild", "New Build", None))
        self.lineBuildName.setText(_translate("dialogNewBuild", "Default", None))
        self.comboPlatform.setItemText(0, _translate("dialogNewBuild", "Concept X1000R (636 x 406 mm)", None))
        self.comboPlatform.setItemText(1, _translate("dialogNewBuild", "Concept X2000R (800 x 400 mm)", None))
        self.comboPlatform.setItemText(2, _translate("dialogNewBuild", "EOS M280/M290 (250 x 250 mm)", None))
        self.labelBuildPlatform.setText(_translate("dialogNewBuild", "Build Platform", None))
        self.buttonBrowseBF.setToolTip(_translate("dialogNewBuild", "Select where the captured images for the current build will be stored.", None))
        self.buttonBrowseBF.setText(_translate("dialogNewBuild", "Browse", None))
        self.labelBuildName.setText(_translate("dialogNewBuild", "Build Name", None))
        self.labelCalibrationFile.setText(_translate("dialogNewBuild", "Calibration File", None))
        self.labelSliceFile.setText(_translate("dialogNewBuild", "Slice File(s)", None))
        self.buttonBrowseCF.setToolTip(_translate("dialogNewBuild", "Select the calibration parameters file to be used to process the captured images.", None))
        self.buttonBrowseCF.setText(_translate("dialogNewBuild", "Browse", None))
        self.buttonBrowseSF.setToolTip(_translate("dialogNewBuild", "Select the slice files to be used to draw the part contours.", None))
        self.buttonBrowseSF.setText(_translate("dialogNewBuild", "Browse", None))
        self.labelBuildFolder.setText(_translate("dialogNewBuild", "Build Folder", None))
        self.labelUsername.setText(_translate("dialogNewBuild", "Username", None))
        self.groupNotifications.setTitle(_translate("dialogNewBuild", "Receive Notifications For:", None))
        self.checkAll.setText(_translate("dialogNewBuild", "All", None))
        self.checkMinor.setText(_translate("dialogNewBuild", "Minor Defects", None))
        self.checkMajor.setText(_translate("dialogNewBuild", "Major Defects", None))
        self.checkFailure.setText(_translate("dialogNewBuild", "Capture Failure", None))
        self.checkError.setText(_translate("dialogNewBuild", "Program Error", None))
        self.labelEmailAddress.setText(_translate("dialogNewBuild", "Email Address", None))
        self.buttonSendTestEmail.setText(_translate("dialogNewBuild", "Send Test Email", None))
        self.checkConvert.setToolTip(_translate("dialogNewBuild", "Check this box to convert, draw and save the contours.", None))
        self.checkConvert.setText(_translate("dialogNewBuild", "Convert", None))

import icons_rc
