# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui\dialogCameraSettings.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_dialogCameraSettings(object):
    def setupUi(self, dialogCameraSettings):
        dialogCameraSettings.setObjectName("dialogCameraSettings")
        dialogCameraSettings.resize(277, 199)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/resources/logo.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        dialogCameraSettings.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(dialogCameraSettings)
        self.gridLayout.setObjectName("gridLayout")
        self.spinPacketSize = QtWidgets.QSpinBox(dialogCameraSettings)
        self.spinPacketSize.setMinimum(0)
        self.spinPacketSize.setMaximum(1500)
        self.spinPacketSize.setSingleStep(4)
        self.spinPacketSize.setProperty("value", 500)
        self.spinPacketSize.setObjectName("spinPacketSize")
        self.gridLayout.addWidget(self.spinPacketSize, 2, 2, 1, 2)
        self.labelOption5 = QtWidgets.QLabel(dialogCameraSettings)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelOption5.setFont(font)
        self.labelOption5.setScaledContents(False)
        self.labelOption5.setObjectName("labelOption5")
        self.gridLayout.addWidget(self.labelOption5, 4, 0, 1, 2)
        self.labelOption2 = QtWidgets.QLabel(dialogCameraSettings)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelOption2.setFont(font)
        self.labelOption2.setObjectName("labelOption2")
        self.gridLayout.addWidget(self.labelOption2, 1, 0, 1, 1)
        self.labelOption4 = QtWidgets.QLabel(dialogCameraSettings)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelOption4.setFont(font)
        self.labelOption4.setObjectName("labelOption4")
        self.gridLayout.addWidget(self.labelOption4, 3, 0, 1, 1)
        self.labelOption6 = QtWidgets.QLabel(dialogCameraSettings)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelOption6.setFont(font)
        self.labelOption6.setObjectName("labelOption6")
        self.gridLayout.addWidget(self.labelOption6, 5, 0, 1, 1)
        self.labelOption1 = QtWidgets.QLabel(dialogCameraSettings)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelOption1.setFont(font)
        self.labelOption1.setObjectName("labelOption1")
        self.gridLayout.addWidget(self.labelOption1, 0, 0, 1, 1)
        self.comboPixelFormat = QtWidgets.QComboBox(dialogCameraSettings)
        self.comboPixelFormat.setObjectName("comboPixelFormat")
        self.comboPixelFormat.addItem("")
        self.comboPixelFormat.addItem("")
        self.comboPixelFormat.addItem("")
        self.gridLayout.addWidget(self.comboPixelFormat, 0, 2, 1, 2)
        self.spinExposureTime = QtWidgets.QSpinBox(dialogCameraSettings)
        self.spinExposureTime.setMinimum(35)
        self.spinExposureTime.setMaximum(100000)
        self.spinExposureTime.setProperty("value", 23000)
        self.spinExposureTime.setObjectName("spinExposureTime")
        self.gridLayout.addWidget(self.spinExposureTime, 1, 2, 1, 2)
        self.labelOption3 = QtWidgets.QLabel(dialogCameraSettings)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelOption3.setFont(font)
        self.labelOption3.setObjectName("labelOption3")
        self.gridLayout.addWidget(self.labelOption3, 2, 0, 1, 1)
        self.spinFrameDelay = QtWidgets.QSpinBox(dialogCameraSettings)
        self.spinFrameDelay.setMaximum(10000)
        self.spinFrameDelay.setProperty("value", 1000)
        self.spinFrameDelay.setObjectName("spinFrameDelay")
        self.gridLayout.addWidget(self.spinFrameDelay, 4, 2, 1, 2)
        self.spinTriggerTimeout = QtWidgets.QSpinBox(dialogCameraSettings)
        self.spinTriggerTimeout.setMaximum(60)
        self.spinTriggerTimeout.setProperty("value", 3)
        self.spinTriggerTimeout.setObjectName("spinTriggerTimeout")
        self.gridLayout.addWidget(self.spinTriggerTimeout, 5, 2, 1, 2)
        self.spinInterPacketDelay = QtWidgets.QSpinBox(dialogCameraSettings)
        self.spinInterPacketDelay.setSuffix("")
        self.spinInterPacketDelay.setMaximum(10000)
        self.spinInterPacketDelay.setProperty("value", 6900)
        self.spinInterPacketDelay.setObjectName("spinInterPacketDelay")
        self.gridLayout.addWidget(self.spinInterPacketDelay, 3, 2, 1, 2)
        self.frameButtons = QtWidgets.QFrame(dialogCameraSettings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameButtons.sizePolicy().hasHeightForWidth())
        self.frameButtons.setSizePolicy(sizePolicy)
        self.frameButtons.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameButtons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameButtons.setObjectName("frameButtons")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frameButtons)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushApply = QtWidgets.QPushButton(self.frameButtons)
        self.pushApply.setEnabled(False)
        self.pushApply.setObjectName("pushApply")
        self.horizontalLayout.addWidget(self.pushApply)
        self.pushOK = QtWidgets.QPushButton(self.frameButtons)
        self.pushOK.setObjectName("pushOK")
        self.horizontalLayout.addWidget(self.pushOK)
        self.pushCancel = QtWidgets.QPushButton(self.frameButtons)
        self.pushCancel.setEnabled(True)
        self.pushCancel.setObjectName("pushCancel")
        self.horizontalLayout.addWidget(self.pushCancel)
        self.gridLayout.addWidget(self.frameButtons, 6, 0, 1, 4)

        self.retranslateUi(dialogCameraSettings)
        self.pushOK.clicked.connect(dialogCameraSettings.accept)
        self.pushCancel.clicked.connect(dialogCameraSettings.close)
        QtCore.QMetaObject.connectSlotsByName(dialogCameraSettings)
        dialogCameraSettings.setTabOrder(self.comboPixelFormat, self.spinExposureTime)
        dialogCameraSettings.setTabOrder(self.spinExposureTime, self.spinPacketSize)
        dialogCameraSettings.setTabOrder(self.spinPacketSize, self.spinInterPacketDelay)
        dialogCameraSettings.setTabOrder(self.spinInterPacketDelay, self.spinFrameDelay)
        dialogCameraSettings.setTabOrder(self.spinFrameDelay, self.spinTriggerTimeout)
        dialogCameraSettings.setTabOrder(self.spinTriggerTimeout, self.pushApply)
        dialogCameraSettings.setTabOrder(self.pushApply, self.pushOK)
        dialogCameraSettings.setTabOrder(self.pushOK, self.pushCancel)

    def retranslateUi(self, dialogCameraSettings):
        _translate = QtCore.QCoreApplication.translate
        dialogCameraSettings.setWindowTitle(_translate("dialogCameraSettings", "Camera Settings"))
        self.spinPacketSize.setToolTip(_translate("dialogCameraSettings", "0 - 1,500"))
        self.labelOption5.setToolTip(_translate("dialogCameraSettings", "Sets the frame transfer start delay (in ticks) for the selected stream channel."))
        self.labelOption5.setText(_translate("dialogCameraSettings", "Frame Transmission Delay"))
        self.labelOption2.setToolTip(_translate("dialogCameraSettings", "Directly sets the camera\'s exposure time in microseconds."))
        self.labelOption2.setText(_translate("dialogCameraSettings", "Exposure Time"))
        self.labelOption4.setToolTip(_translate("dialogCameraSettings", "Sets the inter-packet delay (in ticks) for the selected stream channel."))
        self.labelOption4.setText(_translate("dialogCameraSettings", "Inter-Packet Delay"))
        self.labelOption6.setToolTip(_translate("dialogCameraSettings", "Sets how long (in seconds) until the trigger can be triggered again. Timeout starts upon saving the image."))
        self.labelOption6.setText(_translate("dialogCameraSettings", "Trigger Timeout"))
        self.labelOption1.setToolTip(_translate("dialogCameraSettings", "Sets the format of the pixel data transmitted for acquired images."))
        self.labelOption1.setText(_translate("dialogCameraSettings", "Pixel Format"))
        self.comboPixelFormat.setItemText(0, _translate("dialogCameraSettings", "Mono 8"))
        self.comboPixelFormat.setItemText(1, _translate("dialogCameraSettings", "Mono 12"))
        self.comboPixelFormat.setItemText(2, _translate("dialogCameraSettings", "Mono 12 Packed"))
        self.spinExposureTime.setToolTip(_translate("dialogCameraSettings", "0 - 100,000"))
        self.labelOption3.setToolTip(_translate("dialogCameraSettings", "Sets the packet size in bytes for the selected stream channel."))
        self.labelOption3.setText(_translate("dialogCameraSettings", "Packet Size"))
        self.spinFrameDelay.setToolTip(_translate("dialogCameraSettings", "0 - 10,000"))
        self.spinTriggerTimeout.setToolTip(_translate("dialogCameraSettings", "0 - 60"))
        self.spinInterPacketDelay.setToolTip(_translate("dialogCameraSettings", "0 - 10,000"))
        self.pushApply.setText(_translate("dialogCameraSettings", "Apply"))
        self.pushOK.setText(_translate("dialogCameraSettings", "OK"))
        self.pushCancel.setText(_translate("dialogCameraSettings", "Cancel"))

import icons_rc
