# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialogCameraSettings.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_dialogCameraSettings(object):
    def setupUi(self, dialogCameraSettings):
        dialogCameraSettings.setObjectName(_fromUtf8("dialogCameraSettings"))
        dialogCameraSettings.setWindowModality(QtCore.Qt.NonModal)
        dialogCameraSettings.resize(311, 371)
        dialogCameraSettings.setMinimumSize(QtCore.QSize(311, 371))
        dialogCameraSettings.setMaximumSize(QtCore.QSize(311, 371))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/resources/logo.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        dialogCameraSettings.setWindowIcon(icon)
        dialogCameraSettings.setModal(True)
        self.buttonBox = QtGui.QDialogButtonBox(dialogCameraSettings)
        self.buttonBox.setGeometry(QtCore.QRect(110, 330, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.buttonBox.setFont(font)
        self.buttonBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.buttonApply = QtGui.QPushButton(dialogCameraSettings)
        self.buttonApply.setEnabled(False)
        self.buttonApply.setGeometry(QtCore.QRect(10, 331, 92, 28))
        self.buttonApply.setObjectName(_fromUtf8("buttonApply"))
        self.widget = QtGui.QWidget(dialogCameraSettings)
        self.widget.setGeometry(QtCore.QRect(10, 10, 291, 201))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayout = QtGui.QGridLayout(self.widget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label2 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label2.setFont(font)
        self.label2.setObjectName(_fromUtf8("label2"))
        self.gridLayout.addWidget(self.label2, 1, 0, 1, 1)
        self.comboPixelFormat = QtGui.QComboBox(self.widget)
        self.comboPixelFormat.setObjectName(_fromUtf8("comboPixelFormat"))
        self.comboPixelFormat.addItem(_fromUtf8(""))
        self.comboPixelFormat.addItem(_fromUtf8(""))
        self.comboPixelFormat.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboPixelFormat, 0, 1, 1, 1)
        self.label1 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label1.setFont(font)
        self.label1.setObjectName(_fromUtf8("label1"))
        self.gridLayout.addWidget(self.label1, 0, 0, 1, 1)
        self.label5 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label5.setFont(font)
        self.label5.setObjectName(_fromUtf8("label5"))
        self.gridLayout.addWidget(self.label5, 4, 0, 1, 1)
        self.label4 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label4.setFont(font)
        self.label4.setObjectName(_fromUtf8("label4"))
        self.gridLayout.addWidget(self.label4, 3, 0, 1, 1)
        self.label7 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label7.setFont(font)
        self.label7.setObjectName(_fromUtf8("label7"))
        self.gridLayout.addWidget(self.label7, 6, 0, 1, 1)
        self.label6 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label6.setFont(font)
        self.label6.setObjectName(_fromUtf8("label6"))
        self.gridLayout.addWidget(self.label6, 5, 0, 1, 1)
        self.comboTriggerSelector = QtGui.QComboBox(self.widget)
        self.comboTriggerSelector.setObjectName(_fromUtf8("comboTriggerSelector"))
        self.comboTriggerSelector.addItem(_fromUtf8(""))
        self.comboTriggerSelector.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboTriggerSelector, 1, 1, 1, 1)
        self.comboTriggerMode = QtGui.QComboBox(self.widget)
        self.comboTriggerMode.setObjectName(_fromUtf8("comboTriggerMode"))
        self.comboTriggerMode.addItem(_fromUtf8(""))
        self.comboTriggerMode.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboTriggerMode, 2, 1, 1, 1)
        self.comboTriggerSource = QtGui.QComboBox(self.widget)
        self.comboTriggerSource.setObjectName(_fromUtf8("comboTriggerSource"))
        self.comboTriggerSource.addItem(_fromUtf8(""))
        self.comboTriggerSource.addItem(_fromUtf8(""))
        self.comboTriggerSource.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboTriggerSource, 3, 1, 1, 1)
        self.comboTriggerActivation = QtGui.QComboBox(self.widget)
        self.comboTriggerActivation.setObjectName(_fromUtf8("comboTriggerActivation"))
        self.comboTriggerActivation.addItem(_fromUtf8(""))
        self.comboTriggerActivation.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboTriggerActivation, 4, 1, 1, 1)
        self.label3 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label3.setFont(font)
        self.label3.setObjectName(_fromUtf8("label3"))
        self.gridLayout.addWidget(self.label3, 2, 0, 1, 1)
        self.lineExposureTime = QtGui.QLineEdit(self.widget)
        self.lineExposureTime.setInputMask(_fromUtf8(""))
        self.lineExposureTime.setObjectName(_fromUtf8("lineExposureTime"))
        self.gridLayout.addWidget(self.lineExposureTime, 5, 1, 1, 1)
        self.spinAcquisitionFC = QtGui.QSpinBox(self.widget)
        self.spinAcquisitionFC.setMinimum(1)
        self.spinAcquisitionFC.setMaximum(255)
        self.spinAcquisitionFC.setObjectName(_fromUtf8("spinAcquisitionFC"))
        self.gridLayout.addWidget(self.spinAcquisitionFC, 6, 1, 1, 1)

        self.retranslateUi(dialogCameraSettings)
        self.comboTriggerSource.setCurrentIndex(1)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), dialogCameraSettings.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), dialogCameraSettings.reject)
        QtCore.QMetaObject.connectSlotsByName(dialogCameraSettings)

    def retranslateUi(self, dialogCameraSettings):
        dialogCameraSettings.setWindowTitle(_translate("dialogCameraSettings", "Camera Settings", None))
        self.buttonApply.setText(_translate("dialogCameraSettings", "Apply", None))
        self.label2.setText(_translate("dialogCameraSettings", "Trigger Selector", None))
        self.comboPixelFormat.setItemText(0, _translate("dialogCameraSettings", "Mono 8", None))
        self.comboPixelFormat.setItemText(1, _translate("dialogCameraSettings", "Mono 12", None))
        self.comboPixelFormat.setItemText(2, _translate("dialogCameraSettings", "Mono 12 Packed", None))
        self.label1.setText(_translate("dialogCameraSettings", "Pixel Format", None))
        self.label5.setText(_translate("dialogCameraSettings", "Trigger Activation", None))
        self.label4.setText(_translate("dialogCameraSettings", "Trigger Source", None))
        self.label7.setText(_translate("dialogCameraSettings", "Acquisition Frame Count", None))
        self.label6.setText(_translate("dialogCameraSettings", "Exposure Time", None))
        self.comboTriggerSelector.setItemText(0, _translate("dialogCameraSettings", "Acquisition Start", None))
        self.comboTriggerSelector.setItemText(1, _translate("dialogCameraSettings", "Frame Start", None))
        self.comboTriggerMode.setItemText(0, _translate("dialogCameraSettings", "Off", None))
        self.comboTriggerMode.setItemText(1, _translate("dialogCameraSettings", "On", None))
        self.comboTriggerSource.setItemText(0, _translate("dialogCameraSettings", "Trigger Software", None))
        self.comboTriggerSource.setItemText(1, _translate("dialogCameraSettings", "Line 1", None))
        self.comboTriggerSource.setItemText(2, _translate("dialogCameraSettings", "Action 1", None))
        self.comboTriggerActivation.setItemText(0, _translate("dialogCameraSettings", "Rising Edge", None))
        self.comboTriggerActivation.setItemText(1, _translate("dialogCameraSettings", "Falling Edge", None))
        self.label3.setText(_translate("dialogCameraSettings", "Trigger Mode", None))
        self.lineExposureTime.setText(_translate("dialogCameraSettings", "23000.0", None))

import icons_rc
