# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui\dialogCalibrationResults.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_dialogCalibrationResults(object):
    def setupUi(self, dialogCalibrationResults):
        dialogCalibrationResults.setObjectName("dialogCalibrationResults")
        dialogCalibrationResults.resize(411, 408)
        dialogCalibrationResults.setMinimumSize(QtCore.QSize(411, 408))
        dialogCalibrationResults.setMaximumSize(QtCore.QSize(411, 408))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("logo.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        dialogCalibrationResults.setWindowIcon(icon)
        self.buttonDone = QtWidgets.QPushButton(dialogCalibrationResults)
        self.buttonDone.setGeometry(QtCore.QRect(310, 370, 91, 28))
        self.buttonDone.setObjectName("buttonDone")
        self.labelRMS = QtWidgets.QLabel(dialogCalibrationResults)
        self.labelRMS.setGeometry(QtCore.QRect(10, 370, 271, 28))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.labelRMS.setFont(font)
        self.labelRMS.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelRMS.setObjectName("labelRMS")
        self.tableCameraMatrix = QtWidgets.QTableWidget(dialogCalibrationResults)
        self.tableCameraMatrix.setEnabled(True)
        self.tableCameraMatrix.setGeometry(QtCore.QRect(10, 40, 391, 91))
        self.tableCameraMatrix.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableCameraMatrix.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableCameraMatrix.setAutoScroll(False)
        self.tableCameraMatrix.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableCameraMatrix.setShowGrid(True)
        self.tableCameraMatrix.setWordWrap(True)
        self.tableCameraMatrix.setCornerButtonEnabled(True)
        self.tableCameraMatrix.setRowCount(3)
        self.tableCameraMatrix.setColumnCount(3)
        self.tableCameraMatrix.setObjectName("tableCameraMatrix")
        item = QtWidgets.QTableWidgetItem()
        self.tableCameraMatrix.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableCameraMatrix.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableCameraMatrix.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableCameraMatrix.setItem(0, 0, item)
        self.tableCameraMatrix.horizontalHeader().setVisible(False)
        self.tableCameraMatrix.verticalHeader().setVisible(False)
        self.tableCameraMatrix.verticalHeader().setDefaultSectionSize(30)
        self.labelCameraMatrix = QtWidgets.QLabel(dialogCalibrationResults)
        self.labelCameraMatrix.setGeometry(QtCore.QRect(10, 0, 391, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.labelCameraMatrix.setFont(font)
        self.labelCameraMatrix.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCameraMatrix.setObjectName("labelCameraMatrix")
        self.labelDistortionCoefficients = QtWidgets.QLabel(dialogCalibrationResults)
        self.labelDistortionCoefficients.setGeometry(QtCore.QRect(10, 130, 391, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.labelDistortionCoefficients.setFont(font)
        self.labelDistortionCoefficients.setAlignment(QtCore.Qt.AlignCenter)
        self.labelDistortionCoefficients.setObjectName("labelDistortionCoefficients")
        self.tableDistortionCoefficients = QtWidgets.QTableWidget(dialogCalibrationResults)
        self.tableDistortionCoefficients.setEnabled(True)
        self.tableDistortionCoefficients.setGeometry(QtCore.QRect(10, 170, 391, 61))
        self.tableDistortionCoefficients.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableDistortionCoefficients.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableDistortionCoefficients.setAutoScroll(False)
        self.tableDistortionCoefficients.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableDistortionCoefficients.setShowGrid(True)
        self.tableDistortionCoefficients.setWordWrap(True)
        self.tableDistortionCoefficients.setCornerButtonEnabled(True)
        self.tableDistortionCoefficients.setRowCount(2)
        self.tableDistortionCoefficients.setColumnCount(3)
        self.tableDistortionCoefficients.setObjectName("tableDistortionCoefficients")
        item = QtWidgets.QTableWidgetItem()
        self.tableDistortionCoefficients.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableDistortionCoefficients.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableDistortionCoefficients.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableDistortionCoefficients.setItem(0, 0, item)
        self.tableDistortionCoefficients.horizontalHeader().setVisible(False)
        self.tableDistortionCoefficients.verticalHeader().setVisible(False)
        self.tableDistortionCoefficients.verticalHeader().setDefaultSectionSize(30)
        self.labelHomographyMatrix = QtWidgets.QLabel(dialogCalibrationResults)
        self.labelHomographyMatrix.setGeometry(QtCore.QRect(10, 230, 391, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.labelHomographyMatrix.setFont(font)
        self.labelHomographyMatrix.setAlignment(QtCore.Qt.AlignCenter)
        self.labelHomographyMatrix.setObjectName("labelHomographyMatrix")
        self.tableHomographyMatrix = QtWidgets.QTableWidget(dialogCalibrationResults)
        self.tableHomographyMatrix.setEnabled(True)
        self.tableHomographyMatrix.setGeometry(QtCore.QRect(10, 270, 391, 91))
        self.tableHomographyMatrix.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableHomographyMatrix.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableHomographyMatrix.setAutoScroll(False)
        self.tableHomographyMatrix.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableHomographyMatrix.setShowGrid(True)
        self.tableHomographyMatrix.setWordWrap(True)
        self.tableHomographyMatrix.setCornerButtonEnabled(True)
        self.tableHomographyMatrix.setRowCount(3)
        self.tableHomographyMatrix.setColumnCount(3)
        self.tableHomographyMatrix.setObjectName("tableHomographyMatrix")
        item = QtWidgets.QTableWidgetItem()
        self.tableHomographyMatrix.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableHomographyMatrix.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableHomographyMatrix.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableHomographyMatrix.setItem(0, 0, item)
        self.tableHomographyMatrix.horizontalHeader().setVisible(False)
        self.tableHomographyMatrix.verticalHeader().setVisible(False)
        self.tableHomographyMatrix.verticalHeader().setDefaultSectionSize(30)

        self.retranslateUi(dialogCalibrationResults)
        self.buttonDone.clicked.connect(dialogCalibrationResults.close)
        QtCore.QMetaObject.connectSlotsByName(dialogCalibrationResults)

    def retranslateUi(self, dialogCalibrationResults):
        _translate = QtCore.QCoreApplication.translate
        dialogCalibrationResults.setWindowTitle(_translate("dialogCalibrationResults", "Calibration Results"))
        self.buttonDone.setText(_translate("dialogCalibrationResults", "Done"))
        self.labelRMS.setToolTip(_translate("dialogCalibrationResults", "An acceptable error should be less than 1 pixel."))
        self.labelRMS.setText(_translate("dialogCalibrationResults", "Re-Projection Error: 0.000000000"))
        item = self.tableCameraMatrix.horizontalHeaderItem(0)
        item.setText(_translate("dialogCalibrationResults", "1"))
        item = self.tableCameraMatrix.horizontalHeaderItem(1)
        item.setText(_translate("dialogCalibrationResults", "2"))
        item = self.tableCameraMatrix.horizontalHeaderItem(2)
        item.setText(_translate("dialogCalibrationResults", "3"))
        __sortingEnabled = self.tableCameraMatrix.isSortingEnabled()
        self.tableCameraMatrix.setSortingEnabled(False)
        self.tableCameraMatrix.setSortingEnabled(__sortingEnabled)
        self.labelCameraMatrix.setText(_translate("dialogCalibrationResults", "Camera Matrix"))
        self.labelDistortionCoefficients.setText(_translate("dialogCalibrationResults", "Distortion Coefficients"))
        item = self.tableDistortionCoefficients.horizontalHeaderItem(0)
        item.setText(_translate("dialogCalibrationResults", "1"))
        item = self.tableDistortionCoefficients.horizontalHeaderItem(1)
        item.setText(_translate("dialogCalibrationResults", "2"))
        item = self.tableDistortionCoefficients.horizontalHeaderItem(2)
        item.setText(_translate("dialogCalibrationResults", "3"))
        __sortingEnabled = self.tableDistortionCoefficients.isSortingEnabled()
        self.tableDistortionCoefficients.setSortingEnabled(False)
        self.tableDistortionCoefficients.setSortingEnabled(__sortingEnabled)
        self.labelHomographyMatrix.setText(_translate("dialogCalibrationResults", "Homography Matrix"))
        item = self.tableHomographyMatrix.horizontalHeaderItem(0)
        item.setText(_translate("dialogCalibrationResults", "1"))
        item = self.tableHomographyMatrix.horizontalHeaderItem(1)
        item.setText(_translate("dialogCalibrationResults", "2"))
        item = self.tableHomographyMatrix.horizontalHeaderItem(2)
        item.setText(_translate("dialogCalibrationResults", "3"))
        __sortingEnabled = self.tableHomographyMatrix.isSortingEnabled()
        self.tableHomographyMatrix.setSortingEnabled(False)
        self.tableHomographyMatrix.setSortingEnabled(__sortingEnabled)

