# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui\dialogCameraCalibration.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_dialogCameraCalibration(object):
    def setupUi(self, dialogCameraCalibration):
        dialogCameraCalibration.setObjectName("dialogCameraCalibration")
        dialogCameraCalibration.resize(411, 646)
        dialogCameraCalibration.setMinimumSize(QtCore.QSize(411, 646))
        dialogCameraCalibration.setMaximumSize(QtCore.QSize(411, 646))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("logo.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        dialogCameraCalibration.setWindowIcon(icon)
        self.labelInformation = QtWidgets.QLabel(dialogCameraCalibration)
        self.labelInformation.setGeometry(QtCore.QRect(10, 10, 391, 81))
        self.labelInformation.setScaledContents(False)
        self.labelInformation.setWordWrap(True)
        self.labelInformation.setObjectName("labelInformation")
        self.buttonBrowseF = QtWidgets.QPushButton(dialogCameraCalibration)
        self.buttonBrowseF.setGeometry(QtCore.QRect(310, 99, 91, 28))
        self.buttonBrowseF.setObjectName("buttonBrowseF")
        self.buttonStart = QtWidgets.QPushButton(dialogCameraCalibration)
        self.buttonStart.setEnabled(False)
        self.buttonStart.setGeometry(QtCore.QRect(10, 608, 91, 28))
        self.buttonStart.setObjectName("buttonStart")
        self.buttonDone = QtWidgets.QPushButton(dialogCameraCalibration)
        self.buttonDone.setGeometry(QtCore.QRect(310, 608, 91, 28))
        self.buttonDone.setObjectName("buttonDone")
        self.progressBar = QtWidgets.QProgressBar(dialogCameraCalibration)
        self.progressBar.setGeometry(QtCore.QRect(10, 438, 391, 28))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setTextVisible(True)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName("progressBar")
        self.labelStatus = QtWidgets.QLabel(dialogCameraCalibration)
        self.labelStatus.setGeometry(QtCore.QRect(10, 404, 391, 28))
        self.labelStatus.setAlignment(QtCore.Qt.AlignCenter)
        self.labelStatus.setObjectName("labelStatus")
        self.labelImages = QtWidgets.QLabel(dialogCameraCalibration)
        self.labelImages.setGeometry(QtCore.QRect(10, 130, 221, 21))
        self.labelImages.setObjectName("labelImages")
        self.listImages = QtWidgets.QListWidget(dialogCameraCalibration)
        self.listImages.setGeometry(QtCore.QRect(10, 150, 391, 181))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.listImages.setFont(font)
        self.listImages.setObjectName("listImages")
        self.label1 = QtWidgets.QLabel(dialogCameraCalibration)
        self.label1.setGeometry(QtCore.QRect(11, 472, 391, 28))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label1.setFont(font)
        self.label1.setAlignment(QtCore.Qt.AlignCenter)
        self.label1.setObjectName("label1")
        self.label2 = QtWidgets.QLabel(dialogCameraCalibration)
        self.label2.setGeometry(QtCore.QRect(11, 506, 141, 28))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label2.setFont(font)
        self.label2.setObjectName("label2")
        self.label3 = QtWidgets.QLabel(dialogCameraCalibration)
        self.label3.setGeometry(QtCore.QRect(11, 540, 141, 28))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label3.setFont(font)
        self.label3.setObjectName("label3")
        self.label4 = QtWidgets.QLabel(dialogCameraCalibration)
        self.label4.setGeometry(QtCore.QRect(11, 574, 141, 28))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label4.setFont(font)
        self.label4.setObjectName("label4")
        self.spinWidth = QtWidgets.QSpinBox(dialogCameraCalibration)
        self.spinWidth.setGeometry(QtCore.QRect(160, 507, 41, 26))
        self.spinWidth.setMinimum(1)
        self.spinWidth.setMaximum(20)
        self.spinWidth.setProperty("value", 9)
        self.spinWidth.setObjectName("spinWidth")
        self.spinHeight = QtWidgets.QSpinBox(dialogCameraCalibration)
        self.spinHeight.setGeometry(QtCore.QRect(160, 541, 41, 26))
        self.spinHeight.setMinimum(1)
        self.spinHeight.setMaximum(20)
        self.spinHeight.setProperty("value", 7)
        self.spinHeight.setObjectName("spinHeight")
        self.spinRatio = QtWidgets.QSpinBox(dialogCameraCalibration)
        self.spinRatio.setGeometry(QtCore.QRect(160, 575, 41, 26))
        self.spinRatio.setMinimum(1)
        self.spinRatio.setMaximum(4)
        self.spinRatio.setProperty("value", 2)
        self.spinRatio.setObjectName("spinRatio")
        self.lineCalibrationFolder = QtWidgets.QLineEdit(dialogCameraCalibration)
        self.lineCalibrationFolder.setGeometry(QtCore.QRect(10, 100, 291, 26))
        self.lineCalibrationFolder.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineCalibrationFolder.setReadOnly(True)
        self.lineCalibrationFolder.setObjectName("lineCalibrationFolder")
        self.checkSaveC = QtWidgets.QCheckBox(dialogCameraCalibration)
        self.checkSaveC.setGeometry(QtCore.QRect(210, 506, 191, 28))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.checkSaveC.setFont(font)
        self.checkSaveC.setObjectName("checkSaveC")
        self.checkApply = QtWidgets.QCheckBox(dialogCameraCalibration)
        self.checkApply.setGeometry(QtCore.QRect(210, 574, 191, 28))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.checkApply.setFont(font)
        self.checkApply.setObjectName("checkApply")
        self.checkSaveU = QtWidgets.QCheckBox(dialogCameraCalibration)
        self.checkSaveU.setGeometry(QtCore.QRect(210, 540, 191, 28))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.checkSaveU.setFont(font)
        self.checkSaveU.setObjectName("checkSaveU")
        self.buttonResults = QtWidgets.QPushButton(dialogCameraCalibration)
        self.buttonResults.setGeometry(QtCore.QRect(110, 608, 91, 28))
        self.buttonResults.setObjectName("buttonResults")
        self.buttonBrowseHI = QtWidgets.QPushButton(dialogCameraCalibration)
        self.buttonBrowseHI.setGeometry(QtCore.QRect(310, 335, 91, 28))
        self.buttonBrowseHI.setObjectName("buttonBrowseHI")
        self.lineHomographyImage = QtWidgets.QLineEdit(dialogCameraCalibration)
        self.lineHomographyImage.setGeometry(QtCore.QRect(100, 336, 201, 26))
        self.lineHomographyImage.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineHomographyImage.setReadOnly(True)
        self.lineHomographyImage.setObjectName("lineHomographyImage")
        self.label5 = QtWidgets.QLabel(dialogCameraCalibration)
        self.label5.setGeometry(QtCore.QRect(10, 336, 91, 28))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label5.setFont(font)
        self.label5.setObjectName("label5")
        self.label6 = QtWidgets.QLabel(dialogCameraCalibration)
        self.label6.setGeometry(QtCore.QRect(10, 370, 91, 28))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label6.setFont(font)
        self.label6.setObjectName("label6")
        self.lineTestImage = QtWidgets.QLineEdit(dialogCameraCalibration)
        self.lineTestImage.setGeometry(QtCore.QRect(100, 370, 201, 26))
        self.lineTestImage.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineTestImage.setReadOnly(True)
        self.lineTestImage.setObjectName("lineTestImage")
        self.buttonBrowseTI = QtWidgets.QPushButton(dialogCameraCalibration)
        self.buttonBrowseTI.setGeometry(QtCore.QRect(310, 369, 91, 28))
        self.buttonBrowseTI.setObjectName("buttonBrowseTI")
        self.buttonSave = QtWidgets.QPushButton(dialogCameraCalibration)
        self.buttonSave.setEnabled(False)
        self.buttonSave.setGeometry(QtCore.QRect(210, 608, 91, 28))
        self.buttonSave.setObjectName("buttonSave")

        self.retranslateUi(dialogCameraCalibration)
        self.buttonDone.clicked.connect(dialogCameraCalibration.close)
        QtCore.QMetaObject.connectSlotsByName(dialogCameraCalibration)
        dialogCameraCalibration.setTabOrder(self.buttonBrowseF, self.listImages)
        dialogCameraCalibration.setTabOrder(self.listImages, self.spinWidth)
        dialogCameraCalibration.setTabOrder(self.spinWidth, self.spinHeight)
        dialogCameraCalibration.setTabOrder(self.spinHeight, self.spinRatio)
        dialogCameraCalibration.setTabOrder(self.spinRatio, self.checkSaveC)
        dialogCameraCalibration.setTabOrder(self.checkSaveC, self.checkSaveU)
        dialogCameraCalibration.setTabOrder(self.checkSaveU, self.checkApply)
        dialogCameraCalibration.setTabOrder(self.checkApply, self.buttonStart)
        dialogCameraCalibration.setTabOrder(self.buttonStart, self.buttonResults)
        dialogCameraCalibration.setTabOrder(self.buttonResults, self.buttonDone)

    def retranslateUi(self, dialogCameraCalibration):
        _translate = QtCore.QCoreApplication.translate
        dialogCameraCalibration.setWindowTitle(_translate("dialogCameraCalibration", "Camera Calibration"))
        self.labelInformation.setText(_translate("dialogCameraCalibration", "To calibrate the camera, please select the folder containing your checkboard images. To determine the most accurate camera parameters, please provide at least 10 images. Calibration images must contain the word \"image_calibration\" in the file name, and will be displayed below."))
        self.buttonBrowseF.setText(_translate("dialogCameraCalibration", "Browse..."))
        self.buttonStart.setText(_translate("dialogCameraCalibration", "Start"))
        self.buttonDone.setText(_translate("dialogCameraCalibration", "Done"))
        self.labelStatus.setText(_translate("dialogCameraCalibration", "Waiting to start process."))
        self.labelImages.setText(_translate("dialogCameraCalibration", "List of images:"))
        self.label1.setText(_translate("dialogCameraCalibration", "Calibration Settings"))
        self.label2.setToolTip(_translate("dialogCameraCalibration", "Sets the number of square corners the width of the chessboard has."))
        self.label2.setText(_translate("dialogCameraCalibration", "Chessboard Width"))
        self.label3.setToolTip(_translate("dialogCameraCalibration", "Sets the number of square corners the height of the chessboard has."))
        self.label3.setText(_translate("dialogCameraCalibration", "Chessboard Height"))
        self.label4.setToolTip(_translate("dialogCameraCalibration", "Sets the downscaling ratio to use to speed up calibration."))
        self.label4.setText(_translate("dialogCameraCalibration", "Downscaling Ratio"))
        self.spinWidth.setToolTip(_translate("dialogCameraCalibration", "1 - 20"))
        self.spinHeight.setToolTip(_translate("dialogCameraCalibration", "1 - 20"))
        self.spinRatio.setToolTip(_translate("dialogCameraCalibration", "1 - 4"))
        self.checkSaveC.setToolTip(_translate("dialogCameraCalibration", "Check to save drawn chessboard corner calibration images to the corners folder."))
        self.checkSaveC.setText(_translate("dialogCameraCalibration", "Save Chessboard Images"))
        self.checkApply.setToolTip(_translate("dialogCameraCalibration", "Check to apply found camera matrix, distortion coefficient and homography matrix processing to the sample image."))
        self.checkApply.setText(_translate("dialogCameraCalibration", "Apply to Test Image"))
        self.checkSaveU.setToolTip(_translate("dialogCameraCalibration", "Check to save undistorted calibration images to the undistorted folder."))
        self.checkSaveU.setText(_translate("dialogCameraCalibration", "Save Undistorted Images"))
        self.buttonResults.setText(_translate("dialogCameraCalibration", "View Results"))
        self.buttonBrowseHI.setText(_translate("dialogCameraCalibration", "Browse..."))
        self.label5.setToolTip(_translate("dialogCameraCalibration", "Select the image to be used to calculate the homography image."))
        self.label5.setText(_translate("dialogCameraCalibration", "Homography"))
        self.label6.setToolTip(_translate("dialogCameraCalibration", "Select the image to be used to test the calculated calibration results."))
        self.label6.setText(_translate("dialogCameraCalibration", "Test Image"))
        self.buttonBrowseTI.setText(_translate("dialogCameraCalibration", "Browse..."))
        self.buttonSave.setText(_translate("dialogCameraCalibration", "Save Results"))

