# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui\dialogImageConverter.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_dialogImageConverter(object):
    def setupUi(self, dialogImageConverter):
        dialogImageConverter.setObjectName("dialogImageConverter")
        dialogImageConverter.resize(245, 307)
        self.gridLayout = QtWidgets.QGridLayout(dialogImageConverter)
        self.gridLayout.setObjectName("gridLayout")
        self.labelStatus = QtWidgets.QLabel(dialogImageConverter)
        self.labelStatus.setAlignment(QtCore.Qt.AlignCenter)
        self.labelStatus.setObjectName("labelStatus")
        self.gridLayout.addWidget(self.labelStatus, 5, 0, 1, 3)
        self.progressBar = QtWidgets.QProgressBar(dialogImageConverter)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 6, 0, 1, 3)
        self.pushBrowse = QtWidgets.QPushButton(dialogImageConverter)
        self.pushBrowse.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushBrowse.setObjectName("pushBrowse")
        self.gridLayout.addWidget(self.pushBrowse, 0, 2, 1, 1)
        self.pushDone = QtWidgets.QPushButton(dialogImageConverter)
        self.pushDone.setObjectName("pushDone")
        self.gridLayout.addWidget(self.pushDone, 7, 2, 1, 1)
        self.pushStart = QtWidgets.QPushButton(dialogImageConverter)
        self.pushStart.setEnabled(False)
        self.pushStart.setObjectName("pushStart")
        self.gridLayout.addWidget(self.pushStart, 7, 0, 1, 2)
        self.checkAlternate = QtWidgets.QCheckBox(dialogImageConverter)
        self.checkAlternate.setEnabled(False)
        self.checkAlternate.setObjectName("checkAlternate")
        self.gridLayout.addWidget(self.checkAlternate, 4, 0, 1, 3)
        self.checkSave = QtWidgets.QCheckBox(dialogImageConverter)
        self.checkSave.setEnabled(False)
        self.checkSave.setObjectName("checkSave")
        self.gridLayout.addWidget(self.checkSave, 3, 0, 1, 3)
        self.listImages = QtWidgets.QListWidget(dialogImageConverter)
        self.listImages.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.listImages.setObjectName("listImages")
        self.gridLayout.addWidget(self.listImages, 0, 0, 3, 2)
        self.groupImagesSave = QtWidgets.QGroupBox(dialogImageConverter)
        self.groupImagesSave.setEnabled(False)
        self.groupImagesSave.setObjectName("groupImagesSave")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupImagesSave)
        self.verticalLayout.setContentsMargins(-1, 3, -1, 6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkToggleAll = QtWidgets.QCheckBox(self.groupImagesSave)
        self.checkToggleAll.setObjectName("checkToggleAll")
        self.verticalLayout.addWidget(self.checkToggleAll)
        self.checkUndistort = QtWidgets.QCheckBox(self.groupImagesSave)
        self.checkUndistort.setObjectName("checkUndistort")
        self.verticalLayout.addWidget(self.checkUndistort)
        self.checkPerspective = QtWidgets.QCheckBox(self.groupImagesSave)
        self.checkPerspective.setObjectName("checkPerspective")
        self.verticalLayout.addWidget(self.checkPerspective)
        self.checkCrop = QtWidgets.QCheckBox(self.groupImagesSave)
        self.checkCrop.setObjectName("checkCrop")
        self.verticalLayout.addWidget(self.checkCrop)
        self.checkEqualization = QtWidgets.QCheckBox(self.groupImagesSave)
        self.checkEqualization.setObjectName("checkEqualization")
        self.verticalLayout.addWidget(self.checkEqualization)
        self.gridLayout.addWidget(self.groupImagesSave, 1, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 2, 2, 1, 1)

        self.retranslateUi(dialogImageConverter)
        self.checkCrop.toggled['bool'].connect(self.checkAlternate.setEnabled)
        self.pushDone.clicked.connect(dialogImageConverter.close)
        QtCore.QMetaObject.connectSlotsByName(dialogImageConverter)
        dialogImageConverter.setTabOrder(self.listImages, self.pushBrowse)
        dialogImageConverter.setTabOrder(self.pushBrowse, self.checkToggleAll)
        dialogImageConverter.setTabOrder(self.checkToggleAll, self.checkUndistort)
        dialogImageConverter.setTabOrder(self.checkUndistort, self.checkPerspective)
        dialogImageConverter.setTabOrder(self.checkPerspective, self.checkCrop)
        dialogImageConverter.setTabOrder(self.checkCrop, self.checkEqualization)
        dialogImageConverter.setTabOrder(self.checkEqualization, self.checkSave)
        dialogImageConverter.setTabOrder(self.checkSave, self.checkAlternate)
        dialogImageConverter.setTabOrder(self.checkAlternate, self.pushStart)
        dialogImageConverter.setTabOrder(self.pushStart, self.pushDone)

    def retranslateUi(self, dialogImageConverter):
        _translate = QtCore.QCoreApplication.translate
        dialogImageConverter.setWindowTitle(_translate("dialogImageConverter", "Image Converter"))
        self.labelStatus.setText(_translate("dialogImageConverter", "Please select image(s) to convert."))
        self.pushBrowse.setText(_translate("dialogImageConverter", "Browse..."))
        self.pushDone.setText(_translate("dialogImageConverter", "Done"))
        self.pushStart.setText(_translate("dialogImageConverter", "Start"))
        self.checkAlternate.setToolTip(_translate("dialogImageConverter", "Use the raw filename to determine the new filename (if possible)"))
        self.checkAlternate.setText(_translate("dialogImageConverter", "Alternate Naming Scheme for Crop Images"))
        self.checkSave.setToolTip(_translate("dialogImageConverter", "Images will otherwise be saved to the images\' root folder."))
        self.checkSave.setText(_translate("dialogImageConverter", "Save to Individual Folders"))
        self.groupImagesSave.setTitle(_translate("dialogImageConverter", "Images to Save"))
        self.checkToggleAll.setText(_translate("dialogImageConverter", "Toggle All"))
        self.checkUndistort.setText(_translate("dialogImageConverter", "Undistort"))
        self.checkPerspective.setText(_translate("dialogImageConverter", "Perspective"))
        self.checkCrop.setText(_translate("dialogImageConverter", "Crop"))
        self.checkEqualization.setText(_translate("dialogImageConverter", "Equalization"))

