# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui\mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(988, 693)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/resources/logo.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        mainWindow.setWindowIcon(icon)
        self.centralWidget = QtWidgets.QWidget(mainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout.setContentsMargins(10, 10, 10, 10)
        self.gridLayout.setSpacing(7)
        self.gridLayout.setObjectName("gridLayout")
        self.widgetDisplay = QtWidgets.QTabWidget(self.centralWidget)
        self.widgetDisplay.setObjectName("widgetDisplay")
        self.tabCoatExplorer = QtWidgets.QWidget()
        self.tabCoatExplorer.setObjectName("tabCoatExplorer")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tabCoatExplorer)
        self.gridLayout_4.setContentsMargins(10, 10, 10, 10)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.stackedCE = QtWidgets.QStackedWidget(self.tabCoatExplorer)
        self.stackedCE.setMinimumSize(QtCore.QSize(763, 530))
        self.stackedCE.setObjectName("stackedCE")
        self.pageCE1 = QtWidgets.QWidget()
        self.pageCE1.setObjectName("pageCE1")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.pageCE1)
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.labelCE = QtWidgets.QLabel(self.pageCE1)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.labelCE.setFont(font)
        self.labelCE.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCE.setObjectName("labelCE")
        self.gridLayout_10.addWidget(self.labelCE, 0, 0, 1, 1)
        self.stackedCE.addWidget(self.pageCE1)
        self.pageCE2 = QtWidgets.QWidget()
        self.pageCE2.setObjectName("pageCE2")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.pageCE2)
        self.gridLayout_13.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.graphicsCE = ImageViewer(self.pageCE2)
        self.graphicsCE.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.graphicsCE.setObjectName("graphicsCE")
        self.gridLayout_13.addWidget(self.graphicsCE, 0, 0, 1, 1)
        self.stackedCE.addWidget(self.pageCE2)
        self.gridLayout_4.addWidget(self.stackedCE, 0, 0, 1, 1)
        self.widgetDisplay.addTab(self.tabCoatExplorer, "")
        self.tabScanExplorer = QtWidgets.QWidget()
        self.tabScanExplorer.setObjectName("tabScanExplorer")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tabScanExplorer)
        self.gridLayout_5.setContentsMargins(10, 10, 10, 10)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.stackedSE = QtWidgets.QStackedWidget(self.tabScanExplorer)
        self.stackedSE.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.stackedSE.setObjectName("stackedSE")
        self.pageSE1 = QtWidgets.QWidget()
        self.pageSE1.setObjectName("pageSE1")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.pageSE1)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.labelSE = QtWidgets.QLabel(self.pageSE1)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.labelSE.setFont(font)
        self.labelSE.setAlignment(QtCore.Qt.AlignCenter)
        self.labelSE.setObjectName("labelSE")
        self.gridLayout_6.addWidget(self.labelSE, 0, 0, 1, 1)
        self.stackedSE.addWidget(self.pageSE1)
        self.pageSE2 = QtWidgets.QWidget()
        self.pageSE2.setObjectName("pageSE2")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.pageSE2)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.graphicsSE = ImageViewer(self.pageSE2)
        self.graphicsSE.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.graphicsSE.setObjectName("graphicsSE")
        self.gridLayout_7.addWidget(self.graphicsSE, 0, 0, 1, 1)
        self.stackedSE.addWidget(self.pageSE2)
        self.gridLayout_5.addWidget(self.stackedSE, 0, 0, 1, 1)
        self.widgetDisplay.addTab(self.tabScanExplorer, "")
        self.tabPartContours = QtWidgets.QWidget()
        self.tabPartContours.setObjectName("tabPartContours")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.tabPartContours)
        self.gridLayout_8.setContentsMargins(10, 10, 10, 10)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.stackedPC = QtWidgets.QStackedWidget(self.tabPartContours)
        self.stackedPC.setObjectName("stackedPC")
        self.pagePC1 = QtWidgets.QWidget()
        self.pagePC1.setObjectName("pagePC1")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.pagePC1)
        self.gridLayout_11.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.labelPC = QtWidgets.QLabel(self.pagePC1)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.labelPC.setFont(font)
        self.labelPC.setAlignment(QtCore.Qt.AlignCenter)
        self.labelPC.setObjectName("labelPC")
        self.gridLayout_11.addWidget(self.labelPC, 0, 0, 1, 1)
        self.stackedPC.addWidget(self.pagePC1)
        self.pagePC2 = QtWidgets.QWidget()
        self.pagePC2.setObjectName("pagePC2")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.pagePC2)
        self.gridLayout_14.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.graphicsPC = ImageViewer(self.pagePC2)
        self.graphicsPC.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.graphicsPC.setObjectName("graphicsPC")
        self.gridLayout_14.addWidget(self.graphicsPC, 0, 0, 1, 1)
        self.stackedPC.addWidget(self.pagePC2)
        self.gridLayout_8.addWidget(self.stackedPC, 0, 0, 1, 1)
        self.widgetDisplay.addTab(self.tabPartContours, "")
        self.tabImageCapture = QtWidgets.QWidget()
        self.tabImageCapture.setObjectName("tabImageCapture")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.tabImageCapture)
        self.gridLayout_9.setContentsMargins(10, 10, 10, 10)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.stackedIC = QtWidgets.QStackedWidget(self.tabImageCapture)
        self.stackedIC.setObjectName("stackedIC")
        self.pageIC1 = QtWidgets.QWidget()
        self.pageIC1.setObjectName("pageIC1")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.pageIC1)
        self.gridLayout_12.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.labelIC = QtWidgets.QLabel(self.pageIC1)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.labelIC.setFont(font)
        self.labelIC.setAlignment(QtCore.Qt.AlignCenter)
        self.labelIC.setObjectName("labelIC")
        self.gridLayout_12.addWidget(self.labelIC, 0, 0, 1, 1)
        self.stackedIC.addWidget(self.pageIC1)
        self.pageIC = QtWidgets.QWidget()
        self.pageIC.setObjectName("pageIC")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.pageIC)
        self.gridLayout_15.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.graphicsIC = ImageViewer(self.pageIC)
        self.graphicsIC.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.graphicsIC.setObjectName("graphicsIC")
        self.gridLayout_15.addWidget(self.graphicsIC, 0, 0, 1, 1)
        self.stackedIC.addWidget(self.pageIC)
        self.gridLayout_9.addWidget(self.stackedIC, 0, 0, 1, 1)
        self.widgetDisplay.addTab(self.tabImageCapture, "")
        self.gridLayout.addWidget(self.widgetDisplay, 0, 1, 1, 1)
        self.frameProgress = QtWidgets.QFrame(self.centralWidget)
        self.frameProgress.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameProgress.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameProgress.setObjectName("frameProgress")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frameProgress)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.progressBar = QtWidgets.QProgressBar(self.frameProgress)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_2.addWidget(self.progressBar)
        self.pushTester = QtWidgets.QPushButton(self.frameProgress)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushTester.setFont(font)
        self.pushTester.setObjectName("pushTester")
        self.horizontalLayout_2.addWidget(self.pushTester)
        self.pushRun = QtWidgets.QPushButton(self.frameProgress)
        self.pushRun.setEnabled(False)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 128, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 128, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.pushRun.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushRun.setFont(font)
        self.pushRun.setObjectName("pushRun")
        self.horizontalLayout_2.addWidget(self.pushRun)
        self.pushStop = QtWidgets.QPushButton(self.frameProgress)
        self.pushStop.setEnabled(False)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.pushStop.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushStop.setFont(font)
        self.pushStop.setObjectName("pushStop")
        self.horizontalLayout_2.addWidget(self.pushStop)
        self.gridLayout.addWidget(self.frameProgress, 1, 1, 1, 2)
        self.frameSidebar = QtWidgets.QFrame(self.centralWidget)
        self.frameSidebar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameSidebar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameSidebar.setObjectName("frameSidebar")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frameSidebar)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frameLayer = QtWidgets.QFrame(self.frameSidebar)
        self.frameLayer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameLayer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameLayer.setObjectName("frameLayer")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frameLayer)
        self.gridLayout_3.setContentsMargins(7, 0, 7, 0)
        self.gridLayout_3.setVerticalSpacing(4)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.labelLayerNumberTitle = QtWidgets.QLabel(self.frameLayer)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelLayerNumberTitle.setFont(font)
        self.labelLayerNumberTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLayerNumberTitle.setObjectName("labelLayerNumberTitle")
        self.gridLayout_3.addWidget(self.labelLayerNumberTitle, 0, 0, 1, 2)
        self.spinLayer = QtWidgets.QSpinBox(self.frameLayer)
        self.spinLayer.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.spinLayer.setFont(font)
        self.spinLayer.setAlignment(QtCore.Qt.AlignCenter)
        self.spinLayer.setMinimum(1)
        self.spinLayer.setObjectName("spinLayer")
        self.gridLayout_3.addWidget(self.spinLayer, 2, 0, 1, 1)
        self.pushGo = QtWidgets.QPushButton(self.frameLayer)
        self.pushGo.setEnabled(False)
        self.pushGo.setMinimumSize(QtCore.QSize(38, 24))
        self.pushGo.setMaximumSize(QtCore.QSize(38, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.pushGo.setFont(font)
        self.pushGo.setObjectName("pushGo")
        self.gridLayout_3.addWidget(self.pushGo, 2, 1, 1, 1)
        self.labelLayerNumber = QtWidgets.QLabel(self.frameLayer)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.labelLayerNumber.setFont(font)
        self.labelLayerNumber.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLayerNumber.setObjectName("labelLayerNumber")
        self.gridLayout_3.addWidget(self.labelLayerNumber, 1, 0, 1, 2)
        self.gridLayout_2.addWidget(self.frameLayer, 2, 0, 1, 1)
        self.groupDisplayOptions = QtWidgets.QGroupBox(self.frameSidebar)
        self.groupDisplayOptions.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.groupDisplayOptions.setFont(font)
        self.groupDisplayOptions.setObjectName("groupDisplayOptions")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupDisplayOptions)
        self.verticalLayout.setContentsMargins(10, 7, 10, 7)
        self.verticalLayout.setObjectName("verticalLayout")
        self.radioOriginal = QtWidgets.QRadioButton(self.groupDisplayOptions)
        self.radioOriginal.setChecked(True)
        self.radioOriginal.setObjectName("radioOriginal")
        self.verticalLayout.addWidget(self.radioOriginal)
        self.radioCLAHE = QtWidgets.QRadioButton(self.groupDisplayOptions)
        self.radioCLAHE.setObjectName("radioCLAHE")
        self.verticalLayout.addWidget(self.radioCLAHE)
        self.radioDefects = QtWidgets.QRadioButton(self.groupDisplayOptions)
        self.radioDefects.setObjectName("radioDefects")
        self.verticalLayout.addWidget(self.radioDefects)
        self.checkOverlay = QtWidgets.QCheckBox(self.groupDisplayOptions)
        self.checkOverlay.setObjectName("checkOverlay")
        self.verticalLayout.addWidget(self.checkOverlay)
        self.gridLayout_2.addWidget(self.groupDisplayOptions, 0, 0, 1, 1)
        self.frameCapture = QtWidgets.QFrame(self.frameSidebar)
        self.frameCapture.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameCapture.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameCapture.setObjectName("frameCapture")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frameCapture)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.labelCamera = QtWidgets.QLabel(self.frameCapture)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.labelCamera.setFont(font)
        self.labelCamera.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCamera.setObjectName("labelCamera")
        self.verticalLayout_3.addWidget(self.labelCamera)
        self.labelCameraStatus = QtWidgets.QLabel(self.frameCapture)
        self.labelCameraStatus.setMinimumSize(QtCore.QSize(0, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.labelCameraStatus.setFont(font)
        self.labelCameraStatus.setFrameShape(QtWidgets.QFrame.Panel)
        self.labelCameraStatus.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.labelCameraStatus.setLineWidth(2)
        self.labelCameraStatus.setText("")
        self.labelCameraStatus.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCameraStatus.setObjectName("labelCameraStatus")
        self.verticalLayout_3.addWidget(self.labelCameraStatus)
        self.labelTrigger = QtWidgets.QLabel(self.frameCapture)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.labelTrigger.setFont(font)
        self.labelTrigger.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTrigger.setObjectName("labelTrigger")
        self.verticalLayout_3.addWidget(self.labelTrigger)
        self.labelTriggerStatus = QtWidgets.QLabel(self.frameCapture)
        self.labelTriggerStatus.setMinimumSize(QtCore.QSize(0, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.labelTriggerStatus.setFont(font)
        self.labelTriggerStatus.setFrameShape(QtWidgets.QFrame.Panel)
        self.labelTriggerStatus.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.labelTriggerStatus.setLineWidth(2)
        self.labelTriggerStatus.setText("")
        self.labelTriggerStatus.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTriggerStatus.setObjectName("labelTriggerStatus")
        self.verticalLayout_3.addWidget(self.labelTriggerStatus)
        self.pushAcquireCT = QtWidgets.QPushButton(self.frameCapture)
        self.pushAcquireCT.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushAcquireCT.setFont(font)
        self.pushAcquireCT.setObjectName("pushAcquireCT")
        self.verticalLayout_3.addWidget(self.pushAcquireCT)
        self.pushCapture = QtWidgets.QPushButton(self.frameCapture)
        self.pushCapture.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushCapture.setFont(font)
        self.pushCapture.setObjectName("pushCapture")
        self.verticalLayout_3.addWidget(self.pushCapture)
        self.frameTimer = QtWidgets.QFrame(self.frameCapture)
        self.frameTimer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameTimer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameTimer.setObjectName("frameTimer")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frameTimer)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.labelElapsed = QtWidgets.QLabel(self.frameTimer)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.labelElapsed.setFont(font)
        self.labelElapsed.setAlignment(QtCore.Qt.AlignCenter)
        self.labelElapsed.setObjectName("labelElapsed")
        self.verticalLayout_5.addWidget(self.labelElapsed)
        self.labelElapsedTime = QtWidgets.QLabel(self.frameTimer)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelElapsedTime.setFont(font)
        self.labelElapsedTime.setAlignment(QtCore.Qt.AlignCenter)
        self.labelElapsedTime.setObjectName("labelElapsedTime")
        self.verticalLayout_5.addWidget(self.labelElapsedTime)
        self.labelIdle = QtWidgets.QLabel(self.frameTimer)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.labelIdle.setFont(font)
        self.labelIdle.setAlignment(QtCore.Qt.AlignCenter)
        self.labelIdle.setObjectName("labelIdle")
        self.verticalLayout_5.addWidget(self.labelIdle)
        self.labelIdleTime = QtWidgets.QLabel(self.frameTimer)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelIdleTime.setFont(font)
        self.labelIdleTime.setAlignment(QtCore.Qt.AlignCenter)
        self.labelIdleTime.setObjectName("labelIdleTime")
        self.verticalLayout_5.addWidget(self.labelIdleTime)
        self.verticalLayout_3.addWidget(self.frameTimer)
        self.frameContinue = QtWidgets.QFrame(self.frameCapture)
        self.frameContinue.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameContinue.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameContinue.setObjectName("frameContinue")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frameContinue)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkResume = QtWidgets.QCheckBox(self.frameContinue)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkResume.setFont(font)
        self.checkResume.setObjectName("checkResume")
        self.horizontalLayout.addWidget(self.checkResume)
        self.spinStartingLayer = QtWidgets.QSpinBox(self.frameContinue)
        self.spinStartingLayer.setEnabled(False)
        self.spinStartingLayer.setMaximumSize(QtCore.QSize(44, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.spinStartingLayer.setFont(font)
        self.spinStartingLayer.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinStartingLayer.setMinimum(1)
        self.spinStartingLayer.setMaximum(9999)
        self.spinStartingLayer.setObjectName("spinStartingLayer")
        self.horizontalLayout.addWidget(self.spinStartingLayer)
        self.verticalLayout_3.addWidget(self.frameContinue)
        self.gridLayout_2.addWidget(self.frameCapture, 4, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 3, 0, 1, 1)
        self.groupAssortedTools = QtWidgets.QGroupBox(self.frameSidebar)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.groupAssortedTools.setFont(font)
        self.groupAssortedTools.setObjectName("groupAssortedTools")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupAssortedTools)
        self.verticalLayout_2.setContentsMargins(7, 7, 7, 7)
        self.verticalLayout_2.setSpacing(7)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushCameraCalibration = QtWidgets.QPushButton(self.groupAssortedTools)
        self.pushCameraCalibration.setObjectName("pushCameraCalibration")
        self.verticalLayout_2.addWidget(self.pushCameraCalibration)
        self.pushOverlayAdjustment = QtWidgets.QPushButton(self.groupAssortedTools)
        self.pushOverlayAdjustment.setEnabled(False)
        self.pushOverlayAdjustment.setObjectName("pushOverlayAdjustment")
        self.verticalLayout_2.addWidget(self.pushOverlayAdjustment)
        self.pushSliceConverter = QtWidgets.QPushButton(self.groupAssortedTools)
        self.pushSliceConverter.setObjectName("pushSliceConverter")
        self.verticalLayout_2.addWidget(self.pushSliceConverter)
        self.pushImageConverter = QtWidgets.QPushButton(self.groupAssortedTools)
        self.pushImageConverter.setObjectName("pushImageConverter")
        self.verticalLayout_2.addWidget(self.pushImageConverter)
        self.gridLayout_2.addWidget(self.groupAssortedTools, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.frameSidebar, 0, 3, 2, 1)
        self.frameSlider = QtWidgets.QFrame(self.centralWidget)
        self.frameSlider.setEnabled(False)
        self.frameSlider.setObjectName("frameSlider")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frameSlider)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pushDisplayUp = QtWidgets.QPushButton(self.frameSlider)
        self.pushDisplayUp.setMinimumSize(QtCore.QSize(27, 26))
        self.pushDisplayUp.setMaximumSize(QtCore.QSize(27, 26))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushDisplayUp.setFont(font)
        self.pushDisplayUp.setObjectName("pushDisplayUp")
        self.verticalLayout_4.addWidget(self.pushDisplayUp)
        self.sliderDisplay = QtWidgets.QSlider(self.frameSlider)
        self.sliderDisplay.setMinimum(1)
        self.sliderDisplay.setTracking(False)
        self.sliderDisplay.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.sliderDisplay.setTickInterval(10)
        self.sliderDisplay.setObjectName("sliderDisplay")
        self.verticalLayout_4.addWidget(self.sliderDisplay)
        self.pushDisplayDown = QtWidgets.QPushButton(self.frameSlider)
        self.pushDisplayDown.setMinimumSize(QtCore.QSize(27, 26))
        self.pushDisplayDown.setMaximumSize(QtCore.QSize(27, 26))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushDisplayDown.setFont(font)
        self.pushDisplayDown.setObjectName("pushDisplayDown")
        self.verticalLayout_4.addWidget(self.pushDisplayDown)
        self.gridLayout.addWidget(self.frameSlider, 0, 2, 1, 1)
        mainWindow.setCentralWidget(self.centralWidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 988, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuRecentBuilds = QtWidgets.QMenu(self.menuFile)
        self.menuRecentBuilds.setObjectName("menuRecentBuilds")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuTools = QtWidgets.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        mainWindow.setMenuBar(self.menubar)
        self.statusBar = QtWidgets.QStatusBar(mainWindow)
        self.statusBar.setObjectName("statusBar")
        mainWindow.setStatusBar(self.statusBar)
        self.toolBar = QtWidgets.QToolBar(mainWindow)
        self.toolBar.setObjectName("toolBar")
        mainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionNew = QtWidgets.QAction(mainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(mainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(mainWindow)
        self.actionSave.setEnabled(False)
        self.actionSave.setObjectName("actionSave")
        self.actionSaveAs = QtWidgets.QAction(mainWindow)
        self.actionSaveAs.setEnabled(False)
        self.actionSaveAs.setObjectName("actionSaveAs")
        self.actionExportImage = QtWidgets.QAction(mainWindow)
        self.actionExportImage.setEnabled(False)
        self.actionExportImage.setObjectName("actionExportImage")
        self.actionQuit = QtWidgets.QAction(mainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionCameraSettings = QtWidgets.QAction(mainWindow)
        self.actionCameraSettings.setObjectName("actionCameraSettings")
        self.actionBuildSettings = QtWidgets.QAction(mainWindow)
        self.actionBuildSettings.setObjectName("actionBuildSettings")
        self.actionCameraCalibration = QtWidgets.QAction(mainWindow)
        self.actionCameraCalibration.setObjectName("actionCameraCalibration")
        self.actionImageConverter = QtWidgets.QAction(mainWindow)
        self.actionImageConverter.setObjectName("actionImageConverter")
        self.actionSliceConverter = QtWidgets.QAction(mainWindow)
        self.actionSliceConverter.setObjectName("actionSliceConverter")
        self.actionOverlayAdjustment = QtWidgets.QAction(mainWindow)
        self.actionOverlayAdjustment.setEnabled(False)
        self.actionOverlayAdjustment.setObjectName("actionOverlayAdjustment")
        self.actionViewHelp = QtWidgets.QAction(mainWindow)
        self.actionViewHelp.setObjectName("actionViewHelp")
        self.actionAbout = QtWidgets.QAction(mainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionZoomIn = QtWidgets.QAction(mainWindow)
        self.actionZoomIn.setEnabled(False)
        self.actionZoomIn.setObjectName("actionZoomIn")
        self.actionZoomOut = QtWidgets.QAction(mainWindow)
        self.actionZoomOut.setEnabled(False)
        self.actionZoomOut.setObjectName("actionZoomOut")
        self.actionFitScreen = QtWidgets.QAction(mainWindow)
        self.actionFitScreen.setEnabled(False)
        self.actionFitScreen.setObjectName("actionFitScreen")
        self.actionOriginalSize = QtWidgets.QAction(mainWindow)
        self.actionOriginalSize.setEnabled(False)
        self.actionOriginalSize.setObjectName("actionOriginalSize")
        self.actionClearMenu = QtWidgets.QAction(mainWindow)
        self.actionClearMenu.setObjectName("actionClearMenu")
        self.menuRecentBuilds.addSeparator()
        self.menuRecentBuilds.addAction(self.actionClearMenu)
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.menuRecentBuilds.menuAction())
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSaveAs)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExportImage)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuView.addAction(self.actionZoomIn)
        self.menuView.addAction(self.actionZoomOut)
        self.menuView.addAction(self.actionOriginalSize)
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionFitScreen)
        self.menuTools.addAction(self.actionCameraCalibration)
        self.menuTools.addAction(self.actionOverlayAdjustment)
        self.menuTools.addSeparator()
        self.menuTools.addAction(self.actionImageConverter)
        self.menuTools.addAction(self.actionSliceConverter)
        self.menuHelp.addAction(self.actionViewHelp)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAbout)
        self.menuSettings.addAction(self.actionCameraSettings)
        self.menuSettings.addAction(self.actionBuildSettings)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolBar.addAction(self.actionNew)
        self.toolBar.addAction(self.actionOpen)
        self.toolBar.addAction(self.actionSave)
        self.toolBar.addAction(self.actionExportImage)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionZoomIn)
        self.toolBar.addAction(self.actionZoomOut)
        self.toolBar.addAction(self.actionOriginalSize)
        self.toolBar.addAction(self.actionFitScreen)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionCameraCalibration)
        self.toolBar.addAction(self.actionOverlayAdjustment)
        self.toolBar.addAction(self.actionSliceConverter)
        self.toolBar.addAction(self.actionImageConverter)

        self.retranslateUi(mainWindow)
        self.widgetDisplay.setCurrentIndex(0)
        self.stackedCE.setCurrentIndex(0)
        self.stackedSE.setCurrentIndex(0)
        self.stackedPC.setCurrentIndex(0)
        self.stackedIC.setCurrentIndex(0)
        self.checkResume.toggled['bool'].connect(self.spinStartingLayer.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)
        mainWindow.setTabOrder(self.widgetDisplay, self.pushRun)
        mainWindow.setTabOrder(self.pushRun, self.pushStop)
        mainWindow.setTabOrder(self.pushStop, self.pushDisplayUp)
        mainWindow.setTabOrder(self.pushDisplayUp, self.sliderDisplay)
        mainWindow.setTabOrder(self.sliderDisplay, self.pushDisplayDown)
        mainWindow.setTabOrder(self.pushDisplayDown, self.radioOriginal)
        mainWindow.setTabOrder(self.radioOriginal, self.radioCLAHE)
        mainWindow.setTabOrder(self.radioCLAHE, self.radioDefects)
        mainWindow.setTabOrder(self.radioDefects, self.checkOverlay)
        mainWindow.setTabOrder(self.checkOverlay, self.pushCameraCalibration)
        mainWindow.setTabOrder(self.pushCameraCalibration, self.pushOverlayAdjustment)
        mainWindow.setTabOrder(self.pushOverlayAdjustment, self.pushSliceConverter)
        mainWindow.setTabOrder(self.pushSliceConverter, self.pushImageConverter)
        mainWindow.setTabOrder(self.pushImageConverter, self.spinLayer)
        mainWindow.setTabOrder(self.spinLayer, self.pushGo)
        mainWindow.setTabOrder(self.pushGo, self.pushAcquireCT)
        mainWindow.setTabOrder(self.pushAcquireCT, self.pushCapture)
        mainWindow.setTabOrder(self.pushCapture, self.checkResume)
        mainWindow.setTabOrder(self.checkResume, self.spinStartingLayer)
        mainWindow.setTabOrder(self.spinStartingLayer, self.graphicsCE)
        mainWindow.setTabOrder(self.graphicsCE, self.graphicsSE)
        mainWindow.setTabOrder(self.graphicsSE, self.graphicsPC)
        mainWindow.setTabOrder(self.graphicsPC, self.graphicsIC)
        mainWindow.setTabOrder(self.graphicsIC, self.pushTester)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Defect Monitor"))
        self.labelCE.setText(_translate("mainWindow", "Create or Open a Build to View Images"))
        self.widgetDisplay.setTabText(self.widgetDisplay.indexOf(self.tabCoatExplorer), _translate("mainWindow", "Coat Explorer"))
        self.labelSE.setText(_translate("mainWindow", "Create or Open a Build to View Images"))
        self.widgetDisplay.setTabText(self.widgetDisplay.indexOf(self.tabScanExplorer), _translate("mainWindow", "Scan Explorer"))
        self.labelPC.setText(_translate("mainWindow", "Create or Open a Build to View Images"))
        self.widgetDisplay.setTabText(self.widgetDisplay.indexOf(self.tabPartContours), _translate("mainWindow", "Part Contours"))
        self.labelIC.setText(_translate("mainWindow", "Create or Open a Build to View Images"))
        self.widgetDisplay.setTabText(self.widgetDisplay.indexOf(self.tabImageCapture), _translate("mainWindow", "Image Capture"))
        self.pushTester.setText(_translate("mainWindow", "Tester"))
        self.pushRun.setText(_translate("mainWindow", "RUN"))
        self.pushStop.setText(_translate("mainWindow", "STOP"))
        self.labelLayerNumberTitle.setText(_translate("mainWindow", "Layer Number"))
        self.pushGo.setText(_translate("mainWindow", "Go"))
        self.labelLayerNumber.setText(_translate("mainWindow", "0001"))
        self.groupDisplayOptions.setTitle(_translate("mainWindow", "Display Options"))
        self.radioOriginal.setText(_translate("mainWindow", "Original"))
        self.radioCLAHE.setText(_translate("mainWindow", "Equalization"))
        self.radioDefects.setText(_translate("mainWindow", "Defect Analysis"))
        self.checkOverlay.setText(_translate("mainWindow", "Toggle Overlay"))
        self.labelCamera.setText(_translate("mainWindow", "Camera Status"))
        self.labelTrigger.setText(_translate("mainWindow", "Trigger Status"))
        self.pushAcquireCT.setText(_translate("mainWindow", "Acquire Camera / Trigger"))
        self.pushCapture.setText(_translate("mainWindow", "Capture Single Image"))
        self.labelElapsed.setText(_translate("mainWindow", "Elapsed Time"))
        self.labelElapsedTime.setText(_translate("mainWindow", "00:00:00"))
        self.labelIdle.setText(_translate("mainWindow", "Idle Time"))
        self.labelIdleTime.setText(_translate("mainWindow", "00:00:00"))
        self.checkResume.setText(_translate("mainWindow", "Resume From"))
        self.groupAssortedTools.setTitle(_translate("mainWindow", "Assorted Tools"))
        self.pushCameraCalibration.setText(_translate("mainWindow", "Camera Calibration"))
        self.pushOverlayAdjustment.setText(_translate("mainWindow", "Overlay Adjustment"))
        self.pushSliceConverter.setText(_translate("mainWindow", "Slice Converter"))
        self.pushImageConverter.setText(_translate("mainWindow", "Image Converter"))
        self.pushDisplayUp.setText(_translate("mainWindow", "▲"))
        self.pushDisplayDown.setText(_translate("mainWindow", "▼"))
        self.menuFile.setTitle(_translate("mainWindow", "File"))
        self.menuRecentBuilds.setTitle(_translate("mainWindow", "Recent Builds"))
        self.menuView.setTitle(_translate("mainWindow", "View"))
        self.menuTools.setTitle(_translate("mainWindow", "Tools"))
        self.menuHelp.setTitle(_translate("mainWindow", "Help"))
        self.menuSettings.setTitle(_translate("mainWindow", "Settings"))
        self.toolBar.setWindowTitle(_translate("mainWindow", "toolBar"))
        self.actionNew.setText(_translate("mainWindow", "New..."))
        self.actionOpen.setText(_translate("mainWindow", "Open..."))
        self.actionSave.setText(_translate("mainWindow", "Save"))
        self.actionSaveAs.setText(_translate("mainWindow", "Save As..."))
        self.actionExportImage.setText(_translate("mainWindow", "Export Image..."))
        self.actionQuit.setText(_translate("mainWindow", "Quit"))
        self.actionCameraSettings.setText(_translate("mainWindow", "Camera Settings..."))
        self.actionBuildSettings.setText(_translate("mainWindow", "Build Settings..."))
        self.actionCameraCalibration.setText(_translate("mainWindow", "Camera Calibration"))
        self.actionImageConverter.setText(_translate("mainWindow", "Image Converter"))
        self.actionSliceConverter.setText(_translate("mainWindow", "Slice Converter"))
        self.actionOverlayAdjustment.setText(_translate("mainWindow", "Overlay Adjustment"))
        self.actionViewHelp.setText(_translate("mainWindow", "View Help"))
        self.actionAbout.setText(_translate("mainWindow", "About"))
        self.actionZoomIn.setText(_translate("mainWindow", "Zoom In"))
        self.actionZoomOut.setText(_translate("mainWindow", "Zoom Out"))
        self.actionFitScreen.setText(_translate("mainWindow", "Fit to Screen"))
        self.actionOriginalSize.setText(_translate("mainWindow", "Original Size"))
        self.actionClearMenu.setText(_translate("mainWindow", "Clear Menu"))

from ui_elements import ImageViewer
import icons_rc
