# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName(_fromUtf8("mainWindow"))
        mainWindow.setEnabled(True)
        mainWindow.resize(1203, 779)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(mainWindow.sizePolicy().hasHeightForWidth())
        mainWindow.setSizePolicy(sizePolicy)
        mainWindow.setMinimumSize(QtCore.QSize(1203, 779))
        mainWindow.setMaximumSize(QtCore.QSize(1203, 779))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/resources/logo.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        mainWindow.setWindowIcon(icon)
        mainWindow.setStatusTip(_fromUtf8(""))
        mainWindow.setIconSize(QtCore.QSize(24, 24))
        mainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.mainWidget = QtGui.QWidget(mainWindow)
        self.mainWidget.setObjectName(_fromUtf8("mainWidget"))
        self.widgetDisplay = QtGui.QTabWidget(self.mainWidget)
        self.widgetDisplay.setGeometry(QtCore.QRect(11, 11, 1041, 651))
        self.widgetDisplay.setObjectName(_fromUtf8("widgetDisplay"))
        self.widgetTab1 = QtGui.QWidget()
        self.widgetTab1.setObjectName(_fromUtf8("widgetTab1"))
        self.gridLayout = QtGui.QGridLayout(self.widgetTab1)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.sliderSE = QtGui.QSlider(self.widgetTab1)
        self.sliderSE.setOrientation(QtCore.Qt.Vertical)
        self.sliderSE.setObjectName(_fromUtf8("sliderSE"))
        self.gridLayout.addWidget(self.sliderSE, 0, 1, 1, 1)
        self.labelDisplaySE = QtGui.QLabel(self.widgetTab1)
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.labelDisplaySE.setFont(font)
        self.labelDisplaySE.setAlignment(QtCore.Qt.AlignCenter)
        self.labelDisplaySE.setObjectName(_fromUtf8("labelDisplaySE"))
        self.gridLayout.addWidget(self.labelDisplaySE, 0, 0, 1, 1)
        self.widgetDisplay.addTab(self.widgetTab1, _fromUtf8(""))
        self.widgetTab2 = QtGui.QWidget()
        self.widgetTab2.setObjectName(_fromUtf8("widgetTab2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.widgetTab2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.labelDisplayCE = QtGui.QLabel(self.widgetTab2)
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.labelDisplayCE.setFont(font)
        self.labelDisplayCE.setAlignment(QtCore.Qt.AlignCenter)
        self.labelDisplayCE.setObjectName(_fromUtf8("labelDisplayCE"))
        self.gridLayout_2.addWidget(self.labelDisplayCE, 0, 0, 1, 1)
        self.sliderCE = QtGui.QSlider(self.widgetTab2)
        self.sliderCE.setOrientation(QtCore.Qt.Vertical)
        self.sliderCE.setObjectName(_fromUtf8("sliderCE"))
        self.gridLayout_2.addWidget(self.sliderCE, 0, 1, 1, 1)
        self.widgetDisplay.addTab(self.widgetTab2, _fromUtf8(""))
        self.widgetTab3 = QtGui.QWidget()
        self.widgetTab3.setObjectName(_fromUtf8("widgetTab3"))
        self.gridLayout_5 = QtGui.QGridLayout(self.widgetTab3)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.labelDisplayDA = QtGui.QLabel(self.widgetTab3)
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.labelDisplayDA.setFont(font)
        self.labelDisplayDA.setAlignment(QtCore.Qt.AlignCenter)
        self.labelDisplayDA.setObjectName(_fromUtf8("labelDisplayDA"))
        self.gridLayout_5.addWidget(self.labelDisplayDA, 0, 0, 1, 1)
        self.sliderDA = QtGui.QSlider(self.widgetTab3)
        self.sliderDA.setOrientation(QtCore.Qt.Vertical)
        self.sliderDA.setObjectName(_fromUtf8("sliderDA"))
        self.gridLayout_5.addWidget(self.sliderDA, 0, 1, 1, 1)
        self.widgetDisplay.addTab(self.widgetTab3, _fromUtf8(""))
        self.groupOpenCV = QtGui.QGroupBox(self.mainWidget)
        self.groupOpenCV.setEnabled(False)
        self.groupOpenCV.setGeometry(QtCore.QRect(1060, 190, 131, 151))
        self.groupOpenCV.setCheckable(False)
        self.groupOpenCV.setObjectName(_fromUtf8("groupOpenCV"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupOpenCV)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.radioBladeChatter = QtGui.QRadioButton(self.groupOpenCV)
        self.radioBladeChatter.setObjectName(_fromUtf8("radioBladeChatter"))
        self.verticalLayout_2.addWidget(self.radioBladeChatter)
        self.radioBladeFaults = QtGui.QRadioButton(self.groupOpenCV)
        self.radioBladeFaults.setObjectName(_fromUtf8("radioBladeFaults"))
        self.verticalLayout_2.addWidget(self.radioBladeFaults)
        self.radioBladeStreaks = QtGui.QRadioButton(self.groupOpenCV)
        self.radioBladeStreaks.setObjectName(_fromUtf8("radioBladeStreaks"))
        self.verticalLayout_2.addWidget(self.radioBladeStreaks)
        self.radioPartCoverage = QtGui.QRadioButton(self.groupOpenCV)
        self.radioPartCoverage.setObjectName(_fromUtf8("radioPartCoverage"))
        self.verticalLayout_2.addWidget(self.radioPartCoverage)
        self.radioPowderHoles = QtGui.QRadioButton(self.groupOpenCV)
        self.radioPowderHoles.setObjectName(_fromUtf8("radioPowderHoles"))
        self.verticalLayout_2.addWidget(self.radioPowderHoles)
        self.labelLayerNumberTitle = QtGui.QLabel(self.mainWidget)
        self.labelLayerNumberTitle.setGeometry(QtCore.QRect(460, 670, 110, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.labelLayerNumberTitle.setFont(font)
        self.labelLayerNumberTitle.setObjectName(_fromUtf8("labelLayerNumberTitle"))
        self.groupDisplayOptions = QtGui.QGroupBox(self.mainWidget)
        self.groupDisplayOptions.setEnabled(False)
        self.groupDisplayOptions.setGeometry(QtCore.QRect(1060, 20, 131, 161))
        self.groupDisplayOptions.setObjectName(_fromUtf8("groupDisplayOptions"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupDisplayOptions)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.radioRaw = QtGui.QRadioButton(self.groupDisplayOptions)
        self.radioRaw.setObjectName(_fromUtf8("radioRaw"))
        self.verticalLayout.addWidget(self.radioRaw)
        self.radioCorrection = QtGui.QRadioButton(self.groupDisplayOptions)
        self.radioCorrection.setObjectName(_fromUtf8("radioCorrection"))
        self.verticalLayout.addWidget(self.radioCorrection)
        self.radioCrop = QtGui.QRadioButton(self.groupDisplayOptions)
        self.radioCrop.setObjectName(_fromUtf8("radioCrop"))
        self.verticalLayout.addWidget(self.radioCrop)
        self.radioCLAHE = QtGui.QRadioButton(self.groupDisplayOptions)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.radioCLAHE.setFont(font)
        self.radioCLAHE.setChecked(True)
        self.radioCLAHE.setObjectName(_fromUtf8("radioCLAHE"))
        self.verticalLayout.addWidget(self.radioCLAHE)
        self.checkToggleOverlay = QtGui.QCheckBox(self.groupDisplayOptions)
        self.checkToggleOverlay.setObjectName(_fromUtf8("checkToggleOverlay"))
        self.verticalLayout.addWidget(self.checkToggleOverlay)
        self.progressBar = QtGui.QProgressBar(self.mainWidget)
        self.progressBar.setEnabled(True)
        self.progressBar.setGeometry(QtCore.QRect(11, 700, 441, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(True)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.labelLayerNumber = QtGui.QLabel(self.mainWidget)
        self.labelLayerNumber.setGeometry(QtCore.QRect(480, 690, 71, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.labelLayerNumber.setFont(font)
        self.labelLayerNumber.setTextFormat(QtCore.Qt.AutoText)
        self.labelLayerNumber.setObjectName(_fromUtf8("labelLayerNumber"))
        self.groupPositionAdjustment = QtGui.QGroupBox(self.mainWidget)
        self.groupPositionAdjustment.setEnabled(False)
        self.groupPositionAdjustment.setGeometry(QtCore.QRect(1060, 460, 131, 201))
        self.groupPositionAdjustment.setObjectName(_fromUtf8("groupPositionAdjustment"))
        self.buttonCrop = QtGui.QPushButton(self.groupPositionAdjustment)
        self.buttonCrop.setGeometry(QtCore.QRect(10, 80, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.buttonCrop.setFont(font)
        self.buttonCrop.setCheckable(True)
        self.buttonCrop.setObjectName(_fromUtf8("buttonCrop"))
        self.buttonShiftLeft = QtGui.QPushButton(self.groupPositionAdjustment)
        self.buttonShiftLeft.setGeometry(QtCore.QRect(10, 120, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.buttonShiftLeft.setFont(font)
        self.buttonShiftLeft.setObjectName(_fromUtf8("buttonShiftLeft"))
        self.buttonShiftRight = QtGui.QPushButton(self.groupPositionAdjustment)
        self.buttonShiftRight.setGeometry(QtCore.QRect(90, 120, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.buttonShiftRight.setFont(font)
        self.buttonShiftRight.setObjectName(_fromUtf8("buttonShiftRight"))
        self.buttonShiftDown = QtGui.QPushButton(self.groupPositionAdjustment)
        self.buttonShiftDown.setGeometry(QtCore.QRect(50, 160, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.buttonShiftDown.setFont(font)
        self.buttonShiftDown.setObjectName(_fromUtf8("buttonShiftDown"))
        self.buttonShiftUp = QtGui.QPushButton(self.groupPositionAdjustment)
        self.buttonShiftUp.setGeometry(QtCore.QRect(50, 80, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.buttonShiftUp.setFont(font)
        self.buttonShiftUp.setObjectName(_fromUtf8("buttonShiftUp"))
        self.buttonRotateACW = QtGui.QPushButton(self.groupPositionAdjustment)
        self.buttonRotateACW.setGeometry(QtCore.QRect(10, 160, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        font.setKerning(True)
        self.buttonRotateACW.setFont(font)
        self.buttonRotateACW.setObjectName(_fromUtf8("buttonRotateACW"))
        self.buttonRotateCW = QtGui.QPushButton(self.groupPositionAdjustment)
        self.buttonRotateCW.setGeometry(QtCore.QRect(90, 160, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        font.setKerning(True)
        self.buttonRotateCW.setFont(font)
        self.buttonRotateCW.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.buttonRotateCW.setObjectName(_fromUtf8("buttonRotateCW"))
        self.labelPixels = QtGui.QLabel(self.groupPositionAdjustment)
        self.labelPixels.setGeometry(QtCore.QRect(70, 25, 50, 20))
        self.labelPixels.setObjectName(_fromUtf8("labelPixels"))
        self.buttonBoundary = QtGui.QPushButton(self.groupPositionAdjustment)
        self.buttonBoundary.setGeometry(QtCore.QRect(90, 80, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.buttonBoundary.setFont(font)
        self.buttonBoundary.setCheckable(True)
        self.buttonBoundary.setObjectName(_fromUtf8("buttonBoundary"))
        self.lineShiftDegrees = QtGui.QLineEdit(self.groupPositionAdjustment)
        self.lineShiftDegrees.setGeometry(QtCore.QRect(20, 50, 41, 20))
        self.lineShiftDegrees.setMaxLength(5)
        self.lineShiftDegrees.setEchoMode(QtGui.QLineEdit.Normal)
        self.lineShiftDegrees.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineShiftDegrees.setObjectName(_fromUtf8("lineShiftDegrees"))
        self.lineShiftPixels = QtGui.QLineEdit(self.groupPositionAdjustment)
        self.lineShiftPixels.setGeometry(QtCore.QRect(20, 25, 41, 20))
        self.lineShiftPixels.setMaxLength(2)
        self.lineShiftPixels.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineShiftPixels.setObjectName(_fromUtf8("lineShiftPixels"))
        self.labelDegrees = QtGui.QLabel(self.groupPositionAdjustment)
        self.labelDegrees.setGeometry(QtCore.QRect(70, 50, 50, 20))
        self.labelDegrees.setObjectName(_fromUtf8("labelDegrees"))
        self.checkSimulation = QtGui.QCheckBox(self.mainWidget)
        self.checkSimulation.setGeometry(QtCore.QRect(1065, 350, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.checkSimulation.setFont(font)
        self.checkSimulation.setChecked(True)
        self.checkSimulation.setObjectName(_fromUtf8("checkSimulation"))
        self.lineLayer = QtGui.QLineEdit(self.mainWidget)
        self.lineLayer.setGeometry(QtCore.QRect(581, 671, 131, 22))
        self.lineLayer.setInputMask(_fromUtf8(""))
        self.lineLayer.setMaxLength(5)
        self.lineLayer.setAlignment(QtCore.Qt.AlignCenter)
        self.lineLayer.setObjectName(_fromUtf8("lineLayer"))
        self.buttonSet = QtGui.QPushButton(self.mainWidget)
        self.buttonSet.setEnabled(True)
        self.buttonSet.setGeometry(QtCore.QRect(581, 700, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.buttonSet.setFont(font)
        self.buttonSet.setObjectName(_fromUtf8("buttonSet"))
        self.buttonPhase = QtGui.QPushButton(self.mainWidget)
        self.buttonPhase.setEnabled(True)
        self.buttonPhase.setGeometry(QtCore.QRect(650, 700, 61, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.buttonPhase.setFont(font)
        self.buttonPhase.setCheckable(False)
        self.buttonPhase.setObjectName(_fromUtf8("buttonPhase"))
        self.buttonStop = QtGui.QPushButton(self.mainWidget)
        self.buttonStop.setEnabled(False)
        self.buttonStop.setGeometry(QtCore.QRect(346, 666, 101, 28))
        self.buttonStop.setObjectName(_fromUtf8("buttonStop"))
        self.buttonInitialize = QtGui.QPushButton(self.mainWidget)
        self.buttonInitialize.setEnabled(False)
        self.buttonInitialize.setGeometry(QtCore.QRect(11, 666, 101, 28))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.buttonInitialize.setFont(font)
        self.buttonInitialize.setObjectName(_fromUtf8("buttonInitialize"))
        self.buttonStart = QtGui.QPushButton(self.mainWidget)
        self.buttonStart.setEnabled(False)
        self.buttonStart.setGeometry(QtCore.QRect(123, 666, 101, 28))
        self.buttonStart.setObjectName(_fromUtf8("buttonStart"))
        self.buttonPause = QtGui.QPushButton(self.mainWidget)
        self.buttonPause.setEnabled(False)
        self.buttonPause.setGeometry(QtCore.QRect(234, 666, 101, 28))
        self.buttonPause.setObjectName(_fromUtf8("buttonPause"))
        mainWindow.setCentralWidget(self.mainWidget)
        self.menuBar = QtGui.QMenuBar(mainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1203, 26))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuFile = QtGui.QMenu(self.menuBar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuSetup = QtGui.QMenu(self.menuBar)
        self.menuSetup.setObjectName(_fromUtf8("menuSetup"))
        self.menuPartFiles = QtGui.QMenu(self.menuSetup)
        self.menuPartFiles.setObjectName(_fromUtf8("menuPartFiles"))
        self.menuReportSettings = QtGui.QMenu(self.menuSetup)
        self.menuReportSettings.setObjectName(_fromUtf8("menuReportSettings"))
        self.menuImageCalibration = QtGui.QMenu(self.menuSetup)
        self.menuImageCalibration.setObjectName(_fromUtf8("menuImageCalibration"))
        self.menuRun = QtGui.QMenu(self.menuBar)
        self.menuRun.setObjectName(_fromUtf8("menuRun"))
        mainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtGui.QStatusBar(mainWindow)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.statusBar.setFont(font)
        self.statusBar.setStatusTip(_fromUtf8(""))
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        mainWindow.setStatusBar(self.statusBar)
        self.actionBuildPlatform = QtGui.QAction(mainWindow)
        self.actionBuildPlatform.setObjectName(_fromUtf8("actionBuildPlatform"))
        self.actionCLS = QtGui.QAction(mainWindow)
        self.actionCLS.setObjectName(_fromUtf8("actionCLS"))
        self.actionCLI = QtGui.QAction(mainWindow)
        self.actionCLI.setEnabled(False)
        self.actionCLI.setObjectName(_fromUtf8("actionCLI"))
        self.actionNewBuild = QtGui.QAction(mainWindow)
        self.actionNewBuild.setObjectName(_fromUtf8("actionNewBuild"))
        self.actionOpenBuild = QtGui.QAction(mainWindow)
        self.actionOpenBuild.setObjectName(_fromUtf8("actionOpenBuild"))
        self.actionExportImage = QtGui.QAction(mainWindow)
        self.actionExportImage.setObjectName(_fromUtf8("actionExportImage"))
        self.actionError_actions = QtGui.QAction(mainWindow)
        self.actionError_actions.setObjectName(_fromUtf8("actionError_actions"))
        self.actionDefectActions = QtGui.QAction(mainWindow)
        self.actionDefectActions.setObjectName(_fromUtf8("actionDefectActions"))
        self.actionNotificationSetup = QtGui.QAction(mainWindow)
        self.actionNotificationSetup.setObjectName(_fromUtf8("actionNotificationSetup"))
        self.actionAdjustCrop = QtGui.QAction(mainWindow)
        self.actionAdjustCrop.setObjectName(_fromUtf8("actionAdjustCrop"))
        self.actionAdjustRotation = QtGui.QAction(mainWindow)
        self.actionAdjustRotation.setObjectName(_fromUtf8("actionAdjustRotation"))
        self.actionStartBuild = QtGui.QAction(mainWindow)
        self.actionStartBuild.setEnabled(False)
        self.actionStartBuild.setObjectName(_fromUtf8("actionStartBuild"))
        self.actionPauseBuild = QtGui.QAction(mainWindow)
        self.actionPauseBuild.setEnabled(False)
        self.actionPauseBuild.setObjectName(_fromUtf8("actionPauseBuild"))
        self.actionStopBuild = QtGui.QAction(mainWindow)
        self.actionStopBuild.setEnabled(False)
        self.actionStopBuild.setObjectName(_fromUtf8("actionStopBuild"))
        self.actionExit = QtGui.QAction(mainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionInitializeBuild = QtGui.QAction(mainWindow)
        self.actionInitializeBuild.setEnabled(False)
        self.actionInitializeBuild.setObjectName(_fromUtf8("actionInitializeBuild"))
        self.menuFile.addAction(self.actionNewBuild)
        self.menuFile.addAction(self.actionOpenBuild)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExportImage)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuPartFiles.addAction(self.actionCLS)
        self.menuPartFiles.addAction(self.actionCLI)
        self.menuReportSettings.addAction(self.actionDefectActions)
        self.menuReportSettings.addAction(self.actionNotificationSetup)
        self.menuImageCalibration.addAction(self.actionAdjustCrop)
        self.menuImageCalibration.addAction(self.actionAdjustRotation)
        self.menuSetup.addAction(self.actionBuildPlatform)
        self.menuSetup.addAction(self.menuPartFiles.menuAction())
        self.menuSetup.addSeparator()
        self.menuSetup.addAction(self.menuImageCalibration.menuAction())
        self.menuSetup.addSeparator()
        self.menuSetup.addAction(self.menuReportSettings.menuAction())
        self.menuRun.addAction(self.actionInitializeBuild)
        self.menuRun.addAction(self.actionStartBuild)
        self.menuRun.addAction(self.actionPauseBuild)
        self.menuRun.addSeparator()
        self.menuRun.addAction(self.actionStopBuild)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuSetup.menuAction())
        self.menuBar.addAction(self.menuRun.menuAction())

        self.retranslateUi(mainWindow)
        self.widgetDisplay.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        mainWindow.setWindowTitle(_translate("mainWindow", "Defect Monitor", None))
        self.labelDisplaySE.setText(_translate("mainWindow", "File -> New Build -> OK -> Initialize", None))
        self.widgetDisplay.setTabText(self.widgetDisplay.indexOf(self.widgetTab1), _translate("mainWindow", "Scan Explorer", None))
        self.labelDisplayCE.setText(_translate("mainWindow", "File -> New Build -> OK -> Initialize", None))
        self.widgetDisplay.setTabText(self.widgetDisplay.indexOf(self.widgetTab2), _translate("mainWindow", "Coat Explorer", None))
        self.labelDisplayDA.setText(_translate("mainWindow", "File -> New Build -> OK -> Initialize", None))
        self.widgetDisplay.setTabText(self.widgetDisplay.indexOf(self.widgetTab3), _translate("mainWindow", "Defect Analyzer", None))
        self.groupOpenCV.setTitle(_translate("mainWindow", "OpenCV Processing", None))
        self.radioBladeChatter.setText(_translate("mainWindow", "Blade Chatter", None))
        self.radioBladeFaults.setText(_translate("mainWindow", "Blade Faults", None))
        self.radioBladeStreaks.setText(_translate("mainWindow", "Blade Streaks", None))
        self.radioPartCoverage.setText(_translate("mainWindow", "Part Coverage", None))
        self.radioPowderHoles.setText(_translate("mainWindow", "Powder Holes", None))
        self.labelLayerNumberTitle.setText(_translate("mainWindow", "<html><head/><body><p align=\"center\">Layer Number</p></body></html>", None))
        self.groupDisplayOptions.setTitle(_translate("mainWindow", "Display Options", None))
        self.radioRaw.setText(_translate("mainWindow", "Raw Image", None))
        self.radioCorrection.setText(_translate("mainWindow", "Correction", None))
        self.radioCrop.setText(_translate("mainWindow", "Crop to Size", None))
        self.radioCLAHE.setText(_translate("mainWindow", "Equalization", None))
        self.checkToggleOverlay.setText(_translate("mainWindow", "Toggle Overlay", None))
        self.labelLayerNumber.setText(_translate("mainWindow", "<html><head/><body><p align=\"center\">0000</p></body></html>", None))
        self.groupPositionAdjustment.setTitle(_translate("mainWindow", "Position Adjustment", None))
        self.buttonCrop.setToolTip(_translate("mainWindow", "Click to move the crop boundary.", None))
        self.buttonCrop.setText(_translate("mainWindow", "╬", None))
        self.buttonShiftLeft.setToolTip(_translate("mainWindow", "Shifts the display image left by the given pixels.", None))
        self.buttonShiftLeft.setText(_translate("mainWindow", "◄", None))
        self.buttonShiftRight.setToolTip(_translate("mainWindow", "Shifts the display image right by the given pixels.", None))
        self.buttonShiftRight.setText(_translate("mainWindow", "►", None))
        self.buttonShiftDown.setToolTip(_translate("mainWindow", "Shifts the display image down by the given pixels.", None))
        self.buttonShiftDown.setText(_translate("mainWindow", "▼", None))
        self.buttonShiftUp.setToolTip(_translate("mainWindow", "Shifts the display image up by the given pixels.", None))
        self.buttonShiftUp.setText(_translate("mainWindow", "▲", None))
        self.buttonRotateACW.setToolTip(_translate("mainWindow", "Clocwise rotates the display image by the given degrees.", None))
        self.buttonRotateACW.setText(_translate("mainWindow", "↺", None))
        self.buttonRotateCW.setToolTip(_translate("mainWindow", "Anti-Clocwise rotates the display image by the given degrees.", None))
        self.buttonRotateCW.setText(_translate("mainWindow", "↻", None))
        self.labelPixels.setText(_translate("mainWindow", "Pixels", None))
        self.buttonBoundary.setToolTip(_translate("mainWindow", "Click to move the overlay boundary.", None))
        self.buttonBoundary.setText(_translate("mainWindow", "□", None))
        self.lineShiftDegrees.setText(_translate("mainWindow", "0.05", None))
        self.lineShiftPixels.setText(_translate("mainWindow", "1", None))
        self.labelDegrees.setText(_translate("mainWindow", "Degrees", None))
        self.checkSimulation.setText(_translate("mainWindow", "Simulation", None))
        self.lineLayer.setPlaceholderText(_translate("mainWindow", "LAYER", None))
        self.buttonSet.setText(_translate("mainWindow", "SET", None))
        self.buttonPhase.setText(_translate("mainWindow", "COAT", None))
        self.buttonStop.setText(_translate("mainWindow", "Stop", None))
        self.buttonInitialize.setText(_translate("mainWindow", "Initialize", None))
        self.buttonStart.setText(_translate("mainWindow", "Start", None))
        self.buttonPause.setText(_translate("mainWindow", "Pause", None))
        self.menuFile.setTitle(_translate("mainWindow", "File", None))
        self.menuSetup.setTitle(_translate("mainWindow", "Setup", None))
        self.menuPartFiles.setTitle(_translate("mainWindow", "Part Files", None))
        self.menuReportSettings.setTitle(_translate("mainWindow", "Report Settings", None))
        self.menuImageCalibration.setTitle(_translate("mainWindow", "Image Calibration", None))
        self.menuRun.setTitle(_translate("mainWindow", "Run", None))
        self.actionBuildPlatform.setText(_translate("mainWindow", "Build Platform", None))
        self.actionCLS.setText(_translate("mainWindow", "CLS", None))
        self.actionCLI.setText(_translate("mainWindow", "CLI", None))
        self.actionNewBuild.setText(_translate("mainWindow", "New Build...", None))
        self.actionOpenBuild.setText(_translate("mainWindow", "Open Build...", None))
        self.actionExportImage.setText(_translate("mainWindow", "Export Image...", None))
        self.actionError_actions.setText(_translate("mainWindow", "Defect actions", None))
        self.actionDefectActions.setText(_translate("mainWindow", "Defect Actions", None))
        self.actionNotificationSetup.setText(_translate("mainWindow", "Notification Setup", None))
        self.actionAdjustCrop.setText(_translate("mainWindow", "Adjust Crop", None))
        self.actionAdjustRotation.setText(_translate("mainWindow", "Adjust Rotation", None))
        self.actionStartBuild.setText(_translate("mainWindow", "Start Build", None))
        self.actionPauseBuild.setText(_translate("mainWindow", "Pause Build", None))
        self.actionStopBuild.setText(_translate("mainWindow", "Stop Build", None))
        self.actionExit.setText(_translate("mainWindow", "Exit", None))
        self.actionInitializeBuild.setText(_translate("mainWindow", "Initialize Build", None))

import icons_rc
