# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName(_fromUtf8("mainWindow"))
        mainWindow.setEnabled(True)
        mainWindow.resize(1214, 790)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(mainWindow.sizePolicy().hasHeightForWidth())
        mainWindow.setSizePolicy(sizePolicy)
        mainWindow.setMinimumSize(QtCore.QSize(1214, 790))
        mainWindow.setMaximumSize(QtCore.QSize(1214, 790))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/resources/logo.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        mainWindow.setWindowIcon(icon)
        mainWindow.setStatusTip(_fromUtf8(""))
        mainWindow.setIconSize(QtCore.QSize(24, 24))
        mainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.mainWidget = QtGui.QWidget(mainWindow)
        self.mainWidget.setObjectName(_fromUtf8("mainWidget"))
        self.mainFrame = QtGui.QFrame(self.mainWidget)
        self.mainFrame.setGeometry(QtCore.QRect(0, 0, 1211, 741))
        self.mainFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.mainFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.mainFrame.setObjectName(_fromUtf8("mainFrame"))
        self.widgetDisplay = QtGui.QTabWidget(self.mainFrame)
        self.widgetDisplay.setGeometry(QtCore.QRect(10, 10, 1011, 731))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.widgetDisplay.setPalette(palette)
        self.widgetDisplay.setObjectName(_fromUtf8("widgetDisplay"))
        self.widgetTab1 = QtGui.QWidget()
        self.widgetTab1.setObjectName(_fromUtf8("widgetTab1"))
        self.layerDisplay = QtGui.QLabel(self.widgetTab1)
        self.layerDisplay.setGeometry(QtCore.QRect(10, 10, 991, 681))
        self.layerDisplay.setAutoFillBackground(False)
        self.layerDisplay.setText(_fromUtf8(""))
        self.layerDisplay.setObjectName(_fromUtf8("layerDisplay"))
        self.layerDisplay.raise_()
        self.widgetDisplay.addTab(self.widgetTab1, _fromUtf8(""))
        self.widgetTab2 = QtGui.QWidget()
        self.widgetTab2.setObjectName(_fromUtf8("widgetTab2"))
        self.sliderLayerSelectCoat = QtGui.QSlider(self.widgetTab2)
        self.sliderLayerSelectCoat.setGeometry(QtCore.QRect(970, 10, 22, 681))
        self.sliderLayerSelectCoat.setOrientation(QtCore.Qt.Vertical)
        self.sliderLayerSelectCoat.setObjectName(_fromUtf8("sliderLayerSelectCoat"))
        self.widgetDisplay.addTab(self.widgetTab2, _fromUtf8(""))
        self.widgetTab3 = QtGui.QWidget()
        self.widgetTab3.setObjectName(_fromUtf8("widgetTab3"))
        self.sliderLayerSelectScan = QtGui.QSlider(self.widgetTab3)
        self.sliderLayerSelectScan.setGeometry(QtCore.QRect(970, 10, 22, 681))
        self.sliderLayerSelectScan.setOrientation(QtCore.Qt.Vertical)
        self.sliderLayerSelectScan.setObjectName(_fromUtf8("sliderLayerSelectScan"))
        self.widgetDisplay.addTab(self.widgetTab3, _fromUtf8(""))
        self.widgetTab4 = QtGui.QWidget()
        self.widgetTab4.setObjectName(_fromUtf8("widgetTab4"))
        self.widgetDisplay.addTab(self.widgetTab4, _fromUtf8(""))
        self.groupDisplayOptions = QtGui.QGroupBox(self.mainFrame)
        self.groupDisplayOptions.setGeometry(QtCore.QRect(1030, 25, 170, 200))
        self.groupDisplayOptions.setObjectName(_fromUtf8("groupDisplayOptions"))
        self.progressImageProcessing = QtGui.QProgressBar(self.groupDisplayOptions)
        self.progressImageProcessing.setEnabled(True)
        self.progressImageProcessing.setGeometry(QtCore.QRect(140, 30, 16, 127))
        self.progressImageProcessing.setProperty("value", 0)
        self.progressImageProcessing.setTextVisible(False)
        self.progressImageProcessing.setOrientation(QtCore.Qt.Vertical)
        self.progressImageProcessing.setInvertedAppearance(True)
        self.progressImageProcessing.setTextDirection(QtGui.QProgressBar.TopToBottom)
        self.progressImageProcessing.setObjectName(_fromUtf8("progressImageProcessing"))
        self.checkToggleOverlay = QtGui.QCheckBox(self.groupDisplayOptions)
        self.checkToggleOverlay.setGeometry(QtCore.QRect(30, 170, 110, 20))
        self.checkToggleOverlay.setAcceptDrops(False)
        self.checkToggleOverlay.setObjectName(_fromUtf8("checkToggleOverlay"))
        self.layoutWidget = QtGui.QWidget(self.groupDisplayOptions)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 131, 151))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.layoutDisplayOptions = QtGui.QVBoxLayout(self.layoutWidget)
        self.layoutDisplayOptions.setObjectName(_fromUtf8("layoutDisplayOptions"))
        self.radioRaw = QtGui.QRadioButton(self.layoutWidget)
        self.radioRaw.setObjectName(_fromUtf8("radioRaw"))
        self.layoutDisplayOptions.addWidget(self.radioRaw)
        self.radioCorrection = QtGui.QRadioButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.radioCorrection.setFont(font)
        self.radioCorrection.setChecked(False)
        self.radioCorrection.setObjectName(_fromUtf8("radioCorrection"))
        self.layoutDisplayOptions.addWidget(self.radioCorrection)
        self.radioCrop = QtGui.QRadioButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.radioCrop.setFont(font)
        self.radioCrop.setObjectName(_fromUtf8("radioCrop"))
        self.layoutDisplayOptions.addWidget(self.radioCrop)
        self.radioCLAHE = QtGui.QRadioButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.radioCLAHE.setFont(font)
        self.radioCLAHE.setChecked(True)
        self.radioCLAHE.setObjectName(_fromUtf8("radioCLAHE"))
        self.layoutDisplayOptions.addWidget(self.radioCLAHE)
        self.buttonStop = QtGui.QPushButton(self.mainFrame)
        self.buttonStop.setEnabled(False)
        self.buttonStop.setGeometry(QtCore.QRect(1085, 390, 60, 30))
        self.buttonStop.setBaseSize(QtCore.QSize(0, 0))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.buttonStop.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(21)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.buttonStop.setFont(font)
        self.buttonStop.setObjectName(_fromUtf8("buttonStop"))
        self.buttonStart = QtGui.QPushButton(self.mainFrame)
        self.buttonStart.setEnabled(False)
        self.buttonStart.setGeometry(QtCore.QRect(1060, 289, 110, 50))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.buttonStart.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.buttonStart.setFont(font)
        self.buttonStart.setObjectName(_fromUtf8("buttonStart"))
        self.buttonPause = QtGui.QPushButton(self.mainFrame)
        self.buttonPause.setEnabled(False)
        self.buttonPause.setGeometry(QtCore.QRect(1085, 350, 60, 30))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.buttonPause.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.buttonPause.setFont(font)
        self.buttonPause.setCheckable(True)
        self.buttonPause.setChecked(False)
        self.buttonPause.setObjectName(_fromUtf8("buttonPause"))
        self.buttonSet = QtGui.QPushButton(self.mainFrame)
        self.buttonSet.setEnabled(True)
        self.buttonSet.setGeometry(QtCore.QRect(1090, 485, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.buttonSet.setFont(font)
        self.buttonSet.setObjectName(_fromUtf8("buttonSet"))
        self.lineLayer = QtGui.QLineEdit(self.mainFrame)
        self.lineLayer.setGeometry(QtCore.QRect(1042, 486, 51, 29))
        self.lineLayer.setInputMask(_fromUtf8(""))
        self.lineLayer.setMaxLength(5)
        self.lineLayer.setAlignment(QtCore.Qt.AlignCenter)
        self.lineLayer.setObjectName(_fromUtf8("lineLayer"))
        self.labelLayerNumber = QtGui.QLabel(self.mainFrame)
        self.labelLayerNumber.setGeometry(QtCore.QRect(1080, 450, 71, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.labelLayerNumber.setFont(font)
        self.labelLayerNumber.setTextFormat(QtCore.Qt.AutoText)
        self.labelLayerNumber.setObjectName(_fromUtf8("labelLayerNumber"))
        self.groupPositionAdjustment = QtGui.QGroupBox(self.mainFrame)
        self.groupPositionAdjustment.setEnabled(False)
        self.groupPositionAdjustment.setGeometry(QtCore.QRect(1040, 530, 150, 201))
        self.groupPositionAdjustment.setObjectName(_fromUtf8("groupPositionAdjustment"))
        self.buttonCrop = QtGui.QPushButton(self.groupPositionAdjustment)
        self.buttonCrop.setGeometry(QtCore.QRect(60, 120, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.buttonCrop.setFont(font)
        self.buttonCrop.setCheckable(True)
        self.buttonCrop.setObjectName(_fromUtf8("buttonCrop"))
        self.buttonShiftLeft = QtGui.QPushButton(self.groupPositionAdjustment)
        self.buttonShiftLeft.setGeometry(QtCore.QRect(20, 120, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.buttonShiftLeft.setFont(font)
        self.buttonShiftLeft.setObjectName(_fromUtf8("buttonShiftLeft"))
        self.buttonShiftRight = QtGui.QPushButton(self.groupPositionAdjustment)
        self.buttonShiftRight.setGeometry(QtCore.QRect(100, 120, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.buttonShiftRight.setFont(font)
        self.buttonShiftRight.setObjectName(_fromUtf8("buttonShiftRight"))
        self.buttonShiftDown = QtGui.QPushButton(self.groupPositionAdjustment)
        self.buttonShiftDown.setGeometry(QtCore.QRect(60, 160, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.buttonShiftDown.setFont(font)
        self.buttonShiftDown.setObjectName(_fromUtf8("buttonShiftDown"))
        self.buttonShiftUp = QtGui.QPushButton(self.groupPositionAdjustment)
        self.buttonShiftUp.setGeometry(QtCore.QRect(60, 80, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.buttonShiftUp.setFont(font)
        self.buttonShiftUp.setObjectName(_fromUtf8("buttonShiftUp"))
        self.buttonRotateACW = QtGui.QPushButton(self.groupPositionAdjustment)
        self.buttonRotateACW.setGeometry(QtCore.QRect(20, 80, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        font.setKerning(True)
        self.buttonRotateACW.setFont(font)
        self.buttonRotateACW.setObjectName(_fromUtf8("buttonRotateACW"))
        self.buttonRotateCW = QtGui.QPushButton(self.groupPositionAdjustment)
        self.buttonRotateCW.setGeometry(QtCore.QRect(100, 160, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        font.setKerning(True)
        self.buttonRotateCW.setFont(font)
        self.buttonRotateCW.setObjectName(_fromUtf8("buttonRotateCW"))
        self.lineShiftPixels = QtGui.QLineEdit(self.groupPositionAdjustment)
        self.lineShiftPixels.setGeometry(QtCore.QRect(30, 50, 41, 20))
        self.lineShiftPixels.setMaxLength(2)
        self.lineShiftPixels.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineShiftPixels.setObjectName(_fromUtf8("lineShiftPixels"))
        self.lineShiftDegrees = QtGui.QLineEdit(self.groupPositionAdjustment)
        self.lineShiftDegrees.setGeometry(QtCore.QRect(30, 22, 41, 20))
        self.lineShiftDegrees.setMaxLength(5)
        self.lineShiftDegrees.setEchoMode(QtGui.QLineEdit.Normal)
        self.lineShiftDegrees.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineShiftDegrees.setObjectName(_fromUtf8("lineShiftDegrees"))
        self.labelDegrees = QtGui.QLabel(self.groupPositionAdjustment)
        self.labelDegrees.setGeometry(QtCore.QRect(75, 22, 50, 20))
        self.labelDegrees.setObjectName(_fromUtf8("labelDegrees"))
        self.labelPixels = QtGui.QLabel(self.groupPositionAdjustment)
        self.labelPixels.setGeometry(QtCore.QRect(75, 50, 50, 20))
        self.labelPixels.setObjectName(_fromUtf8("labelPixels"))
        self.buttonBoundary = QtGui.QPushButton(self.groupPositionAdjustment)
        self.buttonBoundary.setGeometry(QtCore.QRect(100, 80, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.buttonBoundary.setFont(font)
        self.buttonBoundary.setCheckable(True)
        self.buttonBoundary.setObjectName(_fromUtf8("buttonBoundary"))
        self.buttonPhase = QtGui.QPushButton(self.mainFrame)
        self.buttonPhase.setEnabled(True)
        self.buttonPhase.setGeometry(QtCore.QRect(1138, 485, 51, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.buttonPhase.setFont(font)
        self.buttonPhase.setCheckable(True)
        self.buttonPhase.setObjectName(_fromUtf8("buttonPhase"))
        self.labelLayerNumberTitle = QtGui.QLabel(self.mainFrame)
        self.labelLayerNumberTitle.setGeometry(QtCore.QRect(1060, 430, 110, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.labelLayerNumberTitle.setFont(font)
        self.labelLayerNumberTitle.setObjectName(_fromUtf8("labelLayerNumberTitle"))
        self.buttonInitialize = QtGui.QPushButton(self.mainFrame)
        self.buttonInitialize.setGeometry(QtCore.QRect(1040, 240, 150, 40))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(10, 167, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(10, 167, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.buttonInitialize.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.buttonInitialize.setFont(font)
        self.buttonInitialize.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.buttonInitialize.setAutoFillBackground(False)
        self.buttonInitialize.setAutoDefault(False)
        self.buttonInitialize.setObjectName(_fromUtf8("buttonInitialize"))
        mainWindow.setCentralWidget(self.mainWidget)
        self.menuBar = QtGui.QMenuBar(mainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1214, 26))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuFile = QtGui.QMenu(self.menuBar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuSetup = QtGui.QMenu(self.menuBar)
        self.menuSetup.setObjectName(_fromUtf8("menuSetup"))
        self.menuPartFiles = QtGui.QMenu(self.menuSetup)
        self.menuPartFiles.setObjectName(_fromUtf8("menuPartFiles"))
        self.menuReportSettings = QtGui.QMenu(self.menuSetup)
        self.menuReportSettings.setObjectName(_fromUtf8("menuReportSettings"))
        self.menuImageCalibration = QtGui.QMenu(self.menuSetup)
        self.menuImageCalibration.setObjectName(_fromUtf8("menuImageCalibration"))
        self.menuRun = QtGui.QMenu(self.menuBar)
        self.menuRun.setObjectName(_fromUtf8("menuRun"))
        mainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtGui.QStatusBar(mainWindow)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.statusBar.setFont(font)
        self.statusBar.setStatusTip(_fromUtf8(""))
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        mainWindow.setStatusBar(self.statusBar)
        self.actionBuildPlatform = QtGui.QAction(mainWindow)
        self.actionBuildPlatform.setObjectName(_fromUtf8("actionBuildPlatform"))
        self.actionCLS = QtGui.QAction(mainWindow)
        self.actionCLS.setObjectName(_fromUtf8("actionCLS"))
        self.actionCLI = QtGui.QAction(mainWindow)
        self.actionCLI.setEnabled(False)
        self.actionCLI.setObjectName(_fromUtf8("actionCLI"))
        self.actionNewBuild = QtGui.QAction(mainWindow)
        self.actionNewBuild.setObjectName(_fromUtf8("actionNewBuild"))
        self.actionOpenBuild = QtGui.QAction(mainWindow)
        self.actionOpenBuild.setObjectName(_fromUtf8("actionOpenBuild"))
        self.actionExportImage = QtGui.QAction(mainWindow)
        self.actionExportImage.setObjectName(_fromUtf8("actionExportImage"))
        self.actionError_actions = QtGui.QAction(mainWindow)
        self.actionError_actions.setObjectName(_fromUtf8("actionError_actions"))
        self.actionDefectActions = QtGui.QAction(mainWindow)
        self.actionDefectActions.setObjectName(_fromUtf8("actionDefectActions"))
        self.actionNotificationSetup = QtGui.QAction(mainWindow)
        self.actionNotificationSetup.setObjectName(_fromUtf8("actionNotificationSetup"))
        self.actionAdjustCrop = QtGui.QAction(mainWindow)
        self.actionAdjustCrop.setObjectName(_fromUtf8("actionAdjustCrop"))
        self.actionAdjustRotation = QtGui.QAction(mainWindow)
        self.actionAdjustRotation.setObjectName(_fromUtf8("actionAdjustRotation"))
        self.actionStartBuild = QtGui.QAction(mainWindow)
        self.actionStartBuild.setObjectName(_fromUtf8("actionStartBuild"))
        self.actionPauseBuild = QtGui.QAction(mainWindow)
        self.actionPauseBuild.setObjectName(_fromUtf8("actionPauseBuild"))
        self.actionStopBuild = QtGui.QAction(mainWindow)
        self.actionStopBuild.setObjectName(_fromUtf8("actionStopBuild"))
        self.actionExit = QtGui.QAction(mainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.menuFile.addAction(self.actionNewBuild)
        self.menuFile.addAction(self.actionOpenBuild)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExportImage)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuPartFiles.addAction(self.actionCLS)
        self.menuPartFiles.addAction(self.actionCLI)
        self.menuReportSettings.addAction(self.actionDefectActions)
        self.menuReportSettings.addAction(self.actionNotificationSetup)
        self.menuImageCalibration.addAction(self.actionAdjustCrop)
        self.menuImageCalibration.addAction(self.actionAdjustRotation)
        self.menuSetup.addAction(self.actionBuildPlatform)
        self.menuSetup.addAction(self.menuPartFiles.menuAction())
        self.menuSetup.addSeparator()
        self.menuSetup.addAction(self.menuImageCalibration.menuAction())
        self.menuSetup.addSeparator()
        self.menuSetup.addAction(self.menuReportSettings.menuAction())
        self.menuRun.addAction(self.actionStartBuild)
        self.menuRun.addAction(self.actionPauseBuild)
        self.menuRun.addSeparator()
        self.menuRun.addAction(self.actionStopBuild)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuSetup.menuAction())
        self.menuBar.addAction(self.menuRun.menuAction())

        self.retranslateUi(mainWindow)
        self.widgetDisplay.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        mainWindow.setWindowTitle(_translate("mainWindow", "Defect Monitor", None))
        self.widgetDisplay.setTabText(self.widgetDisplay.indexOf(self.widgetTab1), _translate("mainWindow", "Current Layer", None))
        self.widgetDisplay.setTabText(self.widgetDisplay.indexOf(self.widgetTab2), _translate("mainWindow", "Coat Explorer", None))
        self.widgetDisplay.setTabText(self.widgetDisplay.indexOf(self.widgetTab3), _translate("mainWindow", "Scan Explorer", None))
        self.widgetDisplay.setTabText(self.widgetDisplay.indexOf(self.widgetTab4), _translate("mainWindow", "Meltpool Analysis", None))
        self.groupDisplayOptions.setTitle(_translate("mainWindow", "Display Options", None))
        self.checkToggleOverlay.setText(_translate("mainWindow", "Toggle Overlay", None))
        self.radioRaw.setText(_translate("mainWindow", "Raw Image", None))
        self.radioCorrection.setText(_translate("mainWindow", "Correction", None))
        self.radioCrop.setText(_translate("mainWindow", "Crop", None))
        self.radioCLAHE.setText(_translate("mainWindow", "Equalization", None))
        self.buttonStop.setText(_translate("mainWindow", "█", None))
        self.buttonStart.setText(_translate("mainWindow", "START", None))
        self.buttonPause.setText(_translate("mainWindow", " ▌▌", None))
        self.buttonSet.setText(_translate("mainWindow", "SET", None))
        self.lineLayer.setPlaceholderText(_translate("mainWindow", "LAYER", None))
        self.labelLayerNumber.setText(_translate("mainWindow", "<html><head/><body><p align=\"center\">0000</p></body></html>", None))
        self.groupPositionAdjustment.setTitle(_translate("mainWindow", "Position Adjustment", None))
        self.buttonCrop.setToolTip(_translate("mainWindow", "Crop toggle", None))
        self.buttonCrop.setText(_translate("mainWindow", "╬", None))
        self.buttonShiftLeft.setText(_translate("mainWindow", "◄", None))
        self.buttonShiftRight.setText(_translate("mainWindow", "►", None))
        self.buttonShiftDown.setText(_translate("mainWindow", "▼", None))
        self.buttonShiftUp.setText(_translate("mainWindow", "▲", None))
        self.buttonRotateACW.setText(_translate("mainWindow", "↓", None))
        self.buttonRotateCW.setText(_translate("mainWindow", "↓", None))
        self.lineShiftPixels.setText(_translate("mainWindow", "1", None))
        self.lineShiftDegrees.setText(_translate("mainWindow", "0.05", None))
        self.labelDegrees.setText(_translate("mainWindow", "Degrees", None))
        self.labelPixels.setText(_translate("mainWindow", "Pixels", None))
        self.buttonBoundary.setToolTip(_translate("mainWindow", "Move overlay boundary", None))
        self.buttonBoundary.setText(_translate("mainWindow", "□", None))
        self.buttonPhase.setText(_translate("mainWindow", "COAT", None))
        self.labelLayerNumberTitle.setText(_translate("mainWindow", "<html><head/><body><p align=\"center\">Layer Number</p></body></html>", None))
        self.buttonInitialize.setText(_translate("mainWindow", "INITIALIZE", None))
        self.menuFile.setTitle(_translate("mainWindow", "File", None))
        self.menuSetup.setTitle(_translate("mainWindow", "Setup", None))
        self.menuPartFiles.setTitle(_translate("mainWindow", "Part Files", None))
        self.menuReportSettings.setTitle(_translate("mainWindow", "Report Settings", None))
        self.menuImageCalibration.setTitle(_translate("mainWindow", "Image Calibration", None))
        self.menuRun.setTitle(_translate("mainWindow", "Run", None))
        self.actionBuildPlatform.setText(_translate("mainWindow", "Build Platform", None))
        self.actionCLS.setText(_translate("mainWindow", "CLS", None))
        self.actionCLI.setText(_translate("mainWindow", "CLI", None))
        self.actionNewBuild.setText(_translate("mainWindow", "New Build...", None))
        self.actionOpenBuild.setText(_translate("mainWindow", "Open Build...", None))
        self.actionExportImage.setText(_translate("mainWindow", "Export Image...", None))
        self.actionError_actions.setText(_translate("mainWindow", "Defect actions", None))
        self.actionDefectActions.setText(_translate("mainWindow", "Defect Actions", None))
        self.actionNotificationSetup.setText(_translate("mainWindow", "Notification Setup", None))
        self.actionAdjustCrop.setText(_translate("mainWindow", "Adjust Crop", None))
        self.actionAdjustRotation.setText(_translate("mainWindow", "Adjust Rotation", None))
        self.actionStartBuild.setText(_translate("mainWindow", "Start Build", None))
        self.actionPauseBuild.setText(_translate("mainWindow", "Pause Build", None))
        self.actionStopBuild.setText(_translate("mainWindow", "Stop Build", None))
        self.actionExit.setText(_translate("mainWindow", "Exit", None))

import icons_rc
